/* Crops from CEVNI Revision 6 Annex 7. Source and page details live in the artwork audit. */
(function(){
  const root='assets/cevni/annex7/rev6/';
  const plates={
    'A.1':{file:'annex7-a-1a.png',label:'No entry — board example',page:124},
    'A.2':{file:'annex7-a-2.png',label:'No overtaking',page:125},
    'A.1a':{file:'annex7-a-1a.png',label:'No entry — board',page:124},
    'A.1b':{file:'annex7-a-1b.png',label:'No entry — two red lights vertically',page:124},
    'A.1c':{file:'annex7-a-1c.png',label:'No entry — one red light',page:124},
    'A.1d':{file:'annex7-a-1d.png',label:'No entry — two red lights horizontally',page:124},
    'A.1e':{file:'annex7-a-1e.png',label:'No entry — two red flags',page:124},
    'A.1f':{file:'annex7-a-1f.png',label:'No entry — one red flag',page:124},
    'A.1.1':{file:'annex7-a-1-1.png',label:'No entry except non-motorized small craft',page:124},
    'A.3':{file:'annex7-a-3.png',label:'No overtaking of convoys by convoys',page:125},
    'A.4':{file:'annex7-a-4.png',label:'No passing or overtaking',page:125},
    'A.4.1':{file:'annex7-a-4-1.png',label:'No passing or overtaking of convoys by convoys',page:125},
    'A.5':{file:'annex7-a-5.png',label:'No berthing on this side',page:126},
    'A.5.1':{file:'annex7-a-5-1.png',label:'No berthing within the indicated breadth',page:126},
    'A.6':{file:'annex7-a-6.png',label:'No anchoring or trailing anchors, cables or chains',page:126},
    'A.7':{file:'annex7-a-7.png',label:'No making fast to the bank',page:126},
    'A.8':{file:'annex7-a-8.png',label:'No turning',page:126},
    'A.9a':{file:'annex7-a-9a.png',label:'Do not create wash — board',page:127},
    'A.9b':{file:'annex7-a-9b.png',label:'Do not create wash — red over white light',page:127},
    'A.11a':{file:'annex7-a-11a.png',label:'Entry prohibited, prepare to get under way — horizontal lights',page:127},
    'A.11b':{file:'annex7-a-11b.png',label:'Entry prohibited, prepare to get under way — vertical lights',page:127},
    'A.11c':{file:'annex7-a-11c.png',label:'Entry prohibited, prepare to get under way — extinguished light',page:127},
    'A.12':{file:'annex7-a-12.png',label:'Motorized craft prohibited',page:128},
    'A.13':{file:'annex7-a-13.png',label:'Sports or pleasure craft prohibited',page:128},
    'A.14':{file:'annex7-a-14.png',label:'Water skiing prohibited',page:128},
    'A.15':{file:'annex7-a-15.png',label:'Sailing vessels prohibited',page:128},
    'A.16':{file:'annex7-a-16.png',label:'Other craft prohibited',page:128},
    'A.17':{file:'annex7-a-17.png',label:'Sailboards prohibited',page:129},
    'A.18':{file:'annex7-a-18.png',label:'End of high speed zone',page:129},
    'A.19':{file:'annex7-a-19.png',label:'Launching or beaching prohibited',page:129},
    'A.20':{file:'annex7-a-20.png',label:'Water bikes prohibited',page:129},
    'B.1':{file:'annex7-b-1.png',label:'Proceed in direction shown',page:130},
    'B.2a':{file:'annex7-b-2a.png',label:'Move to port side of fairway',page:130},
    'B.2b':{file:'annex7-b-2b.png',label:'Move to starboard side of fairway',page:130},
    'B.3a':{file:'annex7-b-3a.png',label:'Keep to port side of fairway',page:131},
    'B.3b':{file:'annex7-b-3b.png',label:'Keep to starboard side of fairway',page:131},
    'B.4a':{file:'annex7-b-4a.png',label:'Cross fairway to port',page:131},
    'B.4b':{file:'annex7-b-4b.png',label:'Cross fairway to starboard',page:131},
    'B.5':{file:'annex7-b-5.png',label:'Stop',page:132},
    'B.6':{file:'annex7-b-6.png',label:'Speed limit example',page:132},
    'B.7':{file:'annex7-b-7.png',label:'Give a sound signal',page:132},
    'B.8':{file:'annex7-b-8.png',label:'Keep a particularly sharp lookout',page:132},
    'B.9a':{file:'annex7-b-9a.png',label:'Do not enter or cross main waterway',page:133},
    'B.9b':{file:'annex7-b-9b.png',label:'Do not enter or cross main waterway',page:133},
    'B.10':{file:'annex7-b-10.png',label:'Facilitate vessels leaving harbour or tributary',page:133},
    'B.11a':{file:'annex7-b-11a.png',label:'Establish radiotelephone link',page:134},
    'B.11b':{file:'annex7-b-11b.png',label:'Establish radiotelephone link on shown channel',page:134},
    'B.12':{file:'annex7-b-12.png',label:'Use onshore power supply point',page:134},
    'C.1a':{file:'annex7-c-1a.png',label:'Depth limited — plain board',page:135},
    'C.1b':{file:'annex7-c-1b.png',label:'Depth limited — figure example',page:135},
    'C.2a':{file:'annex7-c-2a.png',label:'Headroom limited — plain board',page:135},
    'C.2b':{file:'annex7-c-2b.png',label:'Headroom limited — figure example',page:135},
    'C.3a':{file:'annex7-c-3a.png',label:'Width limited — plain board',page:135},
    'C.3b':{file:'annex7-c-3b.png',label:'Width limited — figure example',page:135},
    'C.4':{file:'annex7-c-4.png',label:'Restrictions on navigation — see information plate',page:135},
    'C.5a':{file:'annex7-c-5a.png',label:'Channel distance from bank — left-facing example',page:135},
    'C.5b':{file:'annex7-c-5b.png',label:'Channel distance from bank — right-facing example',page:135},
    'D.1a':{file:'annex7-d-1a.png',label:'Recommended opening — both directions (diamond)',page:136},
    'D.1b':{file:'annex7-d-1b.png',label:'Recommended opening — both directions (circle)',page:136},
    'D.1c':{file:'annex7-d-1c.png',label:'Recommended opening — indicated direction only (two diamonds across)',page:136},
    'D.1d':{file:'annex7-d-1d.png',label:'Recommended opening — indicated direction only (two diamonds vertically)',page:136},
    'D.1e':{file:'annex7-d-1e.png',label:'Recommended opening — indicated direction only (two circles across)',page:136},
    'D.1f':{file:'annex7-d-1f.png',label:'Recommended opening — indicated direction only (two circles vertically)',page:136},
    'D.2a':{file:'annex7-d-2a.png',label:'Keep within indicated bridge opening — diamond marks',page:136},
    'D.2b':{file:'annex7-d-2b.png',label:'Keep within indicated bridge opening — green lights',page:136},
    'D.3a':{file:'annex7-d-3a.png',label:'Recommended direction — arrow board',page:137},
    'D.3b':{file:'annex7-d-3b.png',label:'Recommended direction — fixed to isophase light',page:137},
    'E.1':{file:'annex7-e-1a.png',label:'Entry permitted — board example',page:137},
    'E.1a':{file:'annex7-e-1a.png',label:'Entry permitted — board',page:137},
    'E.1b':{file:'annex7-e-1b.png',label:'Entry permitted — single green light',page:137},
    'E.1c':{file:'annex7-e-1c.png',label:'Entry permitted — two green lights horizontally',page:137},
    'E.1d':{file:'annex7-e-1d.png',label:'Entry permitted — two green lights vertically',page:137},
    'E.3':{file:'annex7-e-3.png',label:'Weir',page:138},
    'E.4a':{file:'annex7-e-4a.png',label:'Ferry-boat not moving independently',page:138},
    'E.4b':{file:'annex7-e-4b.png',label:'Ferry-boat moving independently',page:138},
    'E.5':{file:'annex7-e-5.png',label:'Berthing permitted on this side of the waterway',page:138},
    'E.5.1':{file:'annex7-e-5-1.png',label:'Berthing permitted within indicated breadth',page:138},
    'E.5.2':{file:'annex7-e-5-2.png',label:'Berthing permitted between indicated distances',page:139},
    'E.5.3':{file:'annex7-e-5-3.png',label:'Maximum number of vessels permitted to berth abreast',page:139},
    'E.5.4':{file:'annex7-e-5-4.png',label:'Reserved berthing — pushing-navigation vessels, no Article 3.14 marking required',page:139},
    'E.5.5':{file:'annex7-e-5-5.png',label:'Reserved berthing — pushing-navigation vessels carrying one blue light/cone',page:139},
    'E.5.6':{file:'annex7-e-5-6.png',label:'Reserved berthing — pushing-navigation vessels carrying two blue lights/cones',page:139},
    'E.5.7':{file:'annex7-e-5-7.png',label:'Reserved berthing — pushing-navigation vessels carrying three blue lights/cones',page:140},
    'E.5.8':{file:'annex7-e-5-8.png',label:'Reserved berthing — other vessels, no Article 3.14 marking required',page:140},
    'E.5.9':{file:'annex7-e-5-9.png',label:'Reserved berthing — other vessels carrying one blue light/cone',page:140},
    'E.5.10':{file:'annex7-e-5-10.png',label:'Reserved berthing — other vessels carrying two blue lights/cones',page:140},
    'E.5.11':{file:'annex7-e-5-11.png',label:'Reserved berthing — other vessels carrying three blue lights/cones',page:140},
    'E.5.12':{file:'annex7-e-5-12.png',label:'Reserved berthing — all vessels, no Article 3.14 marking required',page:141},
    'E.5.13':{file:'annex7-e-5-13.png',label:'Reserved berthing — all vessels carrying one blue light/cone',page:141},
    'E.5.14':{file:'annex7-e-5-14.png',label:'Reserved berthing — all vessels carrying two blue lights/cones',page:141},
    'E.5.15':{file:'annex7-e-5-15.png',label:'Reserved berthing — all vessels carrying three blue lights/cones',page:141},
    'E.6':{file:'annex7-e-6.png',label:'Anchoring or trailing anchors/cables/chains permitted',page:141},
    'E.6.1':{file:'annex7-e-6-1.png',label:'Use of spuds permitted',page:142},
    'E.7':{file:'annex7-e-7.png',label:'Making fast to the bank permitted',page:142},
    'E.7.1':{file:'annex7-e-7-1.png',label:'Berthing area reserved for loading/unloading vehicles',page:142},
    'E.8':{file:'annex7-e-8.png',label:'Turning area',page:142},
    'E.9a':{file:'annex7-e-9a.png',label:'Approaching waterways are tributaries of this waterway',page:143},
    'E.9b':{file:'annex7-e-9b.png',label:'Approaching waterways are tributaries of this waterway',page:143},
    'E.9c':{file:'annex7-e-9c.png',label:'Approaching waterways are tributaries of this waterway',page:143},
    'E.10a':{file:'annex7-e-10a.png',label:'This waterway is tributary of the waterway being approached',page:143},
    'E.10b':{file:'annex7-e-10b.png',label:'This waterway is tributary of the waterway being approached',page:143},
    'E.11a':{file:'annex7-e-11a.png',label:'End of one-direction prohibition/obligation or restriction',page:144},
    'E.11b':{file:'annex7-e-11b.png',label:'End of one-direction prohibition/obligation or restriction',page:144},
    'E.12a':{file:'annex7-e-12a.png',label:'Advance signal — fixed white light: difficulty ahead',page:144},
    'E.12b':{file:'annex7-e-12b.png',label:'Advance signal — fixed white lights: difficulty ahead',page:144},
    'E.12c':{file:'annex7-e-12c.png',label:'Advance signal — isophase white light: may proceed',page:144},
    'E.12d':{file:'annex7-e-12d.png',label:'Advance signal — isophase white lights: may proceed',page:144},
    'E.13':{file:'annex7-e-13.png',label:'Drinking-water supply',page:144},
    'E.14':{file:'annex7-e-14.png',label:'Telephone',page:145},
    'E.15':{file:'annex7-e-15.png',label:'Motorized vessels permitted',page:145},
    'E.16':{file:'annex7-e-16.png',label:'Sports or pleasure craft permitted',page:145},
    'E.17':{file:'annex7-e-17.png',label:'Water skiing permitted',page:145},
    'E.18':{file:'annex7-e-18.png',label:'Sailing vessels permitted',page:145},
    'E.19':{file:'annex7-e-19.png',label:'Craft other than motorized vessels or sailing craft permitted',page:146},
    'E.20':{file:'annex7-e-20.png',label:'Use of sailboards permitted',page:146},
    'E.21':{file:'annex7-e-21.png',label:'High-speed zone for small sport/pleasure craft',page:146},
    'E.22':{file:'annex7-e-22.png',label:'Launching or beaching of small craft permitted',page:146},
    'E.23':{file:'annex7-e-23.png',label:'Nautical information by radiotelephone on channel indicated',page:146},
    'E.24':{file:'annex7-e-24.png',label:'Water bikes permitted',page:147},
    'E.25':{file:'annex7-e-25.png',label:'Electrical power supply point',page:147},
    'E.26':{file:'annex7-e-26.png',label:'Winter harbour',page:147},
    'E.26.1':{file:'annex7-e-26-1.png',label:'Maximum number of vessels permitted to berth in winter harbour',page:147},
    'E.27':{file:'annex7-e-27.png',label:'Winter shelter',page:148},
    'E.27.1':{file:'annex7-e-27-1.png',label:'Winter shelter berthing limits',page:148},
    'E.2':{file:'annex7-e-2.png',label:'Overhead cable crossing',page:137}
  };
  for(const [code,plate] of Object.entries(plates))plate.asset=root+plate.file;
  window.PW_CEVNI_ANNEX7_OFFICIAL_PLATES=plates;
  window.PW_CEVNI_ANNEX7_AUX_EXAMPLES={
    'AUX-A':root+'annex7-aux-a.png',
    'AUX-B':root+'annex7-aux-b.png',
    'AUX-C':root+'annex7-aux-c.png',
    'AUX-D':root+'annex7-aux-d.png'
  };
  const keep=new Set();
  for(const sign of window.PW_CEVNI_SIGN_LIBRARY||[]){
    const source=plates[sign.code];
    if(source){sign.svg='<img src="'+source.asset+'" alt="'+source.label+'">';sign.asset=source.asset;}
    else if(!keep.has(sign.code))sign.svg='<div class="pw1540CodePlate '+sign.code[0]+'">'+sign.code+'</div>';
  }
})();
