/* Original Project Watch reference and training data. */
window.PW_ORIGINAL_LIBRARIES=window.PW_ORIGINAL_LIBRARIES||{};
window.PW_ORIGINAL_LIBRARIES.AIS_TRAINING_TARGETS=[
 {id:'a1',name:'MERIDIAN STAR',mmsi:'232001101',imo:'9301101',call:'MSTA7',cls:'A',type:'Cargo',colour:'#66cfa2',x:-2.7,y:2.1,cog:128,hdg:124,sog:13.4,rot:0,status:'Under way using engine',dest:'LIVERPOOL',eta:'15 SEP 04:20',draught:'8.2 m',len:'182 m',beam:'28 m',age:2},
 {id:'a2',name:'NORTH CHANNEL',mmsi:'235004208',imo:'9464208',call:'2NCH4',cls:'A',type:'Tanker',colour:'#e8756f',x:2.1,y:1.1,cog:248,hdg:247,sog:11.8,rot:-2,status:'Under way using engine',dest:'BELFAST',eta:'15 SEP 02:45',draught:'9.6 m',len:'144 m',beam:'23 m',age:3},
 {id:'a3',name:'ISLAND FERRY',mmsi:'235011425',imo:'9811425',call:'2IFR8',cls:'A',type:'Passenger',colour:'#7398ef',x:-1.2,y:-2.6,cog:018,hdg:020,sog:17.2,rot:1,status:'Under way using engine',dest:'DOUGLAS',eta:'14 SEP 23:35',draught:'4.8 m',len:'96 m',beam:'18 m',age:1},
 {id:'a4',name:'SEA HARVEST',mmsi:'235099114',imo:'',call:'MSEA6',cls:'A',type:'Fishing',colour:'#efa44e',x:2.9,y:-1.8,cog:302,hdg:290,sog:5.8,rot:4,status:'Engaged in fishing',dest:'',eta:'',draught:'3.1 m',len:'24 m',beam:'7 m',age:5},
 {id:'a5',name:'COAST RUNNER',mmsi:'235771902',imo:'',call:'',cls:'B',type:'Pleasure',colour:'#d987d3',x:.7,y:2.8,cog:188,hdg:176,sog:8.1,rot:null,status:'',dest:'',eta:'',draught:'',len:'13 m',beam:'4 m',age:14},
 {id:'a6',name:'TUG ALPHA',mmsi:'232551120',imo:'9123411',call:'MTUG5',cls:'A',type:'Tug',colour:'#5dcac4',x:-3.0,y:-.6,cog:082,hdg:080,sog:9.4,rot:0,status:'Restricted manoeuvrability',dest:'WORK AREA',eta:'',draught:'4.0 m',len:'31 m',beam:'10 m',age:4},
 {id:'a7',name:'WESTERN YACHT',mmsi:'235888701',imo:'',call:'',cls:'B',type:'Pleasure',colour:'#d987d3',x:3.3,y:2.6,cog:224,hdg:218,sog:6.7,rot:null,status:'',dest:'',eta:'',draught:'',len:'15 m',beam:'4.5 m',age:22},
 {id:'a8',name:'OLD SIGNAL',mmsi:'235550099',imo:'',call:'2OLD9',cls:'A',type:'Cargo',colour:'#7c9b96',x:-.3,y:3.4,cog:194,hdg:193,sog:10.2,rot:0,status:'Under way using engine',dest:'HEYSHAM',eta:'',draught:'5.6 m',len:'88 m',beam:'14 m',age:75,lost:true}
];
window.PW_ORIGINAL_LIBRARIES.AIS_STAGE8_Q=[
 {q:'What is the best description of AIS on the bridge?',a:['An additional source of navigational information that supports situational awareness','A replacement for visual lookout when every target has a name','A system that determines which vessel is stand-on','A collision-avoidance autopilot'],c:0},
 {q:'A vessel is visible ahead but no AIS target appears. What should you conclude?',a:['The vessel may simply not be transmitting or fitted with AIS; continue using all available means','It is a false visual contact','It must be under 20 metres','It has right of way'],c:0},
 {q:'What does COG describe?',a:['The direction the vessel is moving over the ground','The direction the bow is pointing','The compass error','The relative bearing of the target'],c:0},
 {q:'AIS shows COG 082° and heading 074°. Which statement is sound?',a:['The values describe different things and can legitimately differ','The heading sensor must be broken','COG should be ignored for all purposes','The vessel must be turning to port'],c:0},
 {q:'A target has CPA 0.2 NM and TCPA 8 minutes. What is the safest interpretation?',a:['It is a predicted close approach requiring attention, cross-checking and COLREG assessment','AIS has ordered you to alter course','The target is definitely the give-way vessel','The collision will occur in exactly eight minutes'],c:0},
 {q:'Why should destination, ETA or navigational status be treated cautiously?',a:['Some AIS information depends on manual entry and may be outdated or wrong','AIS encrypts those fields at sea','Only radar can receive voyage data','They are calculated from CPA'],c:0},
 {q:'A grey/lost AIS target stops updating. What does that prove?',a:['Only that fresh AIS reports are no longer being received; the vessel may still be present','The vessel has sunk','The vessel has left radar range','The vessel has switched to Class A'],c:0},
 {q:'Which statement about Class B AIS is safest?',a:['Do not expect every Class B target to provide the same data/reporting behaviour as Class A','Class B targets can be ignored for collision risk','Class B always transmits more often than Class A','Class B is shore-station data only'],c:0},
 {q:'An AIS target position and radar echo do not correlate well. What should you do?',a:['Investigate and cross-check rather than blindly trusting the AIS position','Delete the radar target','Assume the radar is wrong','Call the AIS target and follow whatever it says'],c:0},
 {q:'Which principle should finish every AIS lesson?',a:['Use AIS to supplement lookout, radar where fitted and COLREG judgement—not replace them','If AIS gives a ship name, VHF agreement overrides COLREGs','A good CPA means no further monitoring is required','AIS displays every navigational hazard'],c:0}
];
