/* Original recreational learning content. Sources listed separately below. */
window.PW_BOAT_SYSTEMS = Object.freeze({
 version:'1.94.0',
 lessons:[
  {title:'How a boat stays upright',subtitle:'Buoyancy and righting',art:'stability',lead:'A boat floats when it displaces enough water to support its weight. Its ability to recover from heel also depends on hull shape, loading and openings.',points:[['Buoyancy','The hull displaces water and supports the boat. More load generally increases displacement and draught; it does not automatically improve safety.'],['Heel and recovery','A sideways force heels the boat. Hull form, ballast and the centre of gravity affect how it responds. A quick snap upright is not proof of a safe stability margin.'],['Boat-specific limits','Use the builder’s manual, capacity and loading information for the actual vessel. A training sketch cannot establish safe heel angles or loading limits.']],scenario:'A crew member says a heavily loaded boat feels solid because it rolls less. Is that enough evidence? No. Check the loading limits, freeboard and how the weight is distributed.',takeaway:'A comfortable motion is not a stability certificate.'},
  {title:'Load low, secure and within limits',subtitle:'People, gear and tanks',art:'loading',lead:'Where weight sits matters as much as how much is aboard.',points:[['High weight','Heavy items on a roof or flybridge raise the centre of gravity. Keep stores low where the builder permits and secure them against movement.'],['Side-to-side balance','Do not gather everyone on one side or use a permanent list as a reason to add arbitrary counterweight. Find the cause.'],['Liquid movement','Water in a partly filled space can shift as the boat heels. Free water in a bilge or on deck is especially concerning; remove it and find the source.']],scenario:'Several heavy boxes are stacked on the cabin roof for a trip. Move them to approved low stowage, secure them and check total loading.',takeaway:'Check weight, position, restraint and the boat’s limits.'},
  {title:'Keep the water outside',subtitle:'Openings, drains and bilges',art:'watertight',lead:'Stability can deteriorate quickly if water enters or stays aboard.',points:[['Openings','Know the location and purpose of seacocks, through-hulls, hatches and doors. Keep closures accessible and use them as specified for the conditions.'],['Drains and pumps','Check cockpit drains, bilge pump modes, alarms and manual means of removing water. A pump manages water; it does not repair an ingress source.'],['Investigate early','Unexpected bilge water, a new list or repeated pump cycling requires prompt action: protect people, locate and control ingress if safe, and seek help early.']],scenario:'The automatic bilge pump cycles repeatedly. Do not treat the pump as the fix. Find the inflow, prepare a safe return or call for assistance.',takeaway:'Keep openings sound, drainage clear and water ingress visible.'},
  {title:'Propulsion and cooling',subtitle:'Engine, raw water and exhaust',art:'engine',lead:'Understand the flow of energy and cooling well enough to spot a problem before propulsion is lost.',points:[['Before starting','Check fuel, oil, coolant when cold, belts where accessible, leaks and the raw-water intake or strainer as the vessel manual directs.'],['While running','Watch the instruments, alarms and exhaust water where applicable. A temperature alarm, lost cooling flow or new smell needs prompt response.'],['Safe response','Reduce load or stop the engine as appropriate, assess the situation, avoid hot pressurised coolant and rotating machinery, and follow the engine manual.']],scenario:'The temperature alarm sounds and exhaust water flow has stopped. Reduce load, move to a safe situation, stop as directed and investigate without opening a hot coolant cap.',takeaway:'Know your normal readings and respond to change.'},
  {title:'Fuel and range',subtitle:'Supply, filtration and reserve',art:'fuel',lead:'A reliable fuel supply means more than a gauge showing fuel in the tank.',points:[['Follow the path','Identify the tank, shutoff, filters or water separator, engine feed and return where fitted. Know which valves are normally open.'],['Contamination','Water or debris can block filters and stop an engine. Inspect and maintain to the manufacturer’s schedule; protect filler and vent fittings.'],['Reserve','Plan range using realistic consumption and a margin for weather, delay and diversion. Never rely on the last indicated litres.']],scenario:'An engine loses power in rough water and a fuel filter alarm appears. Prioritise sea room and crew safety, then follow the boat’s fault procedure; do not randomly switch valves.',takeaway:'Know the system and carry a realistic fuel reserve.'},
  {title:'Electrical power aboard',subtitle:'Batteries, charging and isolation',art:'electrical',lead:'Know what supplies the essential circuits and how to isolate a fault.',points:[['Sources and loads','Identify start and domestic batteries, alternator, shore power, charger, inverter and labelled distribution panels where fitted.'],['Protection','Fuses and breakers protect wiring. Repeated trips, heat, smell or damaged cable require investigation, not a larger fuse or repeated resets.'],['Isolation','Know the master switches and shore-power disconnect. Use approved procedures for your system; high-current DC and mains equipment need competent work.']],scenario:'A navigation-light breaker trips again after one reset. Use the appropriate alternative lighting and make a safe plan; do not fit a higher-rated breaker.',takeaway:'Preserve essential power and investigate abnormal heat or trips.'},
  {title:'Steering and control',subtitle:'Helm, drive and backups',art:'steering',lead:'Steering relies on several linked parts; know what you can check and what backup the boat actually has.',points:[['Normal path','Helm input may reach rudder, outboard or drive mechanically, hydraulically or electronically. Locate the relevant controls and indications.'],['Pre-departure','Check helm response, gear engagement and steering space in safe conditions. Watch for leaks, unusual resistance or unexpected autopilot behaviour.'],['Loss of control','Reduce speed, warn the crew, establish sea room, use a documented backup only if fitted and appropriate, and call for help before options run out.']],scenario:'The wheel turns but the boat does not respond. Disengage autopilot if relevant, reduce speed, assess the steering system and seek assistance early.',takeaway:'A backup must be known and checked, not assumed.'},
  {title:'A practical fault routine',subtitle:'From warning to safe decision',art:'response',lead:'A good skipper notices the first abnormal sign, protects the crew and chooses a safe course before a minor fault becomes urgent.',points:[['Notice','Brief the crew on normal sounds, smells, gauges, bilge level and alarms. Record what changed and when.'],['Stabilise','Keep clear of hazards, reduce demand on the failing system, use suitable safety equipment and communicate the situation.'],['Decide','Use the boat-specific manual and competence available. If propulsion, steering, flooding or fire threatens safety, seek help early using the appropriate distress or urgency procedure.']],scenario:'A persistent bilge alarm and loss of charging occur together. Treat them as related until checked: protect crew, inspect for ingress if safe, conserve power and call for help as needed.',takeaway:'People and sea room first; diagnose only when safe.'}
 ],
 quiz:[
  ['A boat rolls less after heavy roof loading. What does that prove?',['It is safer','It proves no safe stability margin','The load is below the centre of gravity'],1,'Comfortable motion is not a stability assessment.'],
  ['What is the best place for heavy stores?',['High and unrestrained','Low, secure and in approved stowage','All on one side'],1,'Use the builder’s loading guidance and secure stores.'],
  ['What is free water in a bilge likely to do?',['Move as the boat heels and worsen stability','Increase the ballast safely','Improve bilge pump capacity'],0,'Shifting free water is a serious concern.'],
  ['An automatic bilge pump runs repeatedly. What next?',['Ignore it because it works','Find the source and make a safe plan','Disconnect the alarm'],1,'A pump does not fix ingress.'],
  ['When is it safe to open a hot pressurised coolant cap?',['Immediately after an alarm','At sea while running','Only as directed after the system has cooled'],2,'Hot coolant can cause serious burns.'],
  ['A cooling alarm sounds and exhaust water flow stops. What first?',['Increase engine load','Respond promptly and follow the boat’s procedure','Wait for the alarm to clear'],1,'Protect the engine and boat.'],
  ['What belongs in a fuel plan?',['Gauge reading alone','A realistic reserve for delay and diversion','Only the shortest route consumption'],1,'Allow a sensible reserve.'],
  ['A breaker trips repeatedly. What should you do?',['Replace it with a larger rating','Investigate the fault and use safe alternatives','Hold it on'],1,'The protective device indicates a fault.'],
  ['What should you know about the battery system?',['Only its brand','Sources, essential loads and isolation points','Only charger wattage'],1,'Know how essential power is supplied and isolated.'],
  ['The boat stops answering the helm. What is sensible?',['Keep full speed','Reduce speed, gain sea room and assess backups','Assume autopilot will fix it'],1,'Preserve options and seek help early.'],
  ['Do all boats have emergency steering?',['Yes','Only if documented and fitted','Only motorboats'],1,'Never assume a backup exists.'],
  ['A new list and bilge alarm occur together. What priority?',['Protect crew and investigate ingress if safe','Add weight on the opposite side','Continue the passage'],0,'Treat potential flooding promptly.']
 ],
 sources:[
  ['RYA: Boat ready for summer','https://www.rya.org.uk/water-safety/boat-safety-and-maintenance/get-your-boat-ready-for-summer/'],
  ['RYA: Dealing with diesel engines','https://www.rya.org.uk/water-safety/boat-safety-and-maintenance/dealing-with-diesel-engines/'],
  ['RYA: Electrical systems maintenance','https://www.rya.org.uk/members-legal-advice/buying-owning/electrical-systems-maintenance/'],
  ['RYA: Engine checks and fuel contamination','https://www.rya.org.uk/water-safety/boat-safety-and-maintenance/engine-checks-preventing-fuel-contamination/'],
  ['RYA: Water ingress, loading and free surface','https://www.rya.org.uk/network/clubs-and-affiliates/sailability/vessels-with-drop-bows-reflecting-on-good-practice/'],
  ['RYA: Equipment for UK pleasure vessels','https://www.rya.org.uk/water-safety/equipment-for-uk-pleasure-vessels/']
 ]
});
