/* Original Project Watch reference and training data. */
window.PW_ORIGINAL_LIBRARIES=window.PW_ORIGINAL_LIBRARIES||{};
window.PW_ORIGINAL_LIBRARIES.BUOY_TRAINING={
 port:{day:'Red body; cylindrical / can shape or red can topmark where fitted.',pass:'LEAVE TO PORT',choice:'port',explain:'In IALA Region A, when proceeding in the conventional direction of buoyage, a port-hand lateral mark identifies the port side of the channel. Keep the red mark on your port side.',flash:'Red light when fitted. Any rhythm except composite group flashing (2+1). The 4-second flash shown in Project Watch is a representative training rhythm, not a universal characteristic.'},
 starboard:{day:'Green body; conical shape or single green cone point upward where fitted.',pass:'LEAVE TO STARBOARD',choice:'starboard',explain:'In IALA Region A, when proceeding in the conventional direction of buoyage, a starboard-hand lateral mark identifies the starboard side of the channel. Keep the green mark on your starboard side.',flash:'Green light when fitted. Any rhythm except composite group flashing (2+1). The 4-second flash shown here is representative only.'},
 prefStbd:{day:'Red with one broad green horizontal band; red can topmark where fitted.',pass:'PREFERRED CHANNEL IS TO STARBOARD • LEAVE MARK TO PORT',choice:'port',explain:'This is a modified port-hand lateral mark used at a channel division. Treat it as the port-hand boundary of the preferred channel to starboard.',flash:'Red composite group flashing (2+1). Count two flashes, a pause, then one.'},
 prefPort:{day:'Green with one broad red horizontal band; green cone point upward where fitted.',pass:'PREFERRED CHANNEL IS TO PORT • LEAVE MARK TO STARBOARD',choice:'starboard',explain:'This is a modified starboard-hand lateral mark used at a channel division. Treat it as the starboard-hand boundary of the preferred channel to port.',flash:'Green composite group flashing (2+1). Count two flashes, a pause, then one.'},
 north:{day:'Black above yellow. Two black cones, both points upward.',pass:'PASS NORTH OF THE MARK',choice:'north',explain:'A North Cardinal tells you that the best navigable water is to the north of the mark.',flash:'White continuous quick or very quick flashing. North has no numbered clock-face group.'},
 east:{day:'Black with one broad yellow band. Two black cones base-to-base.',pass:'PASS EAST OF THE MARK',choice:'east',explain:'An East Cardinal tells you the best navigable water is to the east. Think of the clock face: east is 3 o’clock.',flash:'White VQ(3) every 5 seconds or Q(3) every 10 seconds. Count THREE.'},
 south:{day:'Yellow above black. Two black cones, both points downward.',pass:'PASS SOUTH OF THE MARK',choice:'south',explain:'A South Cardinal tells you the best navigable water is to the south. Six on the clock face is followed by a long flash to distinguish it clearly.',flash:'White VQ(6) + long flash every 10 seconds, or Q(6) + long flash every 15 seconds. Count SIX, then ONE LONG.'},
 west:{day:'Yellow with one broad black band. Two black cones point-to-point.',pass:'PASS WEST OF THE MARK',choice:'west',explain:'A West Cardinal tells you the best navigable water is to the west. Think of 9 o’clock.',flash:'White VQ(9) every 10 seconds or Q(9) every 15 seconds. Count NINE.'},
 isolated:{day:'Black with one or more broad red horizontal bands. Two black spheres.',pass:'NO FIXED SIDE • PASS AT THE SAFE DISTANCE SHOWN BY CHART / PUBLICATION',choice:'either',explain:'The mark is on or near an isolated danger with navigable water around it. The buoyage system does not give one universal passing side or distance.',flash:'White group flashing two. Count TWO flashes.'},
 safe:{day:'Red and white vertical stripes. Single red spherical topmark where fitted.',pass:'SAFE WATER ALL AROUND • NO FIXED SIDE',choice:'either',explain:'A Safe Water Mark does not mark a danger. It may identify a centreline, fairway, mid-channel, entrance, approach or landfall.',flash:'White light: isophase, occulting, one long flash every 10 seconds, or Morse A. Project Watch shows one permitted representative characteristic.'},
 special:{day:'Yellow. Yellow X topmark where fitted.',pass:'NO GENERIC PASSING SIDE • CHECK THE CHART',choice:'chart',explain:'A Special Mark identifies a special area or feature. Its meaning comes from the chart or nautical publication, so do not invent a passing side from the colour alone.',flash:'Yellow light when fitted, using a rhythm not reserved for another mark.'},
 wreck:{day:'Equal blue and yellow vertical stripes. Upright yellow cross topmark.',pass:'NEW DANGER • KEEP CLEAR AS DIRECTED BY CHART / WARNINGS',choice:'chart',explain:'The Emergency Wreck Marking Buoy is a temporary mark for a new wreck or newly discovered danger while information is being promulgated and other marking is established.',flash:'Alternating blue and yellow light: 1 second blue, 0.5 second eclipse, 1 second yellow, 0.5 second eclipse.'}
};
window.PW_ORIGINAL_LIBRARIES.BUOY_ORDER=['port','starboard','prefStbd','prefPort','north','east','south','west','isolated','safe','special','wreck'];
window.PW_ORIGINAL_LIBRARIES.BUOY_DATA=[
 {id:'port',name:'Port-hand lateral',family:'Lateral • Region A',body:'red',top:'can',light:'Red; any rhythm except the reserved composite group (2+1)',meaning:'Marks the port-hand side of a channel or fairway when proceeding in the conventional direction of buoyage.',source:'IALA R1001 §2.1.3',lamp:'red',pattern:[[0,.55]],period:4,patternLabel:'Representative Fl R 4s training rhythm'},
 {id:'starboard',name:'Starboard-hand lateral',family:'Lateral • Region A',body:'green',top:'coneUp',light:'Green; any rhythm except the reserved composite group (2+1)',meaning:'Marks the starboard-hand side of a channel or fairway when proceeding in the conventional direction of buoyage.',source:'IALA R1001 §2.1.3',lamp:'green',pattern:[[0,.55]],period:4,patternLabel:'Representative Fl G 4s training rhythm'},
 {id:'prefStbd',name:'Preferred channel to starboard',family:'Modified lateral • Region A',body:'redGreenRed',top:'canRed',light:'Red; composite group flashing (2+1)',meaning:'At a channel division, the preferred channel is to starboard when proceeding in the conventional direction of buoyage.',source:'IALA R1001 §2.1.5',lamp:'red',pattern:[[0,.35],[.75,1.10],[2.0,2.35]],period:4,patternLabel:'Fl(2+1) R'},
 {id:'prefPort',name:'Preferred channel to port',family:'Modified lateral • Region A',body:'greenRedGreen',top:'coneGreen',light:'Green; composite group flashing (2+1)',meaning:'At a channel division, the preferred channel is to port when proceeding in the conventional direction of buoyage.',source:'IALA R1001 §2.1.5',lamp:'green',pattern:[[0,.35],[.75,1.10],[2.0,2.35]],period:4,patternLabel:'Fl(2+1) G'},
 {id:'north',name:'North Cardinal',family:'Cardinal',body:'blackYellow',top:'conesUp',light:'White: VQ or Q',meaning:'Safe water lies to the north of the mark.',source:'IALA R1001 §2.2',lamp:'white',pattern:[[0,.25]],period:.5,patternLabel:'VQ (continuous very quick training rhythm)'},
 {id:'east',name:'East Cardinal',family:'Cardinal',body:'blackYellowBlack',top:'conesBase',light:'White: VQ(3)5s or Q(3)10s',meaning:'Safe water lies to the east of the mark.',source:'IALA R1001 §2.2',lamp:'white',pattern:[[0,.25],[.50,.75],[1.00,1.25]],period:5,patternLabel:'VQ(3) 5s'},
 {id:'south',name:'South Cardinal',family:'Cardinal',body:'yellowBlack',top:'conesDown',light:'White: VQ(6)+LFl 10s or Q(6)+LFl 15s',meaning:'Safe water lies to the south of the mark.',source:'IALA R1001 §2.2',lamp:'white',pattern:[[0,.25],[.50,.75],[1.00,1.25],[1.50,1.75],[2.00,2.25],[2.50,2.75],[3.25,5.25]],period:10,patternLabel:'VQ(6)+LFl 10s'},
 {id:'west',name:'West Cardinal',family:'Cardinal',body:'yellowBlackYellow',top:'conesPoint',light:'White: VQ(9)10s or Q(9)15s',meaning:'Safe water lies to the west of the mark.',source:'IALA R1001 §2.2',lamp:'white',pattern:[[0,.25],[.50,.75],[1.00,1.25],[1.50,1.75],[2.00,2.25],[2.50,2.75],[3.00,3.25],[3.50,3.75],[4.00,4.25]],period:10,patternLabel:'VQ(9) 10s'},
 {id:'isolated',name:'Isolated Danger',family:'General mark',body:'blackRedBlack',top:'twoBalls',light:'White: Fl(2)',meaning:'The mark is on or near an isolated danger with navigable water all around. Consult the chart for safe passing distance.',source:'IALA R1001 §2.3',lamp:'white',pattern:[[0,.45],[1.0,1.45]],period:5,patternLabel:'Fl(2) W'},
 {id:'safe',name:'Safe Water',family:'General mark',body:'redWhiteVertical',top:'redBall',light:'White: Iso, Oc, LFl 10s or Mo(A)',meaning:'Navigable water exists all around the mark; used for centreline, mid-channel, entrance, approach or landfall purposes.',source:'IALA R1001 §2.4',lamp:'white',pattern:[[0,2.0]],period:4,patternLabel:'Iso W (representative permitted characteristic)'},
 {id:'special',name:'Special Mark',family:'General mark',body:'yellow',top:'xYellow',light:'Yellow; rhythm not reserved for another mark',meaning:'Marks a special area or feature whose nature is identified from the chart or nautical publication.',source:'IALA R1001 §2.5',lamp:'yellow',pattern:[[0,.55]],period:4,patternLabel:'Representative Fl Y 4s training rhythm'},
 {id:'wreck',name:'Emergency Wreck Mark',family:'New danger',body:'blueYellowVertical',top:'crossYellow',light:'Alternating blue and yellow: 1 s blue, 0.5 s eclipse, 1 s yellow, 0.5 s eclipse',meaning:'Used to mark a new wreck or newly discovered danger while information is being promulgated and other marking is established.',source:'IALA R1001 new-danger provisions',lamp:'alternate',pattern:[[0,1,'blue'],[1.5,2.5,'yellow']],period:3,patternLabel:'Al.BuY 3s'}
];
