/* Original independent recreational navigation content. Charts and questions remain separate from the engine. */
window.PW_CHARTWORK = Object.freeze({
version:'1.96.0',
chart:{id:'PW-CW01',west:-4-20/60,east:-4,south:50,north:50+10/60,panel:{x:75,y:145,width:1210,height:942.849},width:1600,height:1200},
beginner:[
{title:'A chart answers three questions',art:'overview',lead:'Where am I? What is around me? Where can I safely go?',plain:'A nautical chart shows land, water depths, hazards and navigation marks. We will use the same fictional bay throughout, so the places become familiar before the calculations begin.',remember:'Start by reading the chart, not by drawing a line.'},
{title:'A position is an address on the water',art:'position',lead:'Latitude and longitude tell you where the two chart lines meet.',plain:'Latitude tells us how far north or south; longitude tells us how far east or west. P is 50°04.000′ N, 004°10.000′ W. Find 04′ on the side and 10′ on the bottom, then follow them to the intersection.',remember:'Latitude from the side; longitude from the top or bottom.'},
{title:'Measure the journey',art:'distance',lead:'A knot is one nautical mile per hour.',plain:'The line from P to Q is 3 nautical miles. With no current, 6 knots takes half an hour to cover it. On this Mercator chart, measure distance against the latitude scale near the position, never the longitude scale.',remember:'Distance = speed × time in hours.'},
{title:'Know which kind of position you have',art:'ep',lead:'A fix is observed. Dead reckoning and estimated position are calculated.',plain:'A fix uses observations such as visual bearings or a checked GPS reading. Dead reckoning advances the last fix using direction and distance through the water. An estimated position adds the movement caused by current and, when relevant, leeway.',remember:'Write the time and say how you obtained the position.'}
],
lessons:[
{id:'cw01',title:'Read the chart before plotting',art:'overview',subtitle:'Scale, depths, symbols and reliability',lead:'Choose a chart with enough detail for the job. First read its title, scale, units, datum, edition, corrections and notes.',points:[['Scale matters','A larger-scale chart such as 1:10,000 shows a smaller area in more detail than 1:100,000. Enlarging a small-scale image does not add survey detail.'],['Read the water','Soundings are charted depths; contours join equal depths. Rocks, wrecks and drying areas need careful interpretation using the chart legend and an appropriate symbol reference. Colour alone is not a safe-depth test.'],['Check its limits','Position datum and vertical chart datum are different. Check source information, survey quality, notes and updates. Our original chart has invented depths and geography and is only for training.']],scenario:'On Alder Bank the charted depth is 4.6 m. A fictional tide height of 1.8 m gives 6.4 m water depth. With 1.6 m draught, static clearance is 4.8 m before allowances for waves, squat, uncertainty and a chosen safety margin.',takeaway:'A chart is evidence with limits. Use current, suitable-scale chart information for navigation.'},
{id:'cw02',title:'Read and plot latitude and longitude',art:'position',subtitle:'Degrees, minutes and hemispheres',lead:'Read latitude first, then longitude. Check both the number format and N/S/E/W.',points:[['Read the sides','Latitude increases northwards on this chart. P lies on 50°04.000′ N. One degree contains 60 minutes, and a minute can be divided into decimal fractions.'],['Read the top or bottom','Longitude is 004°10.000′ W. West minutes get smaller as you move east. Extend the longitude line vertically and the latitude line horizontally on a north-up Mercator chart.'],['Formats are different','50°04.000′ N equals 50.066667° N and 50°04′00″ N. Decimal degrees are not degrees and decimal minutes. A west longitude is negative when written as signed decimal degrees.']],scenario:'A GPS shows 50.066667, −4.166667 in decimal degrees. Convert to approximately 50°04.000′ N, 004°10.000′ W before using the border scales.',takeaway:'Keep the format, datum and hemispheres with the coordinates.'},
{id:'cw03',title:'Measure distance and time',art:'distance',subtitle:'Dividers and the latitude scale',lead:'On a Mercator chart, take the distance with dividers and transfer it to the latitude scale close to the measured line.',points:[['Distance','One minute of latitude is approximately one nautical mile. Longitude minutes are narrower at this latitude and are not a nautical-mile distance scale.'],['Speed and time','Distance in NM = speed in knots × time in hours. Thirty minutes is 0.5 hours. Time in minutes = distance ÷ speed × 60.'],['Use the right speed','Speed through water belongs in a through-water dead-reckoning calculation. Speed over ground belongs in a ground-distance calculation. Tide can change the arrival time.']],scenario:'P to Q is 3.0 NM. At a constant ground speed of 6 kn, the leg takes 30 minutes. At 4 kn over ground, it takes 45 minutes.',takeaway:'Say whether your speed and distance are through water or over ground.'},
{id:'cw04',title:'Plot a course on the chart',art:'course',subtitle:'True direction and chart tools',lead:'A plotted line gives a direction over the chart. It does not automatically give the compass heading to steer.',points:[['Draw the leg','Identify the start and destination accurately, draw the intended track and inspect the whole corridor for hazards. A direct line may be unsafe.'],['Measure from true north','Use a plotter or parallel rules to measure clockwise from true north. P to Q is 090° T, due east. Label the direction and distance.'],['Convert in separate steps','Allow for stream and leeway when shaping the course, then convert true to magnetic to compass using current variation and the boat’s applicable deviation. The compass pathway teaches those corrections.']],scenario:'A chart leg measures 090° T. Before steering, ask what current will do, whether leeway matters, and which compass corrections apply. Do not simply steer 090° C.',takeaway:'Planned track, through-water course and compass heading are different quantities.'},
{id:'cw05',title:'Fix your position with two bearings',art:'fix',subtitle:'Observe, convert, plot, cross-check',lead:'A bearing to an identified charted object gives a line on which your boat lies. A second suitable bearing gives a crossing.',points:[['Observe and identify','Choose clearly identified fixed landmarks with a useful angle between them. Take the bearings close together in time and record time and instrument reference. Avoid nearly parallel lines.'],['Plot the lines','Convert compass observations to true bearings as necessary. From each landmark draw the reciprocal direction back towards the observer. A bearing of 000° T to A gives a southward line from A.'],['Interpret the crossing','A bears 000° T and B bears 090° T in this ideal example. Their lines meet at P. Real bearing error, vessel movement and wrong identification can make the result unreliable.']],scenario:'Plot from Alder Light south on 180° T, and from East Light west on 270° T. The two lines meet at 50°04.000′ N, 004°10.000′ W.',takeaway:'The bearing is from your boat to the object; the plot from the object uses the reciprocal.'},
{id:'cw06',title:'Use a third line and judge the uncertainty',art:'three',subtitle:'Fix quality, cocked hats and other observations',lead:'A third independent observation checks the first two. Real position lines rarely meet perfectly.',points:[['Third bearing','A third identified landmark provides another line. Our chart shows an idealised common intersection; actual observations may form a small triangle called a cocked hat.'],['Do not trust the centre blindly','A triangle is not a guarantee that the boat is inside it. Wrong identification or systematic error can put every line in the wrong place. Check the observations and allow clearance from danger.'],['Other methods','A transit gives a position line through two objects seen in line. A radar range gives a distance circle around an identified fixed target. A bearing and range can form a fix. An echo-sounder depth is a check, not normally a unique position.']],scenario:'Your plotted fix is near a shoal but the coast looks wrong. Reduce exposure to danger, check landmark identity, bearing reference and time, and take another independent observation.',takeaway:'The quality of the observations matters more than the neatness of the crossing.'},
{id:'cw07',title:'Dead reckoning: advance the last fix',art:'dr',subtitle:'Direction and distance through the water',lead:'Dead reckoning, or DR, calculates a new position from a known starting position, course and distance through the water, before adding current.',points:[['Start with a timed fix','P is the 10:00 fix. Convert steering information to a usable true reference. For this first example, leeway is zero and the through-water course is 090° T.'],['Calculate the run','6 kn × 30/60 h = 3.0 NM. Plot 3.0 NM east from P and mark it DR 10:30. In a real log, plot at changes of course or speed as well as at suitable intervals.'],['Remember what is missing','DR is a calculated position, not a new observation. Steering errors, speed errors and unmodelled movement accumulate. Obtain another fix rather than allowing the uncertainty to grow unchecked.']],scenario:'DR 10:30 is approximately 50°04.000′ N, 004°05.326′ W. It has not yet been moved by the current.',takeaway:'DR answers where the boat would be from the through-water run alone.'},
{id:'cw08',title:'Estimated position: add the stream',art:'ep',subtitle:'Set, rate and leeway',lead:'Estimated position, or EP, includes estimated environmental movement. Add vectors over the same elapsed time.',points:[['Name the stream correctly','Set is the direction towards which the current flows. A stream setting 000° T flows north. At 2 kn for 30 minutes, it carries the boat 1.0 NM.'],['Move the DR','From DR 10:30 draw 1.0 NM north, using the same 30-minute period. Mark the result EP 10:30. Do not use a full hour of tide for a half-hour run.'],['Add other effects carefully','Include a justified leeway allowance in the through-water direction when relevant. Avoid double-counting it. Streams and wind vary; an EP remains an estimate, so seek a fresh observed fix.']],scenario:'In this short-leg exercise, EP 10:30 is approximately 50°05.000′ N, 004°05.326′ W. The 1.0 NM northward displacement is the modelled stream, not a measurement of actual current.',takeaway:'Fix + through-water movement + estimated environmental movement = EP.'},
{id:'cw09',title:'Shape a course to counter the stream',art:'cts',subtitle:'An introduction to the course-to-steer triangle',lead:'To keep an intended eastward ground track when the stream sets north, the boat must move partly south through the water.',points:[['Work in one reference','For this exercise the desired track is 090° T, speed through water is 6 kn, and the stream is 2 kn towards 000° T. Assume constant stream and no leeway.'],['Balance the sideways movement','The southward component of the boat’s movement must cancel 2 kn north. The true course to steer is about 109.5° T, and resulting ground speed is about 5.66 kn east.'],['Finish the practical job','Convert true course to magnetic and compass separately. Check the chart corridor, wind, tide changes and your observed track. A calculated course is a starting estimate, not an instruction to ignore what you see.']],scenario:'Over 30 minutes the boat moves about 2.83 NM east and 1.0 NM south through water. The stream adds 1.0 NM north, leaving about 2.83 NM east over ground.',takeaway:'Aim into the sideways current and verify the ground track.'},
{id:'cw10',title:'Use GPS without surrendering the navigation',art:'gps',subtitle:'Position, datum, COG, SOG and independent checks',lead:'GPS is one satellite constellation within GNSS. A receiver supplies a position; the chart and navigator give that position meaning.',points:[['Transfer it correctly','Check the fix status, timestamp, coordinate format and chart datum. Modern charts commonly use WGS 84, but verify yours. Extra decimal places do not prove equal accuracy.'],['Read the right direction','COG is movement over the ground; SOG is speed over the ground. COG is not bow heading and may become unreliable at very low speed. A heading sensor is a separate input.'],['Cross-check independently','Compare with identified visual objects, radar where fitted and suitable, and depth with tide accounted for. Two displays sharing one receiver are not independent. Power loss, stale data, interference, jamming or spoofing can mislead you.']],scenario:'The GPS dot shows open water but a correctly identified transit and depth disagree. Treat the discrepancy as a navigation problem immediately; do not follow the dot into possible danger.',takeaway:'A convincing screen does not remove the need for a lookout and independent position checks.'},
{id:'cw11',title:'Bring chart work into harbour pilotage',art:'pilotage',subtitle:'Depth, marks and a simple entry plan',lead:'As you approach the coast, switch from broad passage navigation to detailed pilotage. Use the largest suitable chart and local information.',points:[['Plan the entry','Write a short sequence of recognisable features, directions, distances and depth checks. Include local rules, weather, tide, traffic, an abort point and somewhere safe to wait.'],['Understand the marks','Our training harbour uses IALA Region A: entering from seaward, red port-hand marks lie to port and green starboard-hand marks to starboard. Check the local direction of buoyage; lateral marks are not a complete pilotage plan.'],['Keep the crew involved','Brief the lookout, helm and navigator. Keep a safe speed, monitor depth and confirm each feature. Do not let chart work pull attention away from collision avoidance or the water ahead.']],scenario:'Identify both entry lights before committing to the harbour. If the expected marks or depths do not match, stay clear of danger and reassess rather than pressing on.',takeaway:'A safe entry uses the chart, the conditions and what the crew actually observes.'},
{id:'cw12',title:'Record, check and navigate when a screen fails',art:'overview',subtitle:'A practical navigation routine',lead:'Keep a clear record so the next position can be checked and the plan can survive a lost screen or uncertain fix.',points:[['Record enough to reconstruct it','Write position, time, source of fix, course reference, speed basis and significant changes. Label fix, DR and EP distinctly. Use a consistent time reference and record any change.'],['Match the checking interval to risk','Fix more often near hazards, at higher speed, in restricted visibility, or when information disagrees. There is no universal safe interval for every boat and location.'],['Have an independent alternative','Plan how to confirm position and reach safety if the primary equipment fails. It may be paper chart work, independent electronics or other suitable methods; make sure the alternative really works without the failed source or power supply.']],scenario:'Your chartplotter loses power. Use the last timed fix and log to start DR/EP, seek visual or other independent observations, maintain a lookout and act conservatively while position confidence is reduced.',takeaway:'Keep the basic navigation working before relying on extra features.'}
],
practice:[
{title:'Plot a position',prompt:'On the chart, place a fix at 50°04.000′ N, 004°10.000′ W. Use the border scales. Tap or click once, or enter the coordinates below.',target:[50+4/60,-4-10/60]},
{title:'Build a dead-reckoning run',prompt:'From P at 10:00, run 090° T at 6 kn through water for 30 minutes. Use no stream and no leeway. Calculate first, then reveal the chart.',answer:'The through-water run is 3.0 NM east. DR 10:30 is approximately 50°04.000′ N, 004°05.326′ W.'},
{title:'Add the tidal stream',prompt:'Use the same run, but add a stream setting 000° T at 2 kn for the same 30 minutes. What changes?',answer:'Add 1.0 NM north from the DR. EP 10:30 is approximately 50°05.000′ N, 004°05.326′ W.'},
{title:'Cross-check a GPS position',prompt:'The GPS says 50°04.000′ N, 004°10.000′ W. Which checks offer independent evidence?',choices:['Read a second display connected to the same GPS receiver.','Identify Alder Light due north and East Light due east using checked true bearings.','Zoom in until the position icon looks precise.'],correct:1,answer:'The visual observations provide a different source of evidence. Two screens sharing a receiver can share the same error; zooming adds no positional certainty.'}
],
quiz:[
['Which chart offers more detail for a harbour entry?',['1:10,000, if current and suitable for the area','1:100,000 because its number is larger','Either chart gains new detail when enlarged'],0,'A larger-scale chart has a smaller scale denominator and normally shows more local detail.'],
['Where do you measure distance on this Mercator chart?',['The longitude scale','The latitude scale near the measured line','The screen width in centimetres'],1,'One minute of latitude is approximately one nautical mile.'],
['How long is 3 NM at a constant 6 kn over ground?',['30 minutes','18 minutes','60 minutes'],0,'Time = 3 ÷ 6 hours = 0.5 hours.'],
['The charted depth is 4.6 m and tide height is 1.8 m. What is water depth in the example?',['2.8 m','4.6 m','6.4 m'],2,'Add height above chart datum to charted depth, before clearance and uncertainty allowances.'],
['A point is at 004°10′ W. Moving east makes its west minutes…',['larger','smaller, until reaching zero at Greenwich','stay fixed'],1,'Eastward movement approaches zero west longitude.'],
['50.066667° N is approximately…',['50°06.667′ N','50°04.000′ N','50°00.667′ N'],1,'Multiply the fractional degree by 60 to obtain minutes.'],
['A lighthouse bears 045° T from the boat. Which reciprocal direction runs from the lighthouse back towards the boat?',['225° T','045° T','135° T'],0,'Add 180° and wrap within a full circle.'],
['Which pair of position lines normally gives a better-defined crossing?',['Two almost parallel bearings','One bearing taken twice without accounting for movement','Two well-separated, correctly identified bearings taken close together in time'],2,'A useful crossing angle improves geometry, but observation accuracy and timing still matter.'],
['Is the boat guaranteed to be inside a three-bearing cocked hat?',['Yes','No; systematic errors or misidentification can put it outside','Only if the triangle is drawn neatly'],1,'Investigate the observations and allow for uncertainty, especially near danger.'],
['A transit is…',['two identified objects seen in line, providing a position line','a GPS waypoint','a line joining two different tide times'],0,'An identified transit is useful independent positional evidence.'],
['For a through-water DR run, which speed is appropriate?',['GPS SOG without checking the distinction','speed through water','the boat’s maximum advertised speed'],1,'Match the speed basis to the run being plotted.'],
['6 kn through water for 30 minutes gives…',['6 NM','12 NM','3 NM'],2,'Thirty minutes equals 0.5 hours.'],
['A current setting 000° T flows…',['towards north','from north towards south','towards east'],0,'Set is the direction towards which the current moves.'],
['A 2 kn stream over 30 minutes displaces the boat by…',['2 NM','1 NM','0.5 NM'],1,'Use the same elapsed time as the vessel run: 2 × 0.5 = 1 NM.'],
['How does EP differ from the basic DR example?',['It adds estimated environmental movement','It is always an observed fix','It removes the need to take another fix'],0,'Adding stream and relevant leeway does not make the result an observation.'],
['To make an eastward track against a north-setting stream, you need a through-water direction with…',['a northward component','a southward component','no sideways component'],1,'The southward component counters the stream; calculate the amount and verify the result.'],
['At very low boat speed, GPS COG…',['always gives accurate bow heading','may be unstable and is not a substitute for heading','is the compass deviation'],1,'COG describes movement over ground, not the direction the bow points.'],
['Which is an independent check of a GPS position?',['Another screen sharing the same receiver','The precision of its decimal places','A visual fix from correctly identified landmarks'],2,'A separate observation source can reveal a shared electronic error.'],
['What should you do when the GPS position disagrees with reliable visual evidence?',['Investigate immediately and keep clear of danger','Follow the GPS because electronics cannot be wrong','Ignore the view and enlarge the screen'],0,'Treat contradictions as a navigation problem and use other available evidence.'],
['In our Region A harbour, entering from seaward, the port-hand mark is…',['green and conical','red, on the vessel’s port side','a direction to pass every red object to starboard'],1,'Check the direction of buoyage and local information.'],
['How often should a navigator obtain fixes?',['Exactly every hour everywhere','Only after the plotter fails','Often enough for speed, hazards, visibility and confidence in the information'],2,'The interval must suit the risk rather than an arbitrary fixed rule.']
],
sources:[
['RYA Day Skipper Theory: chartwork, electronic charts and position fixing','https://www.rya.org.uk/course-finder/day-skipper-theory-course/'],
['RYA: electronic navigation and independent backups','https://www.rya.org.uk/water-safety/passage-planning-and-navigation/electronic-navigation-aids/'],
['RYA navigation terminology','https://www.rya.org.uk/media/00wbqkjm/da7_mut466820030837430044.pdf'],
['RYA ICC guidance: chart symbols, three-bearing fixes and course shaping','https://www.rya.org.uk/media/vtonfddu/tg10-14_icc_test_centres_guidance_revised_may2021.pdf'],
['MCA MGN 379: limitations and independent checking of electronic navigation','https://www.gov.uk/government/publications/mgn-379-mf-amendment-1-use-of-electronic-navigational-aids/mgn-379-mf-amendment-1-use-of-electronic-navigational-aids'],
['NGA American Practical Navigator: plotting, DR and current vectors','https://msi.nga.mil/Publications/APN'],
['NOAA Chart No. 1: chart symbol reference (check regional differences)','https://nauticalcharts.noaa.gov/publications/us-chart-1.html'],
['UKHO: continuing ADMIRALTY paper-chart production, February 2026','https://www.admiralty.co.uk/news/sustaining-the-future-of-ADMIRALTY-standard-nautical-charts'],
['UKHO chart reproduction and licensing','https://copyright.ukho.gov.uk/']
]
});
