/* Project Watch content library; copied without editing questions or answer indexes. */
window.PW_ORIGINAL_LIBRARIES = window.PW_ORIGINAL_LIBRARIES || {};
window.PW_ORIGINAL_LIBRARIES.STAGE5_FINAL = [
 ['If there is doubt whether risk of collision exists, what should you assume?',['There is no risk until CPA is below 0.5 NM','Risk of collision exists','Only the faster vessel has risk','Wait for a sound signal'],1,'Rule 7 requires doubt to be resolved on the safe side: risk is deemed to exist.'],
 ['Under Rule 8, a good avoiding alteration should normally be…',['A series of small changes','Large enough to be readily apparent','Delayed until close quarters','Course-only in every case'],1,'If circumstances admit, the alteration should be large enough to be readily apparent; repeated small changes should be avoided.'],
 ['You are overtaking another vessel. When does your Rule 13 duty end?',['When you reach its beam','When its bearing changes','When you are finally past and clear','As soon as you sound an overtaking signal'],2,'The overtaking vessel remains responsible until finally past and clear.'],
 ['Two power-driven vessels are meeting head-on with risk of collision. What should each normally do?',['Alter to port','Alter to starboard','The larger vessel stands on','Both stop immediately'],1,'Rule 14 requires each power-driven vessel to alter course to starboard so they pass port-to-port.'],
 ['In a power-driven crossing situation, another power-driven vessel is on your starboard side. Your vessel is normally…',['Stand-on','Give-way','Overtaking','Not required to act'],1,'Under Rule 15, the vessel that has the other on her starboard side keeps out of the way.'],
 ['You are the stand-on vessel and it becomes apparent the give-way vessel is not taking appropriate action. Rule 17 says you…',['Must never manoeuvre','May take action by your manoeuvre alone','Must immediately alter to port','Lose all COLREG responsibility'],1,'Rule 17(a)(ii) permits the stand-on vessel to act when the give-way vessel is evidently not taking appropriate action.'],
 ['Two sailing vessels have wind on different sides. Which vessel gives way?',['The vessel on starboard tack','The vessel with wind on the port side','The leeward vessel','The larger vessel'],1,'Rule 12: with wind on different sides, the vessel with wind on the port side keeps out of the way.'],
 ['Two sailing vessels have wind on the same side. Which gives way?',['The leeward vessel','The windward vessel','The vessel on starboard tack regardless','Neither'],1,'When both have wind on the same side, the windward vessel keeps out of the way.'],
 ['A yacht has sails set but is also being propelled by its engine. For steering and sailing responsibilities it is…',['Always a sailing vessel','A power-driven vessel','NUC','RAM'],1,'A vessel propelled by machinery is treated as power-driven; sails being set do not preserve sailing-vessel privilege.'],
 ['You detect another vessel by radar in fog but cannot see it. Which rule principally governs the encounter?',['Rule 15 crossing','Rule 17 stand-on','Rule 19 restricted visibility','Rule 34 only'],2,'When vessels are not in sight of one another in or near restricted visibility, Rule 19 applies rather than the normal in-sight encounter rules.']
];
window.PW_ORIGINAL_LIBRARIES.STAGE7_FINAL = [
 ['Rule 10 applies to IMO-adopted traffic separation schemes. Does it remove your obligations under the other COLREGs?',['Yes','No — the other applicable Rules still apply','Only for vessels under 20 m'],1,'Rule 10(a) expressly does not relieve a vessel of obligations under any other Rule.'],
 ['If you are using a traffic lane, how should you proceed?',['In the appropriate lane in the general direction of traffic flow','Against the arrows if traffic is light','Along the separation line'],0,'Rule 10(b) requires use of the appropriate lane in the general direction of traffic flow.'],
 ['If you are obliged to cross a traffic lane, what heading should you use?',['As nearly as practicable at right angles to the general direction of traffic flow','A shallow diagonal to reduce speed over ground','Parallel to the traffic flow'],0,'Rule 10(c) calls for a crossing heading as nearly as practicable at right angles to the traffic flow.'],
 ['A strong tide sets your track sideways during a TSS crossing. Which is the key Rule 10(c) geometry?',['Your heading remains as nearly as practicable at right angles to traffic flow','Your COG must always be exactly 90 degrees','Your wake must point at the far buoy'],0,'MCA guidance distinguishes heading from track/COG: tidal set may skew the ground track.'],
 ['When joining a traffic lane from the side, what is the correct approach?',['Join at as small an angle to traffic flow as practicable','Join at 90 degrees','Stop in the separation zone first'],0,'Rule 10(b)(iii) uses different geometry for joining/leaving than for crossing.'],
 ['What should a vessel normally do regarding a separation line or separation zone?',['Keep clear so far as practicable','Use it as waiting space','Navigate along its centre'],0,'The separation feature is not spare sea room or a normal waiting area.'],
 ['Watch One is under 20 m. What Rule 10(j) duty applies regarding a power-driven vessel following a traffic lane?',['Do not impede its safe passage','Claim priority because Watch One is smaller','Always enter the inshore traffic zone'],0,'A vessel under 20 m shall not impede the safe passage of a power-driven vessel following a traffic lane.'],
 ['A fishing vessel operating near a TSS must not do what?',['Impede the passage of a vessel following a traffic lane','Show fishing lights','Use radar'],0,'Rule 10(i) specifically prohibits a fishing vessel from impeding a vessel following a traffic lane.'],
 ['If your voyage is not using the TSS, what does Rule 10 say?',['Avoid it by as wide a margin as practicable','Cross it repeatedly to shorten the route','Follow the separation line'],0,'Rule 10(h) says a vessel not using a TSS shall avoid it by as wide a margin as practicable.'],
 ['You have the correct right-angle crossing heading, but the developing traffic picture is unsafe. What should you do?',['Remain clear and reassess — correct geometry does not replace collision-risk assessment','Commit because 90 degrees gives priority','Stop in the separation zone'],0,'Rule 10 works with lookout, risk assessment and avoiding-action duties. Geometry alone never makes an unsafe crossing safe.']
];
