/* Project Watch content library; values preserved from the approved build. */
window.PW_ORIGINAL_LIBRARIES = window.PW_ORIGINAL_LIBRARIES || {};
window.PW_ORIGINAL_LIBRARIES.LS_LESSONS = [
 {title:'How Project Watch reads lights & shapes',sub:'Four visual ideas — four matching explanations',intro:'Start with four things you can actually see in the approved visual cards. Extra marine words are explained later, at the point where you first need them.',facts:[
 ['Masthead light','White. A forward-facing navigation light fitted on the vessel’s centreline.'],
 ['Sidelights','Red is port and green is starboard. Which one or ones you can see depends on your viewing aspect.'],
 ['Ball','A black round day shape. It is used alone or in prescribed combinations to show particular vessel conditions.'],
 ['Cone — apex down','A black cone with the pointed end facing downward. “Apex” simply means the pointed tip of the cone.']
 ],visual:'intro'},
 {title:'Ordinary power-driven vessel lights',sub:'First recognise the basic navigation lights',intro:'Start with an ordinary power-driven vessel underway. Where you are looking from — the viewing aspect — changes which lights are visible.',facts:[
 ['Masthead light','A white light on the vessel’s centreline. It shines from right ahead to 22.5° abaft the beam on either side. “Abaft” means behind; the beam is the vessel’s widest point across the middle.'],
 ['Port sidelight','Red. It is fitted on the vessel’s port, or left, side when looking forward from onboard.'],
 ['Starboard sidelight','Green. It is fitted on the vessel’s starboard, or right, side when looking forward from onboard.'],
 ['Sternlight','White and directed around the after part of the vessel. From directly astern this is the key ordinary navigation light.'],
 ['Why the picture changes','A light can be fitted to the vessel but invisible to you because you are outside that light’s viewing sector.']
 ],visual:'vesselLights'},
 {title:'Viewing aspect changes the picture',sub:'Ahead, port side, starboard side and astern',intro:'Aspect means where YOU are looking at the other vessel from. The same vessel can therefore present a different light picture without changing what it is doing.',facts:[
 ['Ahead','Looking toward the bow. Both red and green sidelights can be visible together with the applicable masthead light or lights.'],
 ['Port-side aspect','You are looking at the vessel’s port side, so the red sidelight can be visible together with the applicable white light or lights.'],
 ['Starboard-side aspect','You are looking at the vessel’s starboard side, so the green sidelight can be visible together with the applicable white light or lights.'],
 ['Astern','You are looking toward the vessel’s stern. The white sternlight is the key ordinary navigation light directed toward you.']
 ],visual:'aspects'},
 {title:'Day shapes — learn the silhouettes',sub:'Ball, cone, diamond and cylinder',intro:'Day shapes are black shapes shown in daylight. Learn the silhouette, number, order and orientation. “Apex” simply means the pointed end of a cone.',facts:[
 ['Ball','A black round shape. One ball is the basic anchor day shape. Other vessel conditions use balls in combinations.'],
 ['Cone — apex up','A black cone with its pointed tip UP. The direction of the point matters.'],
 ['Cone — apex down','A black cone with its pointed tip DOWN. A sailing vessel also being propelled by machinery uses this day shape.'],
 ['Diamond','A black diamond shape. It appears in several prescribed combinations, including some towing and restricted-manoeuvrability displays.'],
 ['Cylinder','A tall black rectangular-looking shape. A vessel constrained by her draught may exhibit a cylinder.']
 ],visual:'dayShapes'},
 {title:'Special vessel-status patterns',sub:'Learn what the activity means as well as the colours',intro:'These all-round light patterns tell you about a vessel’s condition or work. Learn the plain-English meaning first, then the recognition pattern.',facts:[
 ['Not under command — red over red','The vessel cannot manoeuvre as required by the Rules because of an exceptional circumstance and therefore cannot keep out of another vessel’s way.'],
 ['Restricted in ability to manoeuvre — red • white • red','The nature of the vessel’s work restricts her ability to manoeuvre as required by the Rules.'],
 ['Trawling — green over white','Trawling is fishing by dragging a trawl net or other fishing apparatus through the water.'],
 ['Fishing other than trawling — red over white','Fishing with gear that restricts manoeuvrability, but not by trawling. This COLREG status does not mean every boat simply using a fishing rod.']
 ],visual:'statusVessels'},
 {title:'Anchor, aground, towing, pilot, dredging & mine clearance',sub:'Six different displays — six different meanings',intro:'Finish the teaching section with six separate vessel situations. Match each picture to its explanation before moving to the final check.',facts:[
 ['At anchor','A vessel secured by her anchor rather than underway. The basic day shape is one black ball; prescribed anchor lights depend on vessel length.'],
 ['Aground','A vessel whose hull is touching the ground. It adds the prescribed aground signals to the anchor display; by day the familiar signal is three black balls vertically.'],
 ['Towing astern','A vessel towing another vessel or object behind her. Towing has additional prescribed masthead/towing lights, and long tows require a diamond by day.'],
 ['Pilot vessel','A vessel engaged on pilotage duty. Its distinctive night identification is white over red; when underway, the required ordinary navigation lights are also shown.'],
 ['Dredging / underwater operations','A restricted-in-ability-to-manoeuvre operation. Two red lights or balls mark the obstructed side; two green lights or diamonds mark the side on which another vessel may pass.'],
 ['Mine clearance','A vessel engaged in mine-clearance operations shows three additional all-round green lights at night or three balls by day. The special display warns other vessels to keep well clear.']
 ],visual:'specialVessels'}
];
window.PW_ORIGINAL_LIBRARIES.COLLISION_TUTORIAL_LESSONS = [
 {id:'display',title:'Meet your bridge display',sub:'Own vessel, target, range and bearing',scenario:'cross_stbd',mode:'power',
  summary:'Learn what you are looking at before you touch any controls.',
  points:[['Own vessel','The white vessel symbol represents you. It starts in the centre of the simulator display.'],['Target','The red vessel symbol is the other vessel — the target.'],['Range','Distance to the target is shown in nautical miles.'],['Target sector','A plain-language position such as starboard bow or port bow.']],
  steps:[
   ['radarDisplay','At the start of every tutorial scenario, the white vessel in the centre of the display is your own vessel. The red vessel is the target.'],
   ['og','The white vessel starting in the centre is always your own vessel. In the power-driven lessons, that vessel represents the selected training vessel.'],
   ['tg','The red vessel is the target vessel. At the start, it is positioned around your own vessel according to the encounter being taught.'],
   ['rangeMetric','Range is the distance between you and the target. NM means nautical miles.'],
   ['sectorMetric','Target sector tells you where the vessel is relative to your bow: ahead, port, starboard, beam, quarter or astern.']
  ]},
 {id:'cpa',title:'CPA & TCPA',sub:'Understand collision risk',scenario:'cross_stbd',mode:'power',
  summary:'Learn the two numbers used constantly when assessing another vessel.',
  points:[['CPA','Closest Point of Approach: predicted minimum passing distance if courses and speeds remain unchanged.'],['TCPA','Time to CPA: how long until that closest point occurs.'],['Trend','A low CPA with positive TCPA deserves attention.'],['Reassess','CPA/TCPA change when either vessel manoeuvres.']],
  steps:[
   ['cpaMetric','CPA means Closest Point of Approach. It predicts the minimum passing distance if both vessels maintain their present courses and speeds.'],
   ['tcpaMetric','TCPA means Time to Closest Point of Approach. A positive value means that predicted closest point is still ahead in time.'],
   ['radarDisplay','Never use one number in isolation. Keep watching the target, the trend, the bearing and the developing situation.']
  ]},
 {id:'sides',title:'Port & starboard',sub:'Know which side the target is on',scenario:'cross_stbd',mode:'power',
  summary:'Build the basic language used throughout COLREG collision avoidance.',
  points:[['Port','Left side of the vessel when facing forward.'],['Starboard','Right side of the vessel when facing forward.'],['Bow','Front of the vessel.'],['Quarter','Rear side area, between beam and stern.']],
  steps:[
   ['sectorMetric','This encounter starts with the target on your STARBOARD side — the right-hand side of your own vessel when you are facing forward.'],
   ['radarDisplay','Port and starboard are always relative to your own vessel and its heading, not simply the left or right edge of the tablet.']
  ]},
 {id:'helm',title:'Using the helm',sub:'Order rudder and read the response',scenario:'cross_stbd',mode:'power',
  summary:'Learn the difference between ordered rudder, actual rudder and rate of turn.',
  points:[['Ordered rudder','What you ask the steering system to do.'],['Actual rudder','What the rudder has physically reached.'],['Rate of turn','How quickly the vessel heading is changing.'],['Midships','Returns the ordered rudder to zero.']],
  steps:[
   ['helmControlPanel','This is the helm control. Drag or tap the scale, use the 5° buttons, or press MIDSHIPS.'],
   ['rudderInstrument','The instrument above shows the ACTUAL rudder angle. It moves progressively toward your ordered rudder.'],
   ['helmControlPanel','Try ordering STARBOARD 5°. Then press MIDSHIPS. Watch the actual rudder follow the command.']
  ]},
 {id:'crossing',title:'Crossing situation',sub:'Rules 15–17',scenario:'cross_stbd',mode:'power',
  summary:'Recognise a power-driven crossing encounter and understand give-way / stand-on roles.',
  points:[['Rule 15','When two power-driven vessels are crossing so as to involve risk of collision, the vessel which has the other on her starboard side shall keep out of the way.'],['Rule 16','The give-way vessel should take early and substantial action to keep well clear.'],['Rule 17','The stand-on vessel initially keeps course and speed, while continuing to monitor.'],['Avoid ahead','Where circumstances admit, the give-way vessel should avoid crossing ahead.']],
  steps:[
   ['sectorMetric','In this lesson, two power-driven vessels are in sight of one another, crossing so as to involve risk of collision. The target is on your starboard side, so your own vessel is the give-way vessel under Rule 15.'],
   ['cpaMetric','Use CPA and TCPA as part of the assessment, but keep a proper lookout and use all available means to judge risk of collision.'],
   ['helmControlPanel','Under Rules 15 and 16, the give-way vessel must keep out of the way and take early and substantial action. Where circumstances admit, avoid crossing ahead of the vessel on your starboard side.']
  ]},
 {id:'headon',title:'Head-on situation',sub:'Rule 14',scenario:'head_on',mode:'power',
  summary:'Recognise reciprocal or nearly reciprocal courses.',
  points:[['Recognise','Two power-driven vessels meeting on reciprocal or nearly reciprocal courses.'],['Action','Each power-driven vessel shall alter course to starboard.'],['Passing','Each vessel passes on the port side of the other.'],['Monitor','Continue checking the other vessel is also acting.']],
  steps:[
   ['radarDisplay','Two power-driven vessels are meeting on reciprocal or nearly reciprocal courses so as to involve risk of collision. The target is essentially ahead.'],
   ['helmControlPanel','Under Rule 14, each vessel shall alter course to starboard so that each passes on the port side of the other.']
  ]},
 {id:'overtaking',title:'Overtaking',sub:'Rule 13',scenario:'overtake',mode:'power',
  summary:'Learn why the overtaking vessel carries the responsibility.',
  points:[['Overtaking vessel','A vessel coming up from more than 22.5° abaft the beam is overtaking.'],['Give-way','The overtaking vessel keeps out of the way.'],['Until clear','Responsibility continues until finally past and clear.'],['Doubt','If in doubt whether you are overtaking, assume that you are.']],
  steps:[
   ['radarDisplay','In this scenario, your own vessel is coming up from astern of the target in the Rule 13 overtaking sector — more than 22.5 degrees abaft the target vessel’s beam.'],
   ['sectorMetric','Under Rule 13, the overtaking vessel shall keep out of the way. A later change of bearing does not turn it into a crossing situation or remove that duty until finally past and clear.']
  ]},
 {id:'sail',title:'Power meets sail',sub:'Rule 18 basics',scenario:'power_vs_sail',mode:'power',
  summary:'Understand the normal power-versus-sail relationship — and that other rules can override it.',
  points:[['Rule 18','Except where Rules 9, 10 and 13 otherwise require, a power-driven vessel underway shall keep out of the way of a sailing vessel.'],['Not absolute','Overtaking, narrow channels, TSS and special vessel status can change the analysis.'],['Sailing means sailing','If propulsion machinery is being used, the vessel is treated as power-driven.'],['Look first','Always identify the actual situation before applying a simple hierarchy.']],
  steps:[
   ['radarDisplay','The target in this training encounter is a sailing vessel under sail, with propelling machinery not being used.'],
   ['sectorMetric','Under Rule 18, except where Rules 9, 10 and 13 otherwise require, a power-driven vessel underway shall keep out of the way of a sailing vessel. Always identify the actual situation before applying that hierarchy.']
  ]},
 {id:'firstwatch',title:'Your first coached watch',sub:'Put everything together',scenario:'cross_stbd',mode:'power',
  summary:'Run a complete collision encounter with beginner coaching and spoken warnings.',
  points:[['Observe','Identify target side, range, CPA and TCPA.'],['Decide','Work out whether you are give-way or stand-on.'],['Act','Make any avoiding action early and obvious enough to be understood.'],['Check','Keep monitoring until the vessels are past and clear.']],
  steps:[
   ['radarDisplay','This is your first complete coached watch. At the start, the white vessel in the centre is your own vessel and the red vessel is the target. Begin by identifying the target’s position and whether risk of collision is developing.'],
   ['sectorMetric','In this constructed power-driven crossing exercise, the target begins on your starboard side, so your own vessel is the give-way vessel under Rule 15.'],
   ['helmControlPanel','Use the helm and, if useful, engine controls. Watch how your decisions change CPA and the target geometry.'],
   ['alert','Guided mode gives visual and spoken warnings as the situation becomes close. Continue monitoring until the exercise ends.']
  ]}
];
window.PW_ORIGINAL_LIBRARIES.ORIENTATION_LESSONS = [
 {title:'How Project Watch teaches',sub:'Learn → practise → assess',intro:'Different parts of Project Watch have different purposes.',facts:[
  ['Learn','Teaching screens explain the subject before you are tested.'],
  ['Practise','Guided simulators let you apply it with coaching.'],
  ['Assess','Knowledge checks and mock exams test material after it has been taught. A wrong answer is feedback, not the end of the course.']]},
 {title:'Your own vessel',sub:'Start with what you command',intro:'Before interpreting other traffic, know the vessel from which you are observing it.',facts:[
  ['Own vessel','The vessel you are controlling is your own vessel. In Project Watch it uses the personal vessel profile, or Watch One as the default.'],
  ['Bow & stern','Bow means the front of the vessel. Stern means the rear.'],
  ['Port & starboard','Facing forward, port is your left side and starboard is your right side. These terms stay with the vessel, not the edge of the screen.']]},
 {title:'Direction around you',sub:'Bow, beam and quarter',intro:'Traffic is described relative to your vessel as well as by compass bearing.',facts:[
  ['Ahead / astern','Ahead is in front of the bow. Astern is behind the stern.'],
  ['Beam','The beam direction is approximately 90° to either side of the vessel.'],
  ['Quarter','The quarters are the rear-side sectors between the beam and stern.']]},
 {title:'Heading',sub:'Where the bow points',intro:'Heading tells you the direction the vessel’s bow is pointing.',facts:[
  ['Heading','A heading of 090° means the bow is pointing east.'],
  ['It can change','Turning the vessel changes heading.'],
  ['Not always your track','Wind, tide and current can mean the direction you move over the ground is different from heading.']]},
 {title:'COG & SOG',sub:'How you move over the ground',intro:'Electronic navigation commonly shows Course Over Ground and Speed Over Ground.',facts:[
  ['COG','Course Over Ground is the direction your vessel is actually moving across the Earth.'],
  ['SOG','Speed Over Ground is how fast the vessel is moving over the Earth.'],
  ['Compare with heading','Heading and COG can differ. That difference is useful information, not automatically an instrument error.']]},
 {title:'Lookout first',sub:'Rule 5 mindset',intro:'No screen replaces the basic duty to maintain a proper lookout.',facts:[
  ['Sight and hearing','Look outside and listen.'],
  ['All available means','Use radar, AIS and other appropriate aids when available, but as supporting information.'],
  ['Build the picture','Keep updating what vessels are doing; do not make one observation and stop watching.']]}
];
window.PW_ORIGINAL_LIBRARIES.SIG_LESSONS = [
 {title:'The language of sound',sub:'Rules 32–33',intro:'First learn the building blocks and which appliances vessels carry.',facts:[['Short blast','About one second.'],['Prolonged blast','Four to six seconds. Project Watch uses 4.5 seconds for training playback.'],['12 m or more','A whistle is required.'],['20 m or more','A bell is required in addition to a whistle.'],['100 m or more','A gong is required in addition to whistle and bell.'],['Under 12 m','If the prescribed appliances are not carried, some other means of making an efficient sound signal is required.']],play:['stbd','pdMakingWay']},
 {title:'Vessel status — plain English',sub:'Rule 3 + Rule 35(c)',intro:'Before learning the fog signal, learn the vessel-status words. The abbreviations describe why a vessel may have limits on how she can manoeuvre.',facts:[['NUC — Not Under Command','Something exceptional means the vessel cannot manoeuvre as the COLREGs require and therefore cannot keep out of another vessel’s way. Think: an abnormal problem has taken away normal manoeuvring ability.'],['RAM — Restricted in Ability to Manoeuvre','The nature of the vessel’s work restricts her ability to manoeuvre as the COLREGs require. Examples include dredging, surveying, underwater work, cable or pipeline work, replenishment underway and some towing operations. Think: the job she is doing limits her.'],['CBD — Constrained by Draught','A power-driven vessel whose draught, compared with the available depth of water, severely restricts her ability to deviate from the course she is following. Think: deep vessel + limited depth = very little room to move sideways.'],['Sailing vessel','Under the COLREG definition, a vessel under sail counts as a sailing vessel only when any fitted propelling machinery is not being used.'],['Engaged in fishing','This means fishing with gear such as nets, lines or trawls that restrict manoeuvrability. Ordinary trolling or gear that does not restrict manoeuvrability does not qualify.'],['Why this matters in fog','NUC, RAM, CBD, sailing, fishing, and a vessel towing or pushing use the Rule 35(c) restricted-visibility signal: one prolonged followed by two short, at intervals of not more than 2 minutes. The sound does not tell you which one of those statuses it is — it tells you to consider that the other vessel may have particular limitations.']],play:['specialFog']},
 {title:'Manoeuvring in sight',sub:'Rule 34(a)',intro:'These signals state what a power-driven vessel is doing when vessels are in sight of one another.',facts:[['• One short','I am altering my course to starboard.'],['•• Two short','I am altering my course to port.'],['••• Three short','I am operating astern propulsion.'],['Important','Three short does not mean simply “I am going backwards”; it states that astern propulsion is being operated.']],play:['stbd','port','astern']},
 {title:'Overtaking, doubt & bends',sub:'Rule 34(c–e)',intro:'Narrow-channel overtaking and warning signals have distinctive patterns.',facts:[['— — •','I intend to overtake you on your starboard side.'],['— — ••','I intend to overtake you on your port side.'],['— • — •','Agreement by the vessel being overtaken.'],['•••••+','At least five short and rapid blasts: doubt about the other vessel’s intentions/actions or doubt whether sufficient action is being taken.'],['—','One prolonged when nearing an obscured bend/area of a channel or fairway; an approaching vessel within hearing answers with one prolonged.']],play:['overtakeStbd','overtakePort','agreeOvertake','doubt','bend']},
 {title:'Fog — vessels underway',sub:'Rule 35(a–f)',intro:'In or near restricted visibility, signals identify status and activity. They apply by day or night.',facts:[['Power-driven making way','One prolonged, at intervals of not more than 2 minutes.'],['Power-driven stopped, no way','Two prolonged, about 2 seconds apart, at intervals of not more than 2 minutes.'],['NUC / RAM / CBD / sailing / fishing','One prolonged followed by two short, at intervals of not more than 2 minutes. These terms are introduced in the plain-English vessel-status lesson.'],['Towing or pushing','One prolonged followed by two short.'],['Last vessel of a manned tow','One prolonged followed by three short, when practicable immediately after the towing vessel.'],['Rigid composite unit','Treated as a power-driven vessel.']],play:['pdMakingWay','pdStopped','specialFog','towLast']},
 {title:'Fog — anchor, aground & pilot',sub:'Rule 35(g–k)',intro:'Bell and gong patterns matter just as much as whistle patterns.',facts:[['Anchor under 100 m','Rapid bell for about 5 seconds at intervals of not more than 1 minute.'],['Anchor 100 m or more','Rapid bell forward, then rapid gong aft, each about 5 seconds.'],['Aground','Anchor bell signal plus three distinct bell strokes immediately before and after the rapid ringing.'],['Fishing / RAM at anchor','When carrying out their work at anchor, use the Rule 35(c) whistle signal instead of the ordinary anchor signal.'],['Pilot vessel','When engaged on pilotage duty may add four short blasts to the appropriate Rule 35 signal.'],['Attention, distress & watchkeeping','Know the difference between attracting attention, indicating distress, and making an ordinary COLREG sound signal.'],['Rule 36','A vessel may make light or sound signals to attract attention provided they cannot be mistaken for an authorised signal, and may direct a searchlight without embarrassing another vessel.'],['Rule 37','A vessel in distress and requiring assistance uses or exhibits the signals described in Annex IV.'],['Examples','SOS, MAYDAY, red flares/rockets, orange smoke and continuous sounding of fog-signalling apparatus are among recognised distress indications.'],['Restricted visibility','Hearing is part of the lookout. Rule 35 signals are required in or near restricted visibility, not only in fog.'],['Bridge habit','Hear the pattern, identify only what it actually tells you, then maintain lookout and apply the relevant steering and sailing rules.']],play:['anchor','anchor100','aground','pilot','doubt','specialFog']}];
window.PW_ORIGINAL_LIBRARIES.STAGE5_LESSONS = [
 {title:'Lookout, safe speed & collision risk',sub:'Rules 5–7',intro:'Before deciding who gives way, establish the traffic picture and decide whether risk of collision exists.',facts:[['Proper lookout','Maintain a proper lookout by sight and hearing as well as by all available means appropriate to the circumstances.'],['Safe speed','Proceed at a safe speed so effective avoiding action can be taken and the vessel can be stopped within an appropriate distance.'],['Risk of collision','Use all available means appropriate to determine whether risk exists. If in doubt, risk is deemed to exist.'],['Compass bearing','An appreciably steady bearing of an approaching vessel can indicate collision risk; risk can still exist with bearing change, especially with a large vessel, tow or close range.']]},
 {title:'Early, positive avoiding action',sub:'Rule 8',intro:'Correct classification is only useful if the action that follows is clear, early and effective.',facts:[['Positive and in ample time','Avoiding action should be positive, made in ample time and with due regard to good seamanship.'],['Make it obvious','Course and/or speed changes should, if circumstances admit, be large enough to be readily apparent; avoid a succession of small alterations.'],['Safe passing distance','The action must result in passing at a safe distance.'],['Check the result','Keep checking the effectiveness of the action until the other vessel is finally past and clear.'],['Slow or stop','If necessary, slacken speed or take all way off by stopping or reversing propulsion.']]},
 {title:'Overtaking & head-on',sub:'Rules 13–14',intro:'These two encounter families have strong rules that remain easy to apply when recognised early.',facts:[['Overtaking sector','More than 22.5° abaft the beam. If in doubt, assume overtaking.'],['Overtaking duty continues','The overtaking vessel keeps out of the way until finally past and clear.'],['Head-on','Power-driven vessels meeting on reciprocal or nearly reciprocal courses with risk of collision each alter to starboard.'],['Head-on doubt','If in doubt whether a head-on situation exists, assume it does and act accordingly.']]},
 {title:'Crossing & stand-on escalation',sub:'Rules 15–17',intro:'Learn both sides of the crossing rule — including what happens when the expected give-way action does not happen.',facts:[['Target on your starboard','You are the give-way vessel. Keep out of the way and, if circumstances admit, avoid crossing ahead.'],['Target on your port','You are normally stand-on: keep course and speed initially.'],['Rule 17(a)(ii)','The stand-on vessel may take action when it becomes apparent the give-way vessel is not taking appropriate action.'],['Rule 17(b)','When collision cannot be avoided by give-way action alone, the stand-on vessel shall take such action as will best aid avoidance.'],['Power crossing caution','A power-driven stand-on vessel acting under 17(a)(ii) should, if circumstances admit, not alter to port for a vessel on her own port side.']]},
 {title:'Sailing vessels & responsibilities',sub:'Rules 12 & 18',intro:'Stage 5 explicitly includes sailing-vessel encounters so the learner does not apply power-v-power crossing logic to every target.',facts:[['Opposite tacks','Port tack gives way to starboard tack.'],['Same tack','The windward sailing vessel gives way to the leeward vessel.'],['Uncertain tack','A port-side-wind vessel that cannot determine whether the other sailing vessel has wind on port or starboard keeps out of the way.'],['Power vs sail','A power-driven vessel underway normally keeps out of the way of a sailing vessel when Rule 18 applies.'],['Motor-sailing','If machinery is propelling the vessel, treat it as power-driven for collision responsibilities.'],['Overtaking still wins','Rule 13 applies notwithstanding the other in-sight rules: an overtaking vessel keeps out of the way.']]},
 {title:'Hierarchy, special waters & restricted visibility',sub:'Rules 9, 10, 18 & 19',intro:'The final lesson prevents the common mistake of treating every encounter as a simple crossing problem.',facts:[['Rule 18 responsibilities','Power-driven vessels underway keep out of the way of NUC, RAM, fishing and sailing vessels as specified by Rule 18, subject to Rules 9, 10 and 13.'],['Narrow channels','Rule 9 adds duties including keeping near the starboard outer limit where safe and practicable and not impeding certain vessels.'],['Traffic separation','Rule 10 governs conduct in TSS but does not remove the other collision-avoidance duties.'],['Restricted visibility','When vessels are not in sight in or near restricted visibility, use Rule 19 rather than normal Rules 11–18 encounter labels.'],['Rule 19 caution','For a vessel detected by radar alone, avoid an alteration to port for a vessel forward of the beam, other than one being overtaken, so far as possible.']]}
];
window.PW_ORIGINAL_LIBRARIES.AIS_STAGE8_LESSONS = [
 {title:'What AIS actually is',sim:1,body:'AIS automatically exchanges identity and movement information between suitably equipped vessels and shore stations. Its great strength is situational awareness: it can help you identify a contact and understand the electronic traffic picture.',pts:[['USE IT FOR','Identity, target tracking and extra situational information.'],['DO NOT ASSUME','That every vessel is transmitting AIS or that every transmitted field is correct.'],['CORE HABIT','Correlate the AIS target with what you can see and, where fitted, radar.'],['COLREGS','AIS does not create a new right-of-way system.']],call:'AIS is an additional source of navigational information. It supports the watch; it does not replace the watch.'},
 {title:'Read the target — but question the data',sim:1,body:'Separate what the target reports into useful groups. Identity and vessel particulars help tell you who or what the contact may be. Dynamic information describes present movement. Some voyage information is manually entered and can be old or simply wrong.',pts:[['IDENTITY','Name, MMSI, call sign and ship type can help identify a target.'],['DYNAMIC','Position, COG and SOG update automatically from connected sensors.'],['MANUAL FIELDS','Destination, draught, ETA and navigational status may depend on human input.'],['AGE','A fresh-looking screen can still contain stale or erroneous source data.']],call:'Treat AIS data as information to verify, not truth to obey. A convincing ship name does not make the rest of the transmitted data accurate.'},
 {title:'COG is not heading',sim:2,body:'Course over ground is the direction the vessel is actually moving across the earth. Heading is where its bow points. Current, tide and leeway can make the two values different, so they answer different questions.',pts:[['COG','Direction of movement over the ground.'],['HEADING','Direction the bow is pointing.'],['SOG','Speed over the ground.'],['WHY IT MATTERS','Do not build a COLREG judgement from one AIS number in isolation.']],call:'When COG and heading differ, do not call one of them “wrong”. First understand what each value represents and cross-check the developing situation.'},
 {title:'CPA & TCPA — prediction, not permission',sim:3,body:'CPA predicts the closest passing distance if the present motion continues. TCPA predicts when that closest point will occur. They are useful warning and monitoring values, but they change when either vessel manoeuvres and should not be treated as permission to stand on.',pts:[['CPA','Predicted closest point of approach.'],['TCPA','Predicted time until CPA.'],['TREND','Watch whether the situation is improving or deteriorating.'],['ACTION','Collision avoidance remains a COLREG decision using all available means.']],call:'A small CPA deserves attention; a “comfortable” AIS CPA is not a licence to stop looking outside or stop checking radar.'},
 {title:'Class A, Class B and the incomplete picture',sim:4,body:'AIS equipment does not all transmit identical information or at identical reporting behaviour. Small craft may use Class B, some vessels are not required to carry AIS, and some contacts may not appear at all.',pts:[['CLASS A','Common on SOLAS commercial shipping and carries the fuller shipborne data set.'],['CLASS B','Common on smaller/non-SOLAS craft; capabilities and reporting differ from Class A.'],['NO AIS','A real vessel can exist without appearing as an AIS target.'],['RADAR/VISUAL','Objects and vessels may be detectable by other means even when absent from AIS.']],call:'The empty space between AIS symbols is not necessarily empty sea. Keep the lookout and use all appropriate sensors.'},
 {title:'Stale, lost, wrong and virtual targets',sim:5,body:'An AIS symbol can become stale when reports stop. Incorrect sensor or manually entered data can be transmitted. AIS can also represent physical, synthetic or virtual aids to navigation, so an electronic symbol is not always a physical object at that exact position.',pts:[['STALE','The last report gets older; the vessel has not necessarily disappeared.'],['WRONG DATA','Bad input or sensor data can create misleading information.'],['POSITION','AIS position comes from the transmitting target’s electronic position source.'],['VIRTUAL AtoN','Some AIS navigation marks can exist electronically without a physical buoy there.']],call:'If AIS and the outside/radar picture disagree, investigate the disagreement. Never force reality to fit the electronic display.'},
 {title:'The safe AIS watch',sim:3,body:'The safest way to use AIS is as one layer in a wider watchkeeping picture. Identify, correlate, monitor trends and then apply the COLREGs using sight, hearing, radar where fitted and every other appropriate means.',pts:[['LOOK OUT','Maintain a proper visual and auditory lookout.'],['CROSS-CHECK','Correlate AIS with radar and the real-world picture where available.'],['RULE 7','Use all available means appropriate to determine risk of collision.'],['VHF','Do not let an AIS name tempt you into negotiating away clear COLREG responsibilities by radio.']],call:'Stage 8 principle: AIS improves situational awareness when it is cross-checked. Over-reliance on it can reduce situational awareness.'}
];
