/* Original Project Watch reference and training data. */
window.PW_ORIGINAL_LIBRARIES=window.PW_ORIGINAL_LIBRARIES||{};
window.PW_ORIGINAL_LIBRARIES.BV_ASPECTS=[['ahead','BOW'],['stbd','STARBOARD'],['astern','STERN'],['port','PORT']];
window.PW_ORIGINAL_LIBRARIES.BV=[
{id:'pd',name:'Power-driven vessel under 50 m, underway',kind:'cargo',rule:'23',shape:'',status:[],nav:'pd',memory:'One masthead white, sidelights and sternlight.'},
{id:'pd50',name:'Power-driven vessel 50 m or more, underway',kind:'ship',rule:'23',shape:'',status:[],nav:'pd2',memory:'Two masthead whites; after masthead light higher. Sidelights and sternlight.'},
{id:'sail',name:'Sailing vessel underway',kind:'yacht',rule:'25',shape:'',status:[],nav:'sail',memory:'Sidelights and sternlight. This core scene does not use the optional red-over-green pair.'},
{id:'motor',name:'Sailing vessel proceeding under machinery',kind:'yacht',rule:'25',shape:'coneDown',status:[],nav:'pd',memory:'By day: cone apex downward. At night she displays the lights for a power-driven vessel of her size.'},
{id:'trawl',name:'Vessel engaged in trawling, making way',kind:'trawler',rule:'26',shape:'conesMeet',status:[['G',270,92],['W',270,126]],nav:'move',memory:'Green over white all-round. When making way: sidelights and sternlight.'},
{id:'fish',name:'Fishing other than trawling, making way',kind:'fisher',rule:'26',shape:'conesMeet',status:[['R',270,92],['W',270,126]],nav:'move',memory:'Red over white all-round. When making way: sidelights and sternlight.'},
{id:'nuc',name:'Vessel not under command, making way',kind:'ship',rule:'27',shape:'twoBalls',status:[['R',270,88],['R',270,124]],nav:'move',memory:'Two all-round reds. When making way: sidelights and sternlight; no masthead light.'},
{id:'ram',name:'Restricted in ability to manoeuvre, making way',kind:'work',rule:'27',shape:'ballDiamondBall',status:[['R',270,70],['W',270,106],['R',270,142]],nav:'pd',memory:'Red-white-red all-round plus power-driven lights when making way.'},
{id:'cbd',name:'Vessel constrained by her draught',kind:'tanker',rule:'28',shape:'cylinder',status:[['R',270,68],['R',270,104],['R',270,140]],nav:'pd2',memory:'May show three all-round reds or a cylinder in addition to Rule 23 lights.'},
{id:'pilot',name:'Pilot vessel on pilotage duty, underway',kind:'pilot',rule:'29',shape:'',status:[['W',270,88],['R',270,124]],nav:'move',memory:'White over red all-round; when underway, sidelights and sternlight.'},
{id:'anchorU50',name:'Vessel at anchor — under 50 m',kind:'ship',rule:'30',shape:'ball',status:[['W',310,95]],nav:'none',memory:'One all-round white anchor light may be shown where it can best be seen; one ball by day.'},
{id:'anchor50',name:'Vessel at anchor — 50 m or more',kind:'ship',rule:'30',shape:'ball',status:[['W',310,95],['W',230,126]],nav:'none',memory:'Forward all-round white and a second all-round white at or near the stern at a lower level; one ball by day.'},
{id:'agroundU50',name:'Vessel aground — under 50 m',kind:'ship',rule:'30',shape:'threeBalls',status:[['R',270,83],['R',270,119],['W',320,100]],nav:'none',memory:'Anchor light for a vessel under 50 m plus two all-round reds; three balls by day.'},
{id:'aground50',name:'Vessel aground — 50 m or more',kind:'ship',rule:'30',shape:'threeBalls',status:[['R',270,83],['R',270,119],['W',320,100],['W',220,132]],nav:'none',memory:'Forward and lower after anchor whites plus two all-round reds; three balls by day.'},
{id:'towShort',name:'Towing astern — tow 200 m or less',kind:'work',rule:'24',shape:'',status:[],nav:'tow2',memory:'Two masthead towing lights in a vertical line, sidelights, sternlight, and a yellow towing light vertically above the sternlight.'},
{id:'towLong',name:'Towing astern — tow over 200 m',kind:'work',rule:'24',shape:'diamond',status:[],nav:'tow3',memory:'Three masthead towing lights in a vertical line; a diamond by day; sidelights, sternlight, and a yellow towing light above the sternlight.'},
{id:'push',name:'Pushing ahead / towing alongside — not a composite unit',kind:'work',rule:'24',shape:'',status:[],nav:'push',memory:'Two masthead lights in a vertical line, sidelights, and a sternlight.'},
{id:'composite',name:'Rigid composite unit',kind:'work',rule:'24',shape:'',status:[],nav:'pd',memory:'A rigidly connected pushing vessel and vessel pushed ahead are treated as one power-driven vessel under Rule 23.'},
{id:'gear150',name:'Fishing — outlying gear over 150 m to starboard',kind:'fisher',rule:'26',shape:'conesGear',status:[['R',270,92],['W',270,126],['W',365,126]],nav:'move',memory:'Red over white, plus an all-round white toward the outlying gear; this training example places the gear to starboard. By day an extra cone apex upward is shown toward the gear.'},
{id:'dredge',name:'Dredging / underwater operations — obstruction to starboard',kind:'work',rule:'27',shape:'dredge',status:[['R',270,58],['W',270,94],['R',270,130],['R',365,82],['R',365,118],['G',175,82],['G',175,118]],nav:'pd',memory:'RAM red-white-red, plus two red on the obstruction side and two green on the side on which another vessel may pass.'},
{id:'diving',name:'Diving operations — reduced display',kind:'work',rule:'27',shape:'alpha',status:[['R',270,58],['W',270,94],['R',270,130]],nav:'none',memory:'Where the vessel is too small for the full dredging display: red-white-red all-round plus a rigid International Code flag A by day.'},
{id:'mine',name:'Mine-clearance vessel',kind:'ship',rule:'27',shape:'mineBalls',status:[['G',270,62],['G',195,112],['G',345,112]],nav:'pd',memory:'Three all-round green lights, or three balls by day: one near the foremast head and one at each end of the fore yard. It is dangerous to approach within 1000 m.'}
];
