/* Original Project Watch lessons. External authority links are references, not reused course material. */
window.PW_SAFETY_AWARENESS = Object.freeze({
  lessons:[
    {id:'prepare',title:'Before leaving the berth',image:'assets/safety/departure.svg',alt:'Five connected pre-departure decisions: conditions, vessel, people, equipment and fallback.',scene:'assets/safety/scenes/departure.webp',sceneAlt:'Two recreational boaters wearing lifejackets review a chart and conditions before departure.',sceneCaption:'Before leaving: agree the route, limits and fallback while the boat is safely alongside.',lead:'A safe trip starts with a decision to go, delay, change the plan or stay alongside.',points:[
      ['Conditions and limits','Check the latest forecast, tides, visibility and the crew’s ability. Decide on a clear turn-back point.'],
      ['Vessel and crew','Check fuel, engine, bilges, batteries, navigation and communications. Brief every person on hazards, emergency gear and who can take over.'],
      ['Tell someone','Share destination, route, crew, expected return and what to do if overdue with a reliable shore contact.']
    ],scenario:'The forecast worsens and one crew member has never used the VHF. Pause departure, revise the plan and brief the crew before deciding whether to go.',source:'ryaPassage'},
    {id:'risk',title:'Spot and control risk',image:'assets/safety/risk-cycle.svg',alt:'Risk assessment loop: spot hazard, identify who may be harmed, control it, brief the crew and review.',scene:'assets/safety/scenes/risk.webp',sceneAlt:'Two boaters pause when they notice a loose line crossing the side deck.',sceneCaption:'Look first: the loose line crosses the walking route. Secure it before anyone uses the deck.',lead:'Look for what could cause harm, then change the task so the hazard is less likely to hurt anyone.',points:[
      ['Spot the hazard','Examples include a wet deck, loose mooring line, anchor windlass, hot exhaust or exposed rail. Ask who might be harmed and how.'],
      ['Control the source','Change or stop the task, isolate equipment, establish a safe working area and use suitable protection. A checklist alone does not remove danger.'],
      ['Review as conditions change','A safe deck in harbour can become unsafe in darkness or rough water. Brief the crew and revisit controls after a change or near miss.']
    ],scenario:'A mooring line now runs across the route to the foredeck. Re-route people and secure the line before the next task.',source:'ryaSafety'},
    {id:'deck',title:'Stay aboard and work safely',image:'assets/safety/deck-zones.svg',alt:'Five deck work reminders: handholds, clear route, line of pull, moving gear and rail.',scene:'assets/safety/scenes/deck.webp',sceneAlt:'Lifejacket-wearing boater uses a handhold on a pleasure boat side deck, with mooring gear nearby.',sceneCaption:'Use handholds and keep a clear route. Assess any loaded line on the actual boat before approaching it.',lead:'The best man overboard response is to prevent someone entering the water.',points:[
      ['Control movement','Keep decks clear, move with handholds, use non-slip footwear and avoid working alone on an exposed deck where possible.'],
      ['Keep clear of loaded lines','Never stand in a bight. Brief the crew on the actual line lead, possible snap-back and moving gear; the rest of the deck is not automatically safe. Stop the operation and release the load safely before dealing with a snag.'],
      ['Wear suitable flotation','Choose a lifejacket appropriate to the boat, conditions and wearer. Check its fit, condition and fastenings, and follow the maker’s instructions.']
    ],scenario:'While berthing a pleasure boat, a mooring line snags and comes tight. Stop hauling, keep bystanders clear and reassess how to release it without putting anyone in a bight or possible snap-back area.',source:'mcaMooring'},
    {id:'equipment',title:'Know and check the safety kit',image:'assets/safety/kit-check.svg',alt:'Original visual checklist for lifejacket, communication, fire and recovery equipment.',scene:'assets/safety/scenes/equipment.webp',sceneAlt:'Crew check a lifejacket and locate a throw line, VHF and extinguisher in a pleasure boat cockpit.',sceneCaption:'Check fit, access and crew familiarity with the equipment aboard your own boat.',lead:'Equipment helps only if it is accessible, serviceable and the crew know how to use it.',points:[
      ['Personal flotation','Confirm correct fit, fastenings, service status and that each person knows how to put it on. Follow the maker’s instructions for inspection.'],
      ['Alarm and communication','Know the fixed and handheld VHF, position source and emergency contacts. Keep a charged backup and explain how to raise an alarm.'],
      ['Fire, flooding and recovery','Locate extinguishers, pump controls, seacocks, throw line and recovery aid. Check access and assign roles before departure.']
    ],scenario:'The throw line is buried in a locker beneath luggage. Move it to an accessible position and make sure the crew can find it.',source:'ryaSafety'},
    {id:'human',title:'People and changing conditions',image:'assets/safety/decision.svg',alt:'A decision tree for fatigue, weather and an unsafe task: slow down, change plan or stop.',scene:'assets/safety/scenes/conditions.webp',sceneAlt:'Two recreational boaters discuss a chart and weather in a wheelhouse while safely in harbour.',sceneCaption:'Changing conditions are a prompt to pause, share information and revise the plan.',lead:'Fatigue, cold, pressure and distraction can turn a routine operation into a mistake.',points:[
      ['Recognise fatigue','Look for slower reactions, missed checks, poor judgement or a change in mood. Arrange rest and a competent handover.'],
      ['Use a stop point','Anyone should be able to say that an operation is unsafe. Pause, reassess and change the plan without blame.'],
      ['Keep a margin','Reduce workload when visibility or sea state worsens. Turn back or seek shelter before options narrow.']
    ],scenario:'The only person keeping lookout is struggling to stay alert. Hand over to a competent rested person or make a safe plan to stop.',source:'ryaLookout'},
    {id:'respond',title:'Act early in an emergency',image:'assets/safety/emergency.svg',alt:'Five response steps: alert, protect, call, manage and review.',scene:'assets/safety/scenes/emergency.webp',sceneAlt:'Lifejacket-wearing crew practise a man overboard drill with a training dummy in sheltered water.',sceneCaption:'Practice drill: one person keeps sight and raises the alarm while the helm maintains control.',lead:'A simple, rehearsed response is easier to follow under pressure.',points:[
      ['Alert and protect','Raise the alarm, account for everyone and keep rescuers safe. Take immediate action only within your capability.'],
      ['Call for help','Use the appropriate maritime distress or urgency procedure and give identity, position, nature of problem and assistance needed. VHF operation needs separate training.'],
      ['Manage and review','Stabilise the vessel if safe, follow the emergency plan, preserve a lookout and reassess. Practise procedures with the actual crew and equipment.']
    ],scenario:'A crew member falls overboard. Shout, maintain sight, alert the skipper and start the practised recovery plan while summoning help as needed.',source:'ryaSurvival'}
  ],
  questions:[
    {lesson:'prepare',q:'The forecast has worsened beyond your crew’s comfortable limits. What is the safer decision?',image:'assets/safety/photos/fog.jpg',imageAlt:'Fog obscuring vessels at a harbour',choices:['Delay or change the passage and reassess','Depart and decide once offshore','Rely on the plotter to avoid the weather'],correct:0,why:'Departure is a decision point. Change the plan before losing easy options.'},
    {lesson:'prepare',q:'What should a shore contact know before a passage?',choices:['Only the name of the boat','Route, people aboard, expected return and overdue action','The chartplotter brand'],correct:1,why:'A useful passage plan gives a shore contact enough information to raise an appropriate alarm.'},
    {lesson:'risk',q:'A loose line creates a trip hazard on deck. What is the best first control?',choices:['Put up a warning and carry on','Remove or secure the line and keep the route clear','Ask the crew to step over it'],correct:1,why:'Control the hazard at its source rather than relying on people to avoid it.'},
    {lesson:'risk',q:'When should a task risk assessment be revisited?',choices:['Only when the vessel is sold','When conditions, equipment or the operation change','After an accident only'],correct:1,why:'Controls need review whenever the situation changes materially.'},
    {lesson:'deck',q:'While mooring a pleasure boat, a line snags and comes under heavy tension. What should the skipper do before anyone tries to free it?',choices:['Ask someone to stand outside the straight line of pull; that part of the deck must be safe','Stop hauling, keep others clear and assess the line lead, bights and possible snap-back before safely easing the load','Have a crew member step into the bight to lift the line free'],correct:1,why:'The danger is not limited to the straight line of pull. A snagged line can release suddenly, and the possible snap-back area depends on its lead. Stop and reassess before handling it.'},
    {lesson:'deck',q:'A line has jammed in moving machinery. What should happen first?',choices:['Reach in before it gets worse','Stop and isolate the machinery before handling it','Increase speed to clear the jam'],correct:1,why:'Remove the energy source before anyone approaches the jam.'},
    {lesson:'equipment',q:'What makes a lifejacket ready for use?',image:'assets/safety/photos/lifejacket-check.jpg',imageAlt:'A lifejacket checked during a boat inspection',choices:['It is somewhere aboard','It fits the wearer, is serviceable and is worn correctly','It is the same colour as the boat'],correct:1,why:'Availability alone does not make flotation effective.'},
    {lesson:'equipment',q:'A recovery line is buried beneath equipment. What is the problem?',image:'assets/safety/photos/lifebuoy.jpg',imageAlt:'Accessible lifebuoy secured to a ship rail',choices:['No problem if someone knows it is there','It may be inaccessible when seconds matter','It should always be kept below deck'],correct:1,why:'Emergency equipment should be accessible and its location understood.'},
    {lesson:'human',q:'A watchkeeper is making repeated mistakes from fatigue. What is the best response?',choices:['Continue to maintain the schedule','Arrange a competent handover or stop safely','Turn up the radio volume'],correct:1,why:'Fatigue reduces attention and judgement; change the watch arrangement.'},
    {lesson:'human',q:'A crew member says a deck task feels unsafe. What should the skipper do?',choices:['Pause and reassess with the crew','Tell them to finish quickly','Ignore it unless an accident occurs'],correct:0,why:'A stop point lets the crew control a developing risk.'},
    {lesson:'respond',q:'A person falls overboard. What immediate actions fit the plan?',choices:['Keep visual contact, raise the alarm and start recovery','Leave the helm unattended to search lockers','Wait to see if they swim back'],correct:0,why:'An immediate alert and maintained visual contact support recovery.'},
    {lesson:'respond',q:'When calling for help, what information is most useful?',choices:['Boat colour only','Identity, position, problem and assistance needed','The price of the safety equipment'],correct:1,why:'Clear details help responders locate and assist the vessel.'}
  ],
  sources:{
    mcaMooring:{label:'MCA: mooring and hauling safety (MGN 592 Amendment 2)',url:'https://www.gov.uk/government/publications/mgn-592-mf-anchoring-mooring-towing-or-hauling-equipment/mgn-592-mf-amendment-2-anchoring-mooring-towing-or-hauling-equipment-on-all-vessels'},
    ryaPassage:{label:'RYA: passage planning and crew briefing',url:'https://www.rya.org.uk/water-safety/passage-planning-and-navigation/passage-planning/'},
    ryaSafety:{label:'RYA: on-water safety advice',url:'https://www.rya.org.uk/water-safety/'},
    ryaSurvival:{label:'RYA: Basic Sea Survival course overview',url:'https://www.rya.org.uk/course-finder/basic-sea-survival-certificate/'},
    ryaLookout:{label:'RYA: safe speed and proper lookout',url:'https://www.rya.org.uk/water-safety/safe-speed-and-proper-look-out/'},
    ryaEquipment:{label:'RYA: equipment for UK pleasure vessels',url:'https://www.rya.org.uk/water-safety/equipment-for-uk-pleasure-vessels/'}
  }
});
