/* Project Watch content library; copied without editing questions or answer indexes. */
window.PW_ORIGINAL_LIBRARIES = window.PW_ORIGINAL_LIBRARIES || {};
window.PW_ORIGINAL_LIBRARIES.SIG_FINAL_QUIZ = [
 ['Listen to the signal. A power-driven vessel is in sight and underway. What manoeuvre is she indicating?',['Altering course to starboard','Altering course to port','Operating astern propulsion'],0,'Rule 34(a): one short blast indicates an alteration of course to starboard.','stbd'],
 ['Listen to the signal. A power-driven vessel is in sight and underway. What is she indicating?',['She is stopped','She is operating astern propulsion','She is turning around'],1,'Rule 34(a): three short blasts mean operating astern propulsion.','astern'],
 ['Listen to the signal. You are in a narrow channel and another vessel is signalling an intention to overtake. What intention is being indicated?',['Overtake on your starboard side','Overtake on your port side','Agreement to be overtaken'],1,'Rule 34(c): two prolonged followed by two short blasts indicate an intention to overtake on the other vessel’s port side.','overtakePort'],
 ['Listen to the signal. What does it indicate?',['Danger or doubt','A vessel stopped in fog','Pilot vessel identity'],0,'Rule 34(d): at least five short and rapid blasts are the danger / doubt signal.','doubt'],
 ['Listen to the restricted-visibility signal. Which vessel state matches it?',['Power-driven vessel making way through the water','Power-driven vessel underway but stopped and making no way','Sailing vessel underway'],0,'Rule 35(a): a power-driven vessel making way through the water sounds one prolonged blast at intervals of not more than two minutes.','pdMakingWay'],
 ['Listen to the restricted-visibility signal. Which vessel state matches it?',['Power-driven vessel underway but stopped and making no way','Power-driven vessel making way through the water','Vessel at anchor'],0,'Rule 35(b): a power-driven vessel underway but stopped and making no way sounds two prolonged blasts in succession, with about two seconds between them, at intervals of not more than two minutes.','pdStopped'],
 ['Listen to the restricted-visibility signal. Which vessel could correctly be making this Rule 35(c) signal?',['Sailing vessel underway','Power-driven vessel making way','Power-driven vessel underway but stopped'],0,'Rule 35(c): a sailing vessel underway uses one prolonged followed by two short blasts at intervals of not more than two minutes.','specialFog'],
 ['Listen to the restricted-visibility signal. Which vessel could correctly be making it?',['A manned vessel at the very end of a tow','A power-driven vessel making way','A pilot vessel adding its identity signal'],0,'Rule 35(e): when practicable, a manned vessel at the very end of a tow sounds one prolonged followed by three short blasts immediately after the towing vessel’s signal.','towLast'],
 ['Listen to the restricted-visibility signal. Which situation matches it?',['A vessel at anchor under 100 m','A power-driven vessel making way','A sailing vessel underway'],0,'Rule 35(g): a vessel at anchor under 100 m rings the bell rapidly for about five seconds at intervals of not more than one minute.','anchor'],
 ['Listen to the additional identity signal. Which vessel may add this to its appropriate Rule 35 signal?',['A pilot vessel engaged on pilotage duty','A vessel not under command','A vessel constrained by her draught'],0,'Rule 35(k): a pilot vessel engaged on pilotage duty may, in addition to the appropriate Rule 35 signal, sound four short blasts.','pilot']
];
