/* Project Watch content library; copied without editing questions or answer indexes. */
window.PW_ORIGINAL_LIBRARIES = window.PW_ORIGINAL_LIBRARIES || {};
window.PW_ORIGINAL_LIBRARIES.TSS_EXAM_BANK = [
{cat:"Under-20 m",rule:"Rule 10(j)",critical:true,visual:null,q:"Watch One is 14.2 m long. What additional Rule 10 duty applies when a power-driven vessel is following a traffic lane?",a:["Watch One always has priority because she is small", "Watch One shall not impede the safe passage of that power-driven vessel", "Watch One must stop outside every TSS", "Watch One must always use the ITZ"],correct:1,why:"Rule 10(j) requires a vessel under 20 m not to impede the safe passage of a power-driven vessel following a traffic lane."},
{cat:"Application",rule:"Rule 10(a)",critical:false,visual:null,q:"Does using or crossing a TSS remove your obligations under the other COLREGs?",a:["Yes", "No", "Only for vessels under 20 m", "Only in daylight"],correct:1,why:"Rule 10 does not relieve a vessel of obligations under any other Rule."},
{cat:"Lane use",rule:"Rule 10(b)",critical:true,visual:"textbook",q:"If Watch One is using a traffic lane, how should she proceed?",a:["Against the arrows if traffic is light", "In the appropriate lane in the general direction of traffic flow", "Along the separation line", "Across the lane diagonally"],correct:1,why:"A vessel using a TSS proceeds in the appropriate traffic lane in the general direction of traffic flow."},
{cat:"Separation",rule:"Rule 10(b)(ii)",critical:false,visual:null,q:"When using a traffic lane, what should you do regarding the separation line or zone?",a:["Keep clear so far as practicable", "Use it as extra sea room", "Follow it exactly down the centre", "Anchor on it if traffic is dense"],correct:0,why:"Rule 10(b)(ii) says to keep clear of a traffic separation line or separation zone so far as practicable."},
{cat:"Crossing",rule:"Rule 10(c)",critical:true,visual:"textbook",q:"Traffic flow is east–west. Which crossing heading best represents Rule 10(c)?",a:["North–south, as nearly as practicable at right angles to the flow", "A shallow diagonal in the same general direction as traffic", "Parallel with the lane", "Any heading provided AIS is transmitting"],correct:0,why:"Rule 10(c) requires a crossing heading as nearly as practicable at right angles to the general direction of traffic flow."},
{cat:"Heading vs COG",rule:"Rule 10(c)",critical:true,visual:"tide",q:"Tide sets Watch One sideways during a crossing. What must remain as nearly as practicable at right angles to the traffic flow?",a:["Course over ground", "Heading", "Wake", "Relative bearing of the nearest ship"],correct:1,why:"The Rule and MCA guidance refer to heading, not course over ground."},
{cat:"Heading vs COG",rule:"Rule 10(c)",critical:false,visual:"tide",q:"A tidal stream makes Watch One's track over the ground appear diagonal, while her bow remains at the proper right-angle heading. Is the diagonal COG by itself a Rule 10(c) failure?",a:["Yes", "No", "Only if speed is below 10 knots", "Only at night"],correct:1,why:"Tidal set can skew the ground track. The key Rule 10(c) requirement is the crossing heading."},
{cat:"Wrong geometry",rule:"Rule 10(c)",critical:true,visual:"wrong",q:"What is wrong with the crossing shown?",a:["Nothing; diagonal headings are preferred", "The heading is not as nearly as practicable at right angles to traffic flow", "The vessel is too slow", "The vessel should be in the separation zone"],correct:1,why:"A deliberately shallow/diagonal crossing heading does not meet the right-angle-heading requirement."},
{cat:"Crossing decision",rule:"Rule 10(c) & (j)",critical:true,visual:null,q:"A lane-following ship would have to alter course or speed because of your planned crossing. What should an under-20 m skipper do?",a:["Commit because you intend to cross at 90°", "Wait and reassess rather than impede the ship", "Enter the separation zone and stop", "Cross ahead quickly"],correct:1,why:"The 90° geometry does not cancel the under-20 m duty not to impede lane traffic."},
{cat:"Crossing continuity",rule:"Rule 10(c)",critical:true,visual:"textbook",q:"Once committed to a normal TSS crossing, what is the correct training principle?",a:["Cross the complete lane without stopping except in emergency", "Stop in the separation zone and reassess", "Alter to follow the traffic for a short distance", "Reverse course halfway across"],correct:0,why:"Current MCA guidance teaches that the complete lane should be crossed without stopping except in emergency."},
{cat:"Joining",rule:"Rule 10(b)(iii)",critical:true,visual:"join",q:"If joining a traffic lane from the side, what geometry should be used?",a:["As small an angle to traffic flow as practicable", "As close to 90° as possible", "Exactly 45°", "Any angle if clear"],correct:0,why:"Joining from the side uses a small angle to the general direction of traffic flow."},
{cat:"Leaving",rule:"Rule 10(b)(iii)",critical:false,visual:"leave",q:"If leaving a traffic lane to the side, what geometry should be used?",a:["A small angle to the traffic flow as practicable", "A 90° crossing heading", "A turn into the opposing lane", "A stop in the separation zone"],correct:0,why:"Leaving to the side is also made at as small an angle to traffic flow as practicable."},
{cat:"Bad join",rule:"Rule 10(b)(iii)",critical:true,visual:"badjoin",q:"Why is this side-entry example deliberately marked wrong?",a:["It is too shallow", "It uses a steep entry instead of a small angle to the traffic flow", "It joins at the lane termination", "It keeps clear of the separation zone"],correct:1,why:"A steep side entry is not the small-angle joining geometry called for by Rule 10."},
{cat:"Termination",rule:"Rule 10(b)(iii) & (f)",critical:false,visual:"termination",q:"What is normally the preferred place to join or leave a traffic lane?",a:["At the termination of the lane", "At the centre of the separation zone", "At any midpoint", "At the nearest cardinal mark"],correct:0,why:"Rule 10 says a vessel should normally join or leave at the termination of the lane; particular caution is required near TSS terminations."},
{cat:"Terminations",rule:"Rule 10(f)",critical:true,visual:"termination",q:"How should you navigate near the terminations of a TSS?",a:["With particular caution", "At maximum speed", "Only inside the separation zone", "Using the wrong-way lane if clear"],correct:0,why:"Rule 10(f) requires particular caution near TSS terminations."},
{cat:"ITZ",rule:"Rule 10(d)",critical:false,visual:null,q:"May a vessel under 20 m use an Inshore Traffic Zone under Rule 10(d)?",a:["Yes", "No", "Only with pilot permission", "Only if commercially registered"],correct:0,why:"Rule 10(d) expressly permits vessels under 20 m to use an ITZ."},
{cat:"ITZ",rule:"Rule 10(d)",critical:false,visual:null,q:"For a small recreational vessel, should the ITZ be treated as an empty one-way lane?",a:["Yes", "No", "Only at night", "Only when AIS shows no targets"],correct:1,why:"The ITZ is not guaranteed to be empty or one-way; proper lookout and the other COLREGs still apply."},
{cat:"ITZ",rule:"Rule 10(d)",critical:false,visual:null,q:"Which vessel is expressly among those permitted to use an ITZ?",a:["A sailing vessel", "Every deep-draught ship regardless of route", "Only naval vessels", "Only vessels over 50 m"],correct:0,why:"Rule 10(d) specifically permits sailing vessels, vessels under 20 m and fishing vessels to use the ITZ."},
{cat:"Separation zone",rule:"Rule 10(e)",critical:true,visual:null,q:"Can Watch One normally use the separation zone as convenient waiting space between the two traffic lanes?",a:["Yes", "No", "Only if under 20 m", "Only in daylight"],correct:1,why:"The separation zone is not a normal waiting area or spare sea room."},
{cat:"Separation zone",rule:"Rule 10(e)",critical:false,visual:null,q:"Which is one of the stated exceptions allowing entry into a separation zone?",a:["To avoid immediate danger", "To shorten the passage", "To overtake a slower yacht", "To improve mobile-phone reception"],correct:0,why:"Rule 10(e) includes entry to avoid immediate danger among the stated exceptions."},
{cat:"Fishing",rule:"Rule 10(i)",critical:true,visual:null,q:"A vessel engaged in fishing near a TSS must not:",a:["Impede the passage of a vessel following a traffic lane", "Use radar", "Show fishing lights", "Cross any lane under any circumstances"],correct:0,why:"Rule 10(i) says a vessel engaged in fishing shall not impede the passage of any vessel following a traffic lane."},
{cat:"Not using scheme",rule:"Rule 10(h)",critical:false,visual:null,q:"If your vessel is not using the TSS, what should you normally do?",a:["Avoid it by as wide a margin as practicable", "Run just outside the separation line", "Anchor at the termination", "Cross repeatedly to shorten the route"],correct:0,why:"Rule 10(h) says a vessel not using a TSS shall avoid it by as wide a margin as practicable."},
{cat:"Anchoring",rule:"Rule 10(g)",critical:false,visual:null,q:"What does Rule 10 say about anchoring in a TSS or near its terminations?",a:["Avoid it so far as practicable", "It is preferred for small craft", "It is required before crossing", "It is always permitted in the separation zone"],correct:0,why:"Rule 10(g) says a vessel shall so far as practicable avoid anchoring in a TSS or areas near its terminations."},
{cat:"Priority",rule:"Rule 10 + other Rules",critical:true,visual:"busy",q:"Does a ship following a traffic lane automatically have right of way over every crossing vessel?",a:["Yes", "No; the other applicable steering and sailing rules still apply", "Only if over 100 m", "Only if displaying AIS"],correct:1,why:"Traffic-lane use does not create automatic blanket priority; the other applicable COLREGs continue to operate."},
{cat:"Small vessel",rule:"Rule 10(j)",critical:true,visual:"busy",q:"What does 'shall not impede' mean in practical Project Watch training for Watch One?",a:["Force lane traffic to alter because Watch One is smaller", "Plan early so lane-following power-driven traffic is not forced to alter course or speed for Watch One", "Remain permanently outside every TSS", "Always stop before entering an ITZ"],correct:1,why:"The course teaches the under-20 m skipper to plan early and avoid creating a situation where lane traffic must alter for the small vessel."},
{cat:"Local information",rule:"Rule 10 / local provisions",critical:false,visual:null,q:"Before using a real TSS, what additional information should a recreational skipper check?",a:["The chart and Sailing Directions/local scheme provisions", "Only social-media reports", "Only AIS vessel names", "No additional information is necessary"],correct:0,why:"The Project Watch course repeatedly warns that individual schemes may contain special provisions and should be checked on the chart and in Sailing Directions."},
{cat:"Scenario",rule:"Rules 5–8 & 10",critical:true,visual:"busy",q:"You have the correct 90° heading but the traffic picture is unsafe. What should you do?",a:["Commit anyway because Rule 10(c) geometry is correct", "Remain clear and reassess; correct geometry does not replace collision-risk assessment", "Enter and stop in the separation zone", "Accelerate across ahead of the nearest ship"],correct:1,why:"Rule 10 works together with lookout, safe speed, risk assessment and avoiding-action duties."},
{cat:"Scenario",rule:"Rule 10(c) & (j)",critical:true,visual:"textbook",q:"Which sequence best matches the Project Watch under-20 m crossing method?",a:["Enter first, then search for a gap", "Read the scheme, assess traffic, do not impede, wait for a safe gap, cross on the correct heading and keep watch", "Follow the separation line until clear", "Stop between lanes and restart when convenient"],correct:1,why:"That is the complete under-20 m sequence taught in the beginner course."},
{cat:"Lane use",rule:"Rule 10(b) & (j)",critical:false,visual:null,q:"Is an under-20 m recreational vessel automatically prohibited from using a traffic lane?",a:["Yes, always", "No; if using the lane it must use the appropriate lane and flow, while still complying with Rule 10(j) and any local provisions", "Only if power-driven", "Only if sailing"],correct:1,why:"Rule 10 does not impose a blanket prohibition on an under-20 m recreational vessel using a traffic lane."},
{cat:"Final watch",rule:"Full Rule 10",critical:true,visual:"textbook",q:"Watch One has crossed both traffic lanes and cleared the far side. What happens to the watchkeeping duty?",a:["It ends immediately", "It continues; maintain lookout and continue applying the COLREGs", "AIS may now replace lookout", "The nearest lane ship becomes responsible for all avoidance"],correct:1,why:"Clearing the TSS does not end the continuous duties of proper lookout, safe navigation and collision avoidance."}
];
window.PW_ORIGINAL_LIBRARIES.TSS_QUESTIONS = [
 {q:'Traffic flows east–west. Tide sets you to starboard. Which must be as nearly as practicable at right angles to traffic flow?',a:['Heading','Course over ground','Ground track only'],ok:0,mode:'correct',why:'Correct. Rule 10(c) and current MCA guidance specify heading, not course over ground.'},
 {q:'Does a ship following a TSS lane automatically have priority over a vessel crossing the lane?',a:['Yes','No — the other applicable COLREG rules still apply','Only if over 20 m'],ok:1,mode:'busy',why:'Correct. Rule 10 does not relieve vessels of obligations under other rules.'},
 {q:'You intend to cross a lane but stop halfway in normal conditions. Is that a proper Rule 10 crossing?',a:['Yes','No','Only in daylight'],ok:1,mode:'correct',why:'Correct. MCA guidance says the entire lane should be crossed without stopping, except in emergency, and exited in one manoeuvre.'},
 {q:'Which is the better geometry for joining a lane from the side?',a:['At as small an angle to traffic flow as practicable','At 90°','Any angle if AIS is transmitting'],ok:0,mode:'join',why:'Correct. Rule 10(b) calls for as small an angle to the general direction of traffic flow as practicable when joining/leaving from the side.'}
];
