/* Independent recreational boat systems pathway. */
(function(){'use strict';
const data=window.PW_BOAT_SYSTEMS,key='pw-boat-systems-reviewed-v1';
if(!data)return;
const $=id=>document.getElementById(id),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let selected=0,mode='lesson',reviewed=[];
try{const v=JSON.parse(localStorage.getItem(key)||'[]');if(Array.isArray(v))reviewed=v.filter(n=>Number.isInteger(n)&&n>=0&&n<data.lessons.length)}catch(_){}
function top(){document.getElementById('systemsPage')?.scrollIntoView({block:'start',behavior:'instant'})}
function nav(){$('pwSystemsProgress').textContent=`${reviewed.length} / ${data.lessons.length} LESSONS REVIEWED`;$('pwSystemsLessonNav').innerHTML=data.lessons.map((l,i)=>`<button type="button" class="${mode==='lesson'&&selected===i?'active ':''}${reviewed.includes(i)?'completed':''}" onclick="pwSystemsLesson(${i})"><small>${String(i+1).padStart(2,'0')}</small> ${esc(l.title)}</button>`).join('')}
function lesson(i){selected=i;mode='lesson';let l=data.lessons[i];$('pwSystemsContent').innerHTML=`<div class="pwTidesKicker">LESSON ${String(i+1).padStart(2,'0')} / 08 • ${esc(l.subtitle)}</div><h2>${esc(l.title)}</h2><p class="pwTidesLead">${esc(l.lead)}</p><figure class="pwTidesScene pwSystemsDiagram"><img src="assets/boat-systems/${esc(l.art)}.svg" alt="${esc(l.title)} teaching diagram"><figcaption>Original Helmlore schematic • check your own boat's documentation.</figcaption></figure><div class="pwTidesPoints">${l.points.map((p,j)=>`<article><small>0${j+1}</small><h3>${esc(p[0])}</h3><p>${esc(p[1])}</p></article>`).join('')}</div><div class="pwTidesScenario"><b>PUT IT TO WORK</b><p>${esc(l.scenario)}</p></div><p class="pwTidesTakeaway"><b>Remember:</b> ${esc(l.takeaway)}</p><div class="pwTidesActions"><button type="button" onclick="pwSystemsMark()">${reviewed.includes(i)?'REVIEWED ✓':'MARK REVIEWED ✓'}</button><button type="button" class="secondary" onclick="${i<7?`pwSystemsLesson(${i+1})`:'pwSystemsWorkshop()'}">${i<7?'NEXT LESSON →':'TRY PRACTICE →'}</button></div>`;nav();top()}
window.pwSystemsOpen=function(){showModule('systems');$('moduleContextNo').textContent='05';$('moduleContextTitle').textContent='Boat Systems & Stability';$('moduleContextDesc').textContent='Eight illustrated lessons • practical decisions • knowledge check';$('moduleContextState').textContent='INDEPENDENT PATHWAY';lesson(selected)};
window.pwSystemsLesson=lesson;
window.pwSystemsMark=function(){if(!reviewed.includes(selected)){reviewed.push(selected);reviewed.sort((a,b)=>a-b);try{localStorage.setItem(key,JSON.stringify(reviewed))}catch(_){}}nav();$('pwSystemsContent').querySelector('.pwTidesActions button').textContent='REVIEWED ✓'};
const cases=[
 ['Roof load','You are adding heavy spare equipment to a flybridge roof before a coastal trip.','Move it to approved low stowage, secure it and check the vessel loading guidance.','A shorter trip or calmer forecast does not make high unsecured weight safe.'],
 ['Bilge alarm','The pump cycles repeatedly and the boat has developed a list.','Protect the crew, locate and control ingress if safe, and seek help early.','Pumping alone can mask a worsening ingress.'],
 ['Cooling alarm','Engine temperature rises and raw-water exhaust flow disappears.','Reduce demand, choose a safe situation, stop as directed and follow the engine manual.','Never open a hot pressurised cooling system to investigate.'],
 ['Electrical fault','A breaker trips a second time and a panel feels hot.','Isolate the affected circuit if safe and arrange competent investigation.','Do not up-rate the breaker or force it closed.']
];
window.pwSystemsWorkshop=function(){mode='practice';nav();$('pwSystemsContent').innerHTML=`<div class="pwTidesKicker">PRACTISE • FOUR RECREATIONAL DECISIONS</div><h2>Spot the change, make a safer choice</h2><p class="pwTidesLead">These prompts teach a response pattern. The vessel manual and actual conditions govern real actions.</p>${cases.map((c,i)=>`<article class="pwSystemsCase"><small>SCENARIO 0${i+1}</small><h3>${esc(c[0])}</h3><p>${esc(c[1])}</p><details><summary>SHOW THE SAFER RESPONSE</summary><p><b>${esc(c[2])}</b> ${esc(c[3])}</p></details></article>`).join('')}<div class="pwTidesActions"><button type="button" onclick="pwSystemsQuiz()">KNOWLEDGE CHECK →</button><button type="button" class="secondary" onclick="pwSystemsLesson(0)">REVISIT LESSONS</button></div>`;top()};
window.pwSystemsQuiz=function(){mode='quiz';nav();$('pwSystemsContent').innerHTML=`<div class="pwTidesKicker">SELF-CHECK • ORIGINAL QUESTIONS</div><h2>Check your boat-systems thinking</h2><p class="pwTidesLead">Twelve questions with explanations. This is independent practice, not an RYA or MCA qualification.</p><form id="pwSystemsQuiz">${data.quiz.map((q,i)=>`<fieldset class="pwTidesQuestion"><legend>${i+1}. ${esc(q[0])}</legend>${q[1].map((_,j)=>(j+i+1)%3).map(j=>`<label><input type="radio" name="sys${i}" value="${j}"> ${esc(q[1][j])}</label>`).join('')}<p class="feedback" id="sysFeedback${i}"></p></fieldset>`).join('')}</form><div class="pwTidesActions"><button type="button" onclick="pwSystemsCheck()">CHECK ANSWERS</button><button type="button" class="secondary" onclick="pwSystemsWorkshop()">BACK TO PRACTICE</button></div><div id="pwSystemsResult" aria-live="polite"></div>`;top()};
window.pwSystemsCheck=function(){let score=0;data.quiz.forEach((q,i)=>{let picked=document.querySelector(`input[name="sys${i}"]:checked`),ok=picked&&Number(picked.value)===q[2];if(ok)score++;let f=$('sysFeedback'+i);f.textContent=(ok?'Correct. ':'Review: '+q[1][q[2]]+'. ')+q[3];f.className='feedback '+(ok?'correct':'incorrect')});$('pwSystemsResult').innerHTML=`<b>${score} / ${data.quiz.length} correct</b><p>Review the explanations and revisit any lesson you need.</p>`};
function init(){const links=$('pwSystemsSources');if(links)links.innerHTML=data.sources.map(s=>`<a href="${esc(s[1])}" target="_blank" rel="noopener noreferrer">${esc(s[0])} ↗</a>`).join('');nav()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
