/* Chartwork UI and numerical plotting engine; original content and charts load separately. */
(function(){'use strict';
const d=window.PW_CHARTWORK;if(!d)return;
const $=id=>document.getElementById(id),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const key='pw-chartwork-reviewed-v1';let reviewed=[],mode='beginner',selected=0,task=0,lastPlot=null;
try{const v=JSON.parse(localStorage.getItem(key)||'[]');if(Array.isArray(v))reviewed=v.filter(id=>d.lessons.some(l=>l.id===id))}catch(_){}
const rad=n=>n*Math.PI/180,deg=n=>n*180/Math.PI,merc=lat=>Math.log(Math.tan(Math.PI/4+rad(lat)/2));
const ch=d.chart,scale=ch.panel.width/rad(ch.east-ch.west),height=scale*(merc(ch.north)-merc(ch.south));
function project(lat,lon){return{x:ch.panel.x+scale*rad(lon-ch.west),y:ch.panel.y+scale*(merc(ch.north)-merc(lat))}}
function unproject(x,y){return{lat:deg(2*Math.atan(Math.exp(merc(ch.north)-(y-ch.panel.y)/scale))-Math.PI/2),lon:ch.west+deg((x-ch.panel.x)/scale)}}
function inside(p){return p.lat>=ch.south&&p.lat<=ch.north&&p.lon>=ch.west&&p.lon<=ch.east}
function advance(lat,lon,bearing,nm){const distance=nm/60*Math.PI/180,b=rad(bearing),phi1=rad(lat),phi2=phi1+distance*Math.cos(b);if(Math.abs(phi2)>=Math.PI/2)throw Error('Run reaches the polar limit.');const dm=merc(deg(phi2))-merc(lat),q=Math.abs(dm)>1e-12?(phi2-phi1)/dm:Math.cos(phi1);return{lat:deg(phi2),lon:lon+deg(distance*Math.sin(b)/q)}}
function coords(p){function one(n,width,pos,neg){let value=Math.abs(n),degree=Math.floor(value),minutes=(value-degree)*60;if(minutes>=59.9995){degree++;minutes=0}return `${String(degree).padStart(width,'0')}°${minutes.toFixed(3).padStart(6,'0')}′ ${n<0?neg:pos}`}return `${one(p.lat,2,'N','S')}, ${one(p.lon,3,'E','W')}`}
function distance(a,b){const north=(b.lat-a.lat)*60,east=(b.lon-a.lon)*60*Math.cos(rad((a.lat+b.lat)/2));return Math.hypot(north,east)}
// Exposed for independent numerical checks, not for acquiring real navigation fixes.
window.PW_CHARTWORK_MATH=Object.freeze({project,unproject,advance,coords,distance});
function top(){requestAnimationFrame(()=>requestAnimationFrame(()=>$('pwChartContent').querySelector('h2')?.scrollIntoView({block:'start',behavior:'instant'})))}
function nav(){$('pwChartProgress').textContent=`${reviewed.length} / ${d.lessons.length} LESSONS REVIEWED`;$('pwChartLessonNav').innerHTML=`<button class="${mode==='beginner'?'active ':''}cwBasics" onclick="pwChartBasics(0)">START HERE • FOUR SIMPLE STEPS</button>`+d.lessons.map((l,i)=>`<button class="${mode==='lesson'&&selected===i?'active ':''}${reviewed.includes(l.id)?'completed':''}" onclick="pwChartLesson(${i})"><small>${String(i+1).padStart(2,'0')}</small> ${esc(l.title)}</button>`).join('')}
function plate(art,caption){return `<figure class="cwFigure"><img src="assets/chartwork/${esc(art)}.svg" alt="${esc(caption)}" loading="lazy"><figcaption><span>${esc(caption)}</span><button type="button" onclick="pwChartExpand('${esc(art)}')">ENLARGE CHART ↗</button></figcaption></figure>`}
function actions(next,previous,mark=false){return `<div class="cwActions">${previous?`<button class="secondary" onclick="${previous}">← BACK</button>`:''}${mark?`<button class="secondary" id="cwMark" onclick="pwChartMark()">${reviewed.includes(d.lessons[selected].id)?'REVIEWED ✓':'MARK REVIEWED ✓'}</button>`:''}<button onclick="${next}">NEXT →</button></div>`}
function basics(i,opening=false){mode='beginner';selected=i;const b=d.beginner[i];$('pwChartContent').innerHTML=`<div class="pwTidesKicker">START HERE • STEP ${i+1} OF 4</div><h2 tabindex="-1">${esc(b.title)}</h2><p class="pwTidesLead">${esc(b.lead)}</p>${plate(b.art,b.title)}<div class="pwCompassPlain"><small>IN PLAIN WORDS</small><p>${esc(b.plain)}</p></div><p class="pwTidesTakeaway"><b>Remember:</b> ${esc(b.remember)}</p>${actions(i<3?`pwChartBasics(${i+1})`:'pwChartLesson(0)',i>0?`pwChartBasics(${i-1})`:null)}`;nav();if(!opening)top()}
window.pwChartBasics=basics;
window.pwChartOpen=function(){showModule('chartwork');$('moduleContextNo').textContent='07';$('moduleContextTitle').textContent='Chart Work & Position';$('moduleContextDesc').textContent='Read • plot • fix • estimate • cross-check';$('moduleContextState').textContent='INDEPENDENT PATHWAY';basics(0,true);$('chartworkPage').scrollIntoView({block:'start',behavior:'instant'})};
window.pwChartLesson=function(i){mode='lesson';selected=i;const l=d.lessons[i];$('pwChartContent').innerHTML=`<div class="pwTidesKicker">LESSON ${String(i+1).padStart(2,'0')} / 12 • ${esc(l.subtitle)}</div><h2 tabindex="-1">${esc(l.title)}</h2><p class="pwTidesLead">${esc(l.lead)}</p>${plate(l.art,l.title)}<div class="pwTidesPoints">${l.points.map((p,n)=>`<article><small>0${n+1}</small><h3>${esc(p[0])}</h3><p>${esc(p[1])}</p></article>`).join('')}</div><div class="pwTidesScenario"><b>WORKED EXAMPLE</b><p>${esc(l.scenario)}</p></div><p class="pwTidesTakeaway"><b>Remember:</b> ${esc(l.takeaway)}</p>${actions(i<11?`pwChartLesson(${i+1})`:'pwChartPractice(0)',i>0?`pwChartLesson(${i-1})`:'pwChartBasics(3)',true)}`;nav();top()};
window.pwChartMark=function(){const id=d.lessons[selected].id;if(!reviewed.includes(id)){reviewed.push(id);try{localStorage.setItem(key,JSON.stringify(reviewed))}catch(_){}}nav();$('cwMark').textContent='REVIEWED ✓'};
window.pwChartExpand=function(art){const dialog=$('cwChartDialog');$('cwDialogImage').src=`assets/chartwork/${art}.svg`;dialog.showModal()};
function chartCanvas(){return `<div class="cwCanvasWrap"><div class="cwChartCanvas" id="cwCanvas"><img src="assets/chartwork/overview.svg" alt="Alder Bay training chart with graduated coordinate borders"><svg id="cwOverlay" viewBox="0 0 1600 1200" aria-label="Your plotted training position"></svg></div></div>`}
function overlay(points,lines=[]){const el=$('cwOverlay');if(!el)return;el.innerHTML=lines.map(l=>{const a=project(l[0].lat,l[0].lon),b=project(l[1].lat,l[1].lon);return `<line x1="${a.x}" y1="${a.y}" x2="${b.x}" y2="${b.y}" stroke="${l[2]||'#146e9d'}" stroke-width="5"/>`}).join('')+points.filter(p=>inside(p)).map((p,i)=>{const a=project(p.lat,p.lon);return `<circle cx="${a.x}" cy="${a.y}" r="${i===0?10:8}" fill="white" stroke="${p.color||'#ba3c70'}" stroke-width="4"/><text x="${a.x+17}" y="${a.y-14}" font-family="Arial" font-size="22" font-weight="700" fill="${p.color||'#ba3c70'}" paint-order="stroke" stroke="white" stroke-width="5">${esc(p.label||'Your plot')}</text>`}).join('')}
window.pwChartPractice=function(n){mode='practice';task=n;nav();const t=d.practice[n];let tools='';
if(n===0)tools=`${chartCanvas()}<div class="cwFields"><label>Latitude 50° N — minutes <input id="cwLatMinutes" type="number" min="0" max="10" step="0.001" value="4"></label><label>Longitude 004° W — minutes <input id="cwLonMinutes" type="number" min="0" max="20" step="0.001" value="10"></label><button onclick="pwChartEnterPosition()">PLOT COORDINATES</button><button onclick="pwChartCheckPosition()">CHECK MY PLOT</button></div><p id="cwPlotFeedback" role="status" aria-live="polite">No position plotted yet. The input boxes give a keyboard alternative to tapping the chart.</p>`;
else if(n===1||n===2)tools=`<div class="cwWorked"><label>My through-water distance (NM)<input id="cwRunAnswer" type="number" min="0" step="0.1" placeholder="Calculate the run"></label>${n===2?'<label>My stream displacement (NM)<input id="cwStreamAnswer" type="number" min="0" step="0.1" placeholder="Calculate the stream"></label>':''}<button onclick="pwChartRevealRun()">CHECK & SHOW THE PLOT</button><p id="cwRunFeedback" role="status" aria-live="polite"></p></div><div id="cwRunPlate"></div>`;
else tools=`<div class="cwChoices">${t.choices.map((c,i)=>`<button onclick="pwChartGPSAnswer(${i})">${esc(c)}</button>`).join('')}</div><p id="cwGPSFeedback" role="status" aria-live="polite"></p>${plate('gps','Read the GPS coordinates and check the fix independently.')}`;
$('pwChartContent').innerHTML=`<div class="pwTidesKicker">GUIDED PRACTICE • ${n+1} / 4</div><h2 tabindex="-1">${esc(t.title)}</h2><p class="pwTidesLead">${esc(t.prompt)}</p>${tools}${actions(n<3?`pwChartPractice(${n+1})`:'pwChartWorkshop()',n>0?`pwChartPractice(${n-1})`:'pwChartLesson(11)')}`;
if(n===0){lastPlot=null;const svg=$('cwOverlay');svg.addEventListener('click',e=>{const pt=svg.createSVGPoint();pt.x=e.clientX;pt.y=e.clientY;const q=pt.matrixTransform(svg.getScreenCTM().inverse()),p=unproject(q.x,q.y);if(!inside(p)){$('cwPlotFeedback').textContent='Place the position inside the graduated chart border.';return}lastPlot=p;overlay([p]);$('cwPlotFeedback').textContent='Your plot: '+coords(p)+'. Select Check my plot to compare.'})}top()};
window.pwChartEnterPosition=function(){const la=$('cwLatMinutes').value,lo=$('cwLonMinutes').value;if(la.trim()===''||lo.trim()===''||!Number.isFinite(Number(la))||!Number.isFinite(Number(lo))||Number(la)<0||Number(la)>10||Number(lo)<0||Number(lo)>20){$('cwPlotFeedback').textContent='Enter latitude minutes from 0 to 10 and west longitude minutes from 0 to 20.';return}lastPlot={lat:50+Number(la)/60,lon:-4-Number(lo)/60};overlay([lastPlot]);$('cwPlotFeedback').textContent='Your plot: '+coords(lastPlot)+'. Select Check my plot to compare.'};
window.pwChartCheckPosition=function(){const f=$('cwPlotFeedback');if(!lastPlot){f.textContent='Plot a position first.';return}const a=d.practice[0].target,target={lat:a[0],lon:a[1],label:'Target',color:'#197b5c'},err=distance(target,lastPlot);overlay([{...lastPlot,label:'Your plot'},target]);f.className=err<=.15?'cwGood':'cwReview';f.textContent=`${err<=.15?'Correct within the training tolerance.':'Review the border scales and try again.'} Your plot is ${err.toFixed(2)} NM from the target. Target: ${coords(target)}. Training tolerance: 0.15 NM; this is not a real navigation accuracy standard.`};
window.pwChartRevealRun=function(){const t=d.practice[task],a=$('cwRunAnswer').value,b=task===2?$('cwStreamAnswer').value:'1',ok=a.trim()!==''&&Math.abs(Number(a)-3)<.05&&(task!==2||(b.trim()!==''&&Math.abs(Number(b)-1)<.05));$('cwRunFeedback').className=ok?'cwGood':'cwReview';$('cwRunFeedback').textContent=(ok?'Correct. ':'Review the calculation. ')+t.answer;$('cwRunPlate').innerHTML=plate(task===1?'dr':'ep',t.answer)};
window.pwChartGPSAnswer=function(i){const t=d.practice[3],f=$('cwGPSFeedback');f.className=i===t.correct?'cwGood':'cwReview';f.textContent=(i===t.correct?'Correct. ':'Review your choice. ')+t.answer};
window.pwChartWorkshop=function(){mode='workshop';nav();$('pwChartContent').innerHTML=`<div class="pwTidesKicker">EXPLORE • SHORT-LEG TRAINING CALCULATOR</div><h2 tabindex="-1">See the run and the stream separately</h2><p class="pwTidesLead">Start at P. Change the direction, through-water speed, time and stream. The chart plots the DR first, then the EP. Assume no leeway and constant conditions.</p><div class="cwFields"><label>Through-water course (° T)<input id="cwCourse" type="number" min="0" max="359" value="90"></label><label>Speed through water (kn)<input id="cwSpeed" type="number" min="0" max="40" step="0.1" value="6"></label><label>Elapsed time (minutes)<input id="cwTime" type="number" min="1" max="120" value="30"></label><label>Stream towards (° T)<input id="cwSet" type="number" min="0" max="359" value="0"></label><label>Stream rate (kn)<input id="cwRate" type="number" min="0" max="10" step="0.1" value="2"></label><button onclick="pwChartCalculate()">CALCULATE & PLOT</button></div><output id="cwCalculation" aria-live="polite"></output>${chartCanvas()}<p class="cwSmall">Blue = through-water run to DR. Green = stream displacement from DR to EP. This short-leg rhumb-line model uses a constant stream and an approximate 60 NM per latitude degree; it is a teaching calculator.</p>${actions('pwChartQuiz()','pwChartPractice(3)')}`;window.pwChartCalculate();top()};
window.pwChartCalculate=function(){const ids=['cwCourse','cwSpeed','cwTime','cwSet','cwRate'],raw=ids.map(id=>$(id).value),[course,speed,time,set,rate]=raw.map(Number),out=$('cwCalculation');if(raw.some(s=>s.trim()==='')||[course,speed,time,set,rate].some(n=>!Number.isFinite(n))||course<0||course>=360||set<0||set>=360||speed<0||speed>40||time<1||time>120||rate<0||rate>10){out.textContent='Enter directions 0–359°, speed 0–40 kn, time 1–120 minutes and stream 0–10 kn.';$('cwOverlay').innerHTML='';return}const start={lat:50+4/60,lon:-4-10/60,label:'Start'},run=speed*time/60,dr={...advance(start.lat,start.lon,course,run),label:'DR',color:'#146e9d'},tidal=rate*time/60,ep={...advance(dr.lat,dr.lon,set,tidal),label:'EP',color:'#197b5c'};out.innerHTML=`<b>Through-water run:</b> ${run.toFixed(2)} NM → DR ${coords(dr)}<br><b>Stream displacement:</b> ${tidal.toFixed(2)} NM towards ${String(set).padStart(3,'0')}° T → EP ${coords(ep)}${!inside(dr)||!inside(ep)?'<br><strong>One or both results are outside this training chart. Reduce the run to see both points.</strong>':''}`;overlay([start,dr,ep],inside(dr)&&inside(ep)?[[start,dr,'#146e9d'],[dr,ep,'#197b5c']]:[])};
window.pwChartQuiz=function(){mode='quiz';nav();$('pwChartContent').innerHTML=`<div class="pwTidesKicker">SELF-CHECK • ORIGINAL QUESTIONS</div><h2 tabindex="-1">Check your chart-work thinking</h2><p class="pwTidesLead">${d.quiz.length} questions with explanations. Answer everything, then check. Independent practice; no RYA or MCA qualification.</p><form id="cwQuiz">${d.quiz.map((q,i)=>`<fieldset class="pwTidesQuestion"><legend>${i+1}. ${esc(q[0])}</legend>${q[1].map((_,j)=>(j+i)%3).map(j=>`<label><input type="radio" name="cwQ${i}" value="${j}"> ${esc(q[1][j])}</label>`).join('')}<p class="feedback" id="cwFeedback${i}"></p></fieldset>`).join('')}</form><div class="cwActions"><button class="secondary" onclick="pwChartWorkshop()">← PRACTICE</button><button onclick="pwChartCheckQuiz()">CHECK ANSWERS</button></div><div id="cwQuizResult" role="status" aria-live="polite"></div>`;top()};
window.pwChartCheckQuiz=function(){const missing=d.quiz.map((_,i)=>i).filter(i=>!document.querySelector(`input[name="cwQ${i}"]:checked`));if(missing.length){$('cwQuizResult').textContent=`Answer all questions before checking. ${missing.length} remaining.`;$('cwFeedback'+missing[0]).textContent='Choose an answer here.';$('cwFeedback'+missing[0]).scrollIntoView({block:'center'});return}let score=0;d.quiz.forEach((q,i)=>{const ok=Number(document.querySelector(`input[name="cwQ${i}"]:checked`).value)===q[2];if(ok)score++;const f=$('cwFeedback'+i);f.textContent=(ok?'Correct. ':'Review: '+q[1][q[2]]+'. ')+q[3];f.className='feedback '+(ok?'correct':'incorrect')});$('cwQuizResult').innerHTML=`<b>${score} / ${d.quiz.length} correct</b><p>Review the explanations and repeat any lesson you need.</p>`};
function init(){const s=$('pwChartSources');if(s)s.innerHTML=d.sources.map(a=>`<a href="${esc(a[1])}" target="_blank" rel="noopener noreferrer">${esc(a[0])} ↗</a>`).join('');nav();const dialog=$('cwChartDialog');dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
