/* Independent recreational compass pathway. */
(function(){'use strict';
const data=window.PW_COMPASS,key='pw-compass-reviewed-v1';if(!data)return;
const $=id=>document.getElementById(id),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let selected=0,mode='beginner',reviewed=[];
try{const v=JSON.parse(localStorage.getItem(key)||'[]');if(Array.isArray(v))reviewed=v.filter(n=>Number.isInteger(n)&&n>=0&&n<data.lessons.length)}catch(_){}
function top(){requestAnimationFrame(()=>requestAnimationFrame(()=>document.querySelector('#pwCompassContent h2')?.scrollIntoView({block:'start',behavior:'instant'})))}
function nav(){$('pwCompassProgress').textContent=`${reviewed.length} / ${data.lessons.length} LESSONS REVIEWED`;$('pwCompassLessonNav').innerHTML=`<button type="button" class="${mode==='beginner'?'active ':''}pwCompassBasicsButton" onclick="pwCompassBasics(0)">START HERE • THE BASICS</button>`+data.lessons.map((l,i)=>`<button type="button" class="${mode==='lesson'&&selected===i?'active ':''}${reviewed.includes(i)?'completed':''}" onclick="pwCompassLesson(${i})"><small>${String(i+1).padStart(2,'0')}</small> ${esc(l.title)}</button>`).join('')}
const art={rose:'accurate-compass-rose.png',bearing:'bearing-photograph.png',track:'track-photograph.png',north:'north-reference-accurate.png',deviation:'helm-photograph.png',conversion:'chart-table-photograph.png','plot-v2':'plot-bearing-accurate.png'};
const captions={rose:'Compass points and degree scale calculated clockwise from north.',bearing:'A handheld instrument is used to sight an identified object.',track:'Compare the bow direction with the measured track over the ground.',north:'Illustrative 15° E variation. Check actual variation for place and date.',deviation:'A fixed steering compass aboard a recreational boat.',conversion:'Chart work and magnetic corrections are separate steps. Use the worked example below.','plot-v2':'The 045° T bearing and reciprocal 225° T line are plotted on a north-up grid.'};
function scene(name,alt,caption){return `<figure class="pwTidesScene pwCompassModernScene"><img src="assets/compass/scenes/${name}" alt="${esc(alt)}" loading="lazy"><figcaption>${esc(caption)}</figcaption></figure>`}
function lesson(i){
 selected=i;mode='lesson';const l=data.lessons[i];
 const visual=l.art==='types'?`<div class="pwCompassPhotoPair">${scene('helm-photograph.png','Fixed steering compass at a motor cruiser helm','Fixed at the helm • read the bow heading')}${scene('bearing-photograph.png','Boater using a handheld bearing compass to sight a lighthouse','Held to sight an identified landmark • read its bearing')}</div>`:scene(art[l.art],l.title,captions[l.art]);
 $('pwCompassContent').innerHTML=`<div class="pwTidesKicker">LESSON ${String(i+1).padStart(2,'0')} / 08 • ${esc(l.subtitle)}</div><h2>${esc(l.title)}</h2><p class="pwTidesLead">${esc(l.lead)}</p>${visual}<div class="pwTidesPoints">${l.points.map((p,j)=>`<article><small>0${j+1}</small><h3>${esc(p[0])}</h3><p>${esc(p[1])}</p></article>`).join('')}</div><div class="pwTidesScenario"><b>PUT IT TO WORK</b><p>${esc(l.scenario)}</p></div><p class="pwTidesTakeaway"><b>Remember:</b> ${esc(l.takeaway)}</p><div class="pwTidesActions"><button type="button" onclick="pwCompassMark()">${reviewed.includes(i)?'REVIEWED ✓':'MARK REVIEWED ✓'}</button><button type="button" class="secondary" onclick="${i<7?`pwCompassLesson(${i+1})`:'pwCompassWorkshop()'}">${i<7?'NEXT LESSON →':'TRY PRACTICE →'}</button></div>`;
 nav();top()
}
function basics(i,opening=false){
 mode='beginner';const b=data.beginner[i];
 const image=['accurate-compass-rose.png','helm-photograph.png','bearing-photograph.png','track-photograph.png'][i];
 const description=['Compass bearings calculated clockwise from north.','Fixed steering compass at the helm.','A handheld bearing compass sighting a lighthouse.','A boat underway with a visible track over the sea.'][i];
 $('pwCompassContent').innerHTML=`<div class="pwTidesKicker">START HERE • STEP ${i+1} OF ${data.beginner.length}</div><h2>${esc(b.title)}</h2><p class="pwTidesLead">${esc(b.lead)}</p>${scene(image,description,i===0?'Compass bearings calculated clockwise from north.':'The photo shows the instrument or situation. Use the lesson text for the sample bearings.')}<div class="pwCompassPlain"><small>IN PLAIN WORDS</small><p>${esc(b.plain)}</p></div><p class="pwTidesTakeaway"><b>Remember:</b> ${esc(b.remember)}</p>${i===2?`<div class="pwCompassBeginnerCheck"><h3>TRY ONE</h3><p>${esc(data.beginnerCheck.question)}</p>${data.beginnerCheck.choices.map((choice,n)=>`<button type="button" onclick="pwCompassBeginnerAnswer(${n})">${esc(choice)}</button>`).join('')}<p id="pwCompassBeginnerFeedback" role="status" aria-live="polite"></p></div>`:''}<div class="pwTidesActions"><button type="button" onclick="${i<data.beginner.length-1?`pwCompassBasics(${i+1})`:'pwCompassLesson(0)'}">${i<data.beginner.length-1?'NEXT SIMPLE STEP →':'GO TO THE FULL LESSONS →'}</button>${i>0?`<button type="button" class="secondary" onclick="pwCompassBasics(${i-1})">← PREVIOUS STEP</button>`:''}</div><p class="pwCompassNoRush">You can return to these four steps at any time using <b>Start here</b>.</p>`;
 nav();if(!opening)top()
}
window.pwCompassBasics=basics;
window.pwCompassBeginnerAnswer=function(n){const f=$('pwCompassBeginnerFeedback');f.textContent=n===data.beginnerCheck.correct?data.beginnerCheck.correctText:data.beginnerCheck.incorrectText;f.className=n===data.beginnerCheck.correct?'correct':'incorrect'};
window.pwCompassOpen=function(){showModule('compass');$('moduleContextNo').textContent='06';$('moduleContextTitle').textContent='Understanding Compass';$('moduleContextDesc').textContent='Four simple steps • eight visual lessons • practice';$('moduleContextState').textContent='INDEPENDENT PATHWAY';basics(0,true);$('compassPage')?.scrollIntoView({block:'start',behavior:'instant'})};
window.pwCompassLesson=lesson;
window.pwCompassMark=function(){if(!reviewed.includes(selected)){reviewed.push(selected);reviewed.sort((a,b)=>a-b);try{localStorage.setItem(key,JSON.stringify(reviewed))}catch(_){}}nav();$('pwCompassContent').querySelector('.pwTidesActions button').textContent='REVIEWED ✓'};
const fmt=n=>String(((n%360)+360)%360).padStart(3,'0')+'°';
window.pwCompassCalculate=function(){const c=Number($('pwCompassHeading').value),d=Number($('pwCompassDeviation').value),v=Number($('pwCompassVariation').value);if(!Number.isInteger(c)||c<0||c>359||!Number.isInteger(d)||Math.abs(d)>30||!Number.isInteger(v)||Math.abs(v)>30){$('pwCompassAnswer').textContent='Enter a whole compass heading from 0 to 359 and signed corrections from −30 to +30.';return}const m=((c+d)%360+360)%360,t=((m+v)%360+360)%360;$('pwCompassAnswer').innerHTML=`${fmt(c)} C ${d<0?'−':'+'} ${Math.abs(d)}° deviation = <b>${fmt(m)} M</b><br>${fmt(m)} M ${v<0?'−':'+'} ${Math.abs(v)}° variation = <b>${fmt(t)} T</b><br><small>Positive = east; negative = west. This arithmetic does not validate a real deviation card or local variation.</small>`};
window.pwCompassWorkshop=function(){mode='practice';nav();$('pwCompassContent').innerHTML=`<div class="pwTidesKicker">PRACTISE • FICTIONAL CORRECTIONS</div><h2>From compass to chart</h2><p class="pwTidesLead">Enter a compass heading and signed corrections. Use + for east and − for west. Work one reference at a time.</p><div class="pwCompassWorkshop"><label>Compass heading (° C) <input id="pwCompassHeading" type="number" min="0" max="359" step="1" value="82"></label><label>Deviation (°; east +, west −) <input id="pwCompassDeviation" type="number" min="-30" max="30" step="1" value="2"></label><label>Variation (°; east +, west −) <input id="pwCompassVariation" type="number" min="-30" max="30" step="1" value="-4"></label><button type="button" onclick="pwCompassCalculate()">CONVERT →</button><output id="pwCompassAnswer" aria-live="polite"></output></div><p class="pwTidesTakeaway"><b>Reverse it:</b> True to magnetic subtracts the signed variation; magnetic to compass subtracts the signed deviation. Check that the deviation value applies to the intended heading.</p><div class="pwTidesActions"><button type="button" onclick="pwCompassQuiz()">KNOWLEDGE CHECK →</button><button type="button" class="secondary" onclick="pwCompassLesson(0)">REVISIT LESSONS</button></div>`;window.pwCompassCalculate();top()};
window.pwCompassQuiz=function(){mode='quiz';nav();$('pwCompassContent').innerHTML=`<div class="pwTidesKicker">SELF-CHECK • ORIGINAL QUESTIONS</div><h2>Check your compass thinking</h2><p class="pwTidesLead">${data.quiz.length} questions with explanations. Independent practice, not an RYA or MCA assessment.</p><form id="pwCompassQuiz">${data.quiz.map((q,i)=>`<fieldset class="pwTidesQuestion"><legend>${i+1}. ${esc(q[0])}</legend>${q[1].map((_,j)=>(j+i+1)%3).map(j=>`<label><input type="radio" name="comp${i}" value="${j}"> ${esc(q[1][j])}</label>`).join('')}<p class="feedback" id="compFeedback${i}"></p></fieldset>`).join('')}</form><div class="pwTidesActions"><button type="button" onclick="pwCompassCheck()">CHECK ANSWERS</button><button type="button" class="secondary" onclick="pwCompassWorkshop()">BACK TO PRACTICE</button></div><div id="pwCompassResult" aria-live="polite"></div>`;top()};
window.pwCompassCheck=function(){let score=0;data.quiz.forEach((q,i)=>{const picked=document.querySelector(`input[name="comp${i}"]:checked`),ok=picked&&Number(picked.value)===q[2];if(ok)score++;const f=$('compFeedback'+i);f.textContent=(ok?'Correct. ':'Review: '+q[1][q[2]]+'. ')+q[3];f.className='feedback '+(ok?'correct':'incorrect')});$('pwCompassResult').innerHTML=`<b>${score} / ${data.quiz.length} correct</b><p>Review the explanations and revisit any lesson you need.</p>`};
function init(){const links=$('pwCompassSources');if(links)links.innerHTML=data.sources.map(s=>`<a href="${esc(s[1])}" target="_blank" rel="noopener noreferrer">${esc(s[0])} ↗</a>`).join('');nav()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
