/* Diesel UI. Lessons, questions, scenarios, credits and graphics live in separate libraries. */
(function(){'use strict';const d=window.PW_DIESEL;if(!d)return;const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let selected=0,mode='simple',reviewed=[],fault=0,solved=false;
try{reviewed=JSON.parse(localStorage.getItem('pw-diesel-reviewed-v1'))||[]}catch(_){}if(!Array.isArray(reviewed))reviewed=[];reviewed=reviewed.filter(id=>d.lessons.some(l=>l.id===id));
function top(){requestAnimationFrame(()=>requestAnimationFrame(()=>$('deContent').querySelector('h2')?.scrollIntoView({block:'start',behavior:'instant'})))}
function nav(){$('deProgress').textContent=`${reviewed.length} / ${d.lessons.length} LESSONS REVIEWED`;$('deNav').innerHTML=`<button class="${mode==='simple'?'active':''}" onclick="pwDieselSimple(0)">START HERE • THREE SIMPLE STEPS</button>`+d.lessons.map((l,i)=>`<button class="${mode==='lesson'&&selected===i?'active':''}" onclick="pwDieselLesson(${i})">${String(i+1).padStart(2,'0')} ${esc(l.title)}${reviewed.includes(l.id)?' ✓':''}</button>`).join('')}
function order(){const a=[0,1,2];for(let i=2;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function art(name,title){return `<figure class="cwFigure"><img src="assets/diesel/${name}.svg" alt="${esc(title)}" width="1440" height="900"><figcaption><span>${esc(title)}</span><button onclick="pwDieselExpand('${name}')">ENLARGE VISUAL ↗</button></figcaption></figure>`}
function actions(back,next,mark=false){return `<div class="cwActions"><button class="secondary" onclick="${back}">← BACK</button>${mark?'<button class="secondary" onclick="pwDieselMark()" id="deMark">MARK REVIEWED ✓</button>':''}<button onclick="${next}">NEXT →</button></div>`}
window.pwDieselOpen=()=>{showModule('diesel');$('moduleContextNo').textContent='09';$('moduleContextTitle').textContent='Diesel Engine Basics';$('moduleContextDesc').textContent='Understand • check • maintain • investigate';$('moduleContextState').textContent='INDEPENDENT PATHWAY';window.pwDieselSimple(0);$('dieselPage').scrollIntoView({block:'start',behavior:'instant'})};
const simple=[['What keeps a diesel running?','overview','Think of six jobs: fuel, air, cooling, lubrication, starting power and drive to the propeller. Learn those jobs before learning all the part names.'],['What do I check before starting?','checks','With the engine stopped and cool, check the specified fluids, supplies and condition. After starting, stay clear and confirm normal cooling discharge and instruments.'],['What if something changes?','cooling','Protect people and keep control of the boat first. New alarms, lost cooling or a serious leak need prompt action. Stop when safe and appropriate, then investigate by the correct manual.']];
window.pwDieselSimple=i=>{mode='simple';selected=i;const a=simple[i];$('deContent').innerHTML=`<div class="pwTidesKicker">START HERE • ${i+1} / 3</div><h2>${esc(a[0])}</h2><p class="pwTidesLead">${esc(a[2])}</p>${art(a[1],a[0])}<div class="pwCompassPlain"><small>IN PLAIN WORDS</small><p>${esc(a[2])}</p></div>${actions(i?`pwDieselSimple(${i-1})`:"showModule('home')",i<2?`pwDieselSimple(${i+1})`:'pwDieselLesson(0)')}`;nav();top()};
function credit(p){return `<p class="deCredit">${esc(p.credit)} • <a href="${esc(p.source)}" target="_blank" rel="noopener noreferrer">source</a> • <a href="${esc(p.licenseUrl)}" target="_blank" rel="noopener noreferrer">${esc(p.license)}</a>. ${esc(p.note)}</p>`}
function photo(p){return `<figure class="dePhoto"><img src="assets/diesel/${p.file}" alt="${esc(p.title)}" loading="lazy"><figcaption><b>${esc(p.title)}</b><button onclick="pwDieselPhoto('${p.file}')">ENLARGE ↗</button>${credit(p)}</figcaption></figure>`}
function engine(){const p=d.photos[5];return `<figure class="dePhoto deEngine"><div class="deEngineStage"><img src="assets/diesel/${p.file}" alt="Real four-cylinder marine diesel with five numbered component markers">${d.hotspots.map((h,i)=>`<button style="left:${h.x}%;top:${h.y}%" onclick="pwDieselIdentify(${i})" aria-label="${i+1}. ${esc(h.title)}">${i+1}</button>`).join('')}</div><figcaption><b>Explore a real engine — select a numbered component</b><div class="deEngineKeys">${d.hotspots.map((h,i)=>`<button onclick="pwDieselIdentify(${i})">${i+1}. ${esc(h.title)}</button>`).join('')}</div><div id="deComponent" role="status"><b>${esc(d.hotspots[0].title)}</b><p>${esc(d.hotspots[0].text)}</p></div>${credit(p)}</figcaption></figure>`}
window.pwDieselIdentify=i=>{const h=d.hotspots[i];$('deComponent').innerHTML='<b>'+esc(h.title)+'</b><p>'+esc(h.text)+'</p>'};
const refs={0:[0],3:[3],7:[2],8:[4],9:[1]};
window.pwDieselLesson=i=>{mode='lesson';selected=i;const l=d.lessons[i];$('deContent').innerHTML=`<div class="pwTidesKicker">LESSON ${i+1} / ${d.lessons.length}</div><h2>${esc(l.title)}</h2><p class="pwTidesLead">${esc(l.lead)}</p>${i===0?engine():art(l.art,l.title)}<div class="pwTidesPoints">${l.points.map((p,n)=>`<article><small>0${n+1}</small><h3>${esc(p[0])}</h3><p>${esc(p[1])}</p></article>`).join('')}</div>${refs[i]?`<details class="deReference"><summary>SEE THE REAL COMPONENT${refs[i].length>1?'S':''} ↗</summary>${refs[i].map(n=>photo(d.photos[n])).join('')}</details>`:''}<div class="pwTidesScenario"><b>WORKED EXAMPLE</b><p>${esc(l.example)}</p></div><p class="pwTidesTakeaway"><b>Remember:</b> ${esc(l.remember)}</p>${actions(i?`pwDieselLesson(${i-1})`:'pwDieselSimple(2)',i<d.lessons.length-1?`pwDieselLesson(${i+1})`:'pwDieselFault(0)',true)}`;nav();if(reviewed.includes(l.id))$('deMark').textContent='REVIEWED ✓';top()};
window.pwDieselMark=()=>{const id=d.lessons[selected].id;if(!reviewed.includes(id))reviewed.push(id);try{localStorage.setItem('pw-diesel-reviewed-v1',JSON.stringify(reviewed))}catch(_){}$('deMark').textContent='REVIEWED ✓';nav()};
window.pwDieselExpand=name=>{$('deDialogImage').src=`assets/diesel/${name}.svg`;$('deDialogImage').alt='Enlarged '+name.replaceAll('-',' ')+' teaching diagram';$('deDialogCaption').textContent='Original principle diagram • follow the actual engine manual';$('deDialog').showModal()};
window.pwDieselPhoto=file=>{const p=d.photos.find(p=>p.file===file);if(!p)return;$('deDialogImage').src=`assets/diesel/${p.file}`;$('deDialogImage').alt=p.title;$('deDialogCaption').innerHTML=credit(p);$('deDialog').showModal()};
window.pwDieselReferences=()=>{mode='references';nav();$('deContent').innerHTML=`<div class="pwTidesKicker">RECOGNITION • REAL MACHINERY</div><h2>Real components, real layouts</h2><p class="pwTidesLead">Compare these photographs with your own engine’s manual. The Volvo sheet shows a four-cylinder engine during dismantling; the Yanmar close-ups show a two-cylinder engine. Neither is a universal service layout.</p><div class="dePhotoGrid">${d.photos.map(photo).join('')}</div>${actions('pwDieselLesson(0)','pwDieselFault(0)')}`;top()};
window.pwDieselFault=i=>{mode='fault';fault=i;solved=false;nav();const q=d.faults[i];$('deContent').innerHTML=`<div class="pwTidesKicker">FAULT FINDING • ${i+1} / ${d.faults.length}</div><h2>What would you check first?</h2><p class="pwTidesLead">${esc(q[0])}</p>${art(q[1],'Think about the system involved')}<div class="deChoices">${order().map(j=>`<button data-choice="${j}" onclick="pwDieselAnswer(this,${j})">${esc(q[2][j])}</button>`).join('')}</div><p id="deFaultFeedback" role="status"></p><div class="cwActions"><button class="secondary" onclick="${i?`pwDieselFault(${i-1})`:'pwDieselLesson(11)'}">← BACK</button><button id="deFaultNext" disabled onclick="${i<d.faults.length-1?`pwDieselFault(${i+1})`:'pwDieselChecklist()'}">NEXT →</button></div>`;top()};
window.pwDieselAnswer=(button,j)=>{if(solved)return;const q=d.faults[fault];if(j!==q[3]){button.classList.add('incorrect');button.setAttribute('aria-pressed','true');$('deFaultFeedback').textContent='That is not the safest first response. Try another option.';return}solved=true;button.classList.remove('incorrect');button.classList.add('correct');button.setAttribute('aria-pressed','true');$('deFaultFeedback').textContent='Correct. '+q[4];$('deFaultNext').disabled=false;document.querySelectorAll('.deChoices button').forEach(b=>b.disabled=true)};
window.pwDieselChecklist=()=>{mode='checklist';nav();$('deContent').innerHTML=`<div class="pwTidesKicker">REHEARSAL • BEFORE STARTING</div><h2>Build a calm checking routine</h2><p class="pwTidesLead">A visual rehearsal of the checks, not a record that a real boat is ready. Use your boat’s own checklist and engine manual afloat.</p>${art('checks','Before starting and after starting checks')}<div class="deChecklist">${d.checklist.map((s,i)=>`<label><input type="checkbox" id="deC${i}"> ${esc(s)}</label>`).join('')}</div><div class="cwActions"><button class="secondary" onclick="pwDieselFault(7)">← FAULT FINDING</button><button onclick="pwDieselQuiz()">KNOWLEDGE CHECK →</button></div>`;top()};
window.pwDieselQuiz=()=>{mode='quiz';nav();$('deContent').innerHTML=`<div class="pwTidesKicker">SELF-CHECK • ORIGINAL QUESTION BANK</div><h2>Check your diesel understanding</h2><p class="pwTidesLead">${d.quiz.length} questions. Answer all, then check the explanations. This is a learning check, not a practical servicing qualification.</p><form>${d.quiz.map((q,i)=>`<fieldset class="pwTidesQuestion"><legend>${i+1}. ${esc(q[0])}</legend>${order().map(j=>`<label><input type="radio" name="deQ${i}" value="${j}"> ${esc(q[1][j])}</label>`).join('')}<p id="deFeedback${i}"></p></fieldset>`).join('')}</form><div class="cwActions"><button onclick="pwDieselChecklist()">← CHECK ROUTINE</button><button onclick="pwDieselCheckQuiz()">CHECK ANSWERS</button></div><p id="deQuizResult" role="status"></p>`;top()};
window.pwDieselCheckQuiz=()=>{const choices=d.quiz.map((q,i)=>document.querySelector(`input[name="deQ${i}"]:checked`));if(choices.some(c=>!c)){$('deQuizResult').textContent='Answer all questions before checking. '+choices.filter(c=>!c).length+' remaining.';return}let score=0;d.quiz.forEach((q,i)=>{const ok=Number(choices[i].value)===q[2];if(ok)score++;$('deFeedback'+i).textContent=(ok?'Correct. ':'Review: '+q[1][q[2]]+'. ')+q[3];$('deFeedback'+i).className='feedback '+(ok?'correct':'incorrect')});$('deQuizResult').textContent=`${score} / ${d.quiz.length} correct. Review the explanations and repeat any lesson you need.`};
function init(){nav();$('deSources').innerHTML=d.sources.map(s=>`<a href="${esc(s[1])}" target="_blank" rel="noopener noreferrer">${esc(s[0])} ↗</a>`).join('');$('deDialog').addEventListener('click',e=>{if(e.target===$('deDialog'))$('deDialog').close()})}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
