/* Passage UI; teaching, questions and graphics are independent library assets. */
(function(){'use strict';const d=window.PW_PASSAGE;if(!d)return;const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let selected=0,mode='simple',reviewed=[],plan={},logs=[];
function read(k,f){try{const v=JSON.parse(localStorage.getItem(k));return v??f}catch(_){return f}}
reviewed=read('pw-passage-reviewed-v1',[]);if(!Array.isArray(reviewed))reviewed=[];reviewed=reviewed.filter(id=>d.lessons.some(l=>l.id===id));plan=read('pw-passage-plan-v1',{});if(!plan||typeof plan!=='object'||Array.isArray(plan))plan={};logs=read('pw-passage-log-v1',[]);if(!Array.isArray(logs))logs=[];
function save(k,v){try{localStorage.setItem(k,JSON.stringify(v));return true}catch(_){return false}}
function top(){requestAnimationFrame(()=>requestAnimationFrame(()=>$('ppContent').querySelector('h2')?.scrollIntoView({block:'start',behavior:'instant'})))}
function nav(){$('ppProgress').textContent=`${reviewed.length} / 10 LESSONS REVIEWED`;$('ppNav').innerHTML=`<button class="${mode==='simple'?'active':''}" onclick="pwPassageSimple(0)">START HERE • THREE SIMPLE STEPS</button>`+d.lessons.map((l,i)=>`<button class="${mode==='lesson'&&selected===i?'active':''}" onclick="pwPassageLesson(${i})">${String(i+1).padStart(2,'0')} ${esc(l.title)}${reviewed.includes(l.id)?' ✓':''}</button>`).join('')}
function art(name,title){return `<figure class="cwFigure"><img src="assets/passage/${name}.svg" alt="${esc(title)}" width="1440" height="860"><figcaption><span>${esc(title)}</span><button onclick="pwPassageExpand('${name}')">ENLARGE VISUAL ↗</button></figcaption></figure>`}
function actions(back,next,mark=false){return `<div class="cwActions"><button class="secondary" onclick="${back}">← BACK</button>${mark?'<button class="secondary" onclick="pwPassageMark()" id="ppMark">MARK REVIEWED ✓</button>':''}<button onclick="${next}">NEXT →</button></div>`}
window.pwPassageOpen=()=>{showModule('passage');$('moduleContextNo').textContent='08';$('moduleContextTitle').textContent='Passage Planning & Logbook';$('moduleContextDesc').textContent='Plan • brief • monitor • record';$('moduleContextState').textContent='INDEPENDENT PATHWAY';window.pwPassageSimple(0);$('passagePage').scrollIntoView({block:'start',behavior:'instant'})};
const simple=[['Before leaving: can we make this trip?','appraisal','Check the boat, people, weather and tides. Pick a route you can safely complete, and a suitable alternative if something changes.'],['Before leaving: share a simple plan','briefing','Know where you are going, how long it may take and what would make you change your mind. Brief the crew and tell a responsible person ashore what to expect.'],['Underway: compare, record and adjust','logbook','Keep a lookout and check your progress. Record useful observations and decisions. If the facts change, change the plan. Tell your shore contact when you arrive.']];
window.pwPassageSimple=i=>{mode='simple';selected=i;const a=simple[i];$('ppContent').innerHTML=`<div class="pwTidesKicker">START HERE • ${i+1} / 3</div><h2>${esc(a[0])}</h2><p class="pwTidesLead">${esc(a[2])}</p>${art(a[1],a[0])}<div class="pwCompassPlain"><small>IN PLAIN WORDS</small><p>${esc(a[2])}</p></div>${actions(i?`pwPassageSimple(${i-1})`:"showModule('home')",i<2?`pwPassageSimple(${i+1})`:'pwPassageLesson(0)')}`;nav();top()};
window.pwPassageLesson=i=>{mode='lesson';selected=i;const l=d.lessons[i];$('ppContent').innerHTML=`<div class="pwTidesKicker">LESSON ${i+1} / 10</div><h2>${esc(l.title)}</h2><p class="pwTidesLead">${esc(l.lead)}</p>${art(l.art,l.title)}<div class="pwTidesPoints">${l.points.map((p,n)=>`<article><small>0${n+1}</small><h3>${esc(p[0])}</h3><p>${esc(p[1])}</p></article>`).join('')}</div><div class="pwTidesScenario"><b>WORKED EXAMPLE</b><p>${esc(l.example)}</p></div><p class="pwTidesTakeaway"><b>Remember:</b> ${esc(l.remember)}</p>${actions(i?`pwPassageLesson(${i-1})`:'pwPassageSimple(2)',i<9?`pwPassageLesson(${i+1})`:'pwPassagePlan()',true)}`;nav();if(reviewed.includes(l.id))$('ppMark').textContent='REVIEWED ✓';top()};
window.pwPassageMark=()=>{const id=d.lessons[selected].id;if(!reviewed.includes(id))reviewed.push(id);save('pw-passage-reviewed-v1',reviewed);$('ppMark').textContent='REVIEWED ✓';nav()};
window.pwPassageExpand=name=>{$('ppDialogImage').src=`assets/passage/${name}.svg`;$('ppDialog').showModal()};
const fields=[['boat','Boat and crew'],['date','Trip date'],['timebasis','Time basis (UTC / local zone)'],['route','Departure, destination and checked route'],['sources','Chart / pilot / notices checked and dates'],['weather','Forecast source, issue time and expected conditions'],['tide','Tide / stream sources, datum and access windows'],['limits','Boat / crew limits and go-or-delay decision'],['departure','Planned departure time'],['legs','Leg distances, expected SOG and ETA assumptions'],['pilotage','Departure and arrival pilotage'],['clearance','Draught, depth checks and clearance allowance'],['endurance','Usable fuel, consumption, diversion and reserve'],['alternative','Checked alternative / waiting place'],['triggers','Decision points and change-of-plan triggers'],['safety','Boat checks, safety kit and communication backup'],['brief','Crew briefing and roles'],['shore','Shore contact and agreed concern / arrival procedure']];
const sample={boat:'Example training boat; two rested adults, one novice',date:'Fictional exercise date',timebasis:'UTC throughout',route:'Example coastal passage; inspect every leg on current suitable charts. This text is not a real navigable route.',sources:'Exercise chart only; replace with current local chart, pilot and notices for a real trip.',weather:'Fictional favourable conditions; obtain current forecast, including return period.',tide:'Fictional access window 11:00–12:30 UTC; confirm real source, datum and local rules.',limits:'Only proceed within agreed boat and crew limits; postpone if uncertain.',departure:'09:00 UTC',legs:'6 NM + 4 NM at assumed 5 kn SOG = 2 h. Add 30 min: ETA 11:30 UTC.',pilotage:'Prepare detailed approach; identify marks, traffic, waiting place and turn-back point.',clearance:'Teaching sill: 0.8 + 2.0 − 1.6 = 1.2 m static clearance before allowances.',endurance:'Assumed 8 L/h: 20 L trip + 8 L diversion + illustrative 10 L reserve = 38 L.',alternative:'Research a suitable refuge and its access for the expected conditions.',triggers:'Missing entry window, worsening conditions, crew illness or equipment fault → reassess.',safety:'Check boat, engine, fuel, lifejackets and communication equipment; have independent backup.',brief:'Explain plan, roles, emergency equipment, how to give position and who takes over.',shore:'Responsible person informed of route, people, ETA and concern procedure; close on arrival.'};
window.pwPassagePlan=()=>{mode='plan';nav();$('ppContent').innerHTML=`<div class="pwTidesKicker">PRACTICAL • YOUR PLANNING NOTES</div><h2>Build a passage plan</h2><p class="pwTidesLead">Organise the information you have checked. An empty field is a prompt to investigate, not something to guess.</p><p class="ppNote">Notes stay in this browser when you save. They are not synced or sent to a shore contact. Export a backup and keep navigation information available without this device.</p><div class="ppToolbar"><button onclick="pwPassageExample()">VIEW WORKED EXAMPLE</button><button onclick="pwPassageSavePlan()">SAVE NOTES</button><button onclick="pwPassageExportPlan()">DOWNLOAD PLAN (.txt)</button></div><form id="ppPlanForm" class="ppForm">${fields.map(([id,label])=>`<label>${esc(label)}<textarea id="ppF_${id}" rows="3">${esc(plan[id]||'')}</textarea></label>`).join('')}</form><p id="ppPlanStatus" role="status"></p>${actions('pwPassageLesson(9)','pwPassageLog()')}`;top()};
window.pwPassageExample=()=>{const el=document.createElement('div');el.className='ppExample';el.innerHTML='<h3>Fictional worked example</h3>'+fields.map(([id,label])=>`<p><b>${esc(label)}</b><br>${esc(sample[id])}</p>`).join('');const old=$('ppExample');if(old)old.remove();el.id='ppExample';$('ppPlanForm').before(el);el.scrollIntoView({block:'start'});};
function collect(){return Object.fromEntries(fields.map(([id])=>[id,$('ppF_'+id).value]))}
window.pwPassageSavePlan=()=>{plan=collect();$('ppPlanStatus').textContent=save('pw-passage-plan-v1',plan)?'Notes saved in this browser. Export a backup.':'Browser storage is unavailable. Download your notes now.'};
function download(name,content,type){const blob=new Blob([content],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
window.pwPassageExportPlan=()=>{plan=collect();download('Helmlore-passage-plan.txt','HELMLORE — PASSAGE PLANNING NOTES\nNot a verified navigational route.\n\n'+fields.map(([id,label])=>label+'\n'+(plan[id]||'[not completed]')).join('\n\n'),'text/plain;charset=utf-8');$('ppPlanStatus').textContent='Plan download requested. Check your browser downloads.'};
const logFields=[['date','Date','date'],['time','Time','time'],['basis','Time basis','text'],['position','Position / place','text'],['source','Position source (GPS / visual fix / DR / EP)','text'],['course','Heading / course and reference (T / M / C)','text'],['speed','COG / SOG / log reading, with units','text'],['conditions','Weather / sea / depth and reference','text'],['action','Observations / decision / revised ETA','text']];
function logTable(){return `<div class="ppTableWrap"><table><caption>Saved practice log — ${logs.length} entries</caption><thead><tr><th>Date / time</th><th>Position / source</th><th>Navigation</th><th>Conditions / action</th></tr></thead><tbody>${logs.map(r=>`<tr><td>${esc(r.date)}<br>${esc(r.time)} ${esc(r.basis)}</td><td>${esc(r.position)}<br>${esc(r.source)}</td><td>${esc(r.course)}<br>${esc(r.speed)}</td><td>${esc(r.conditions)}<br>${esc(r.action)}</td></tr>`).join('')||'<tr><td colspan="4">No entries yet. Try recording an observation and its consequence.</td></tr>'}</tbody></table></div>`}
window.pwPassageLog=()=>{mode='log';nav();$('ppContent').innerHTML=`<div class="pwTidesKicker">PRACTICAL • RECORD WHAT HAPPENED</div><h2>Practice navigation logbook</h2><p class="pwTidesLead">Write a useful snapshot. State the time basis and position source, then record a decision if the facts have changed.</p>${art('logbook','Example log entries showing observations and decisions')}<p class="ppNote">Saved on this browser only; export a backup. This is a learning tool, not a statutory logbook. Maintain lookout and control before typing.</p><form class="ppForm" id="ppLogForm">${logFields.map(([id,label,type])=>`<label>${esc(label)}<input type="${type}" id="ppL_${id}" ${id==='basis'?'placeholder="e.g. UTC"':''}></label>`).join('')}</form><div class="ppToolbar"><button onclick="pwPassageAddLog()">SAVE LOG ENTRY</button><button onclick="pwPassageExportLog()">DOWNLOAD LOG (.csv)</button></div><p id="ppLogStatus" role="status"></p><div id="ppLogTable">${logTable()}</div>${actions('pwPassagePlan()','pwPassageQuiz()')}`;top()};
window.pwPassageAddLog=()=>{const row=Object.fromEntries(logFields.map(([id])=>[id,$('ppL_'+id).value.trim()]));if(['date','time','basis','position','source','action'].some(k=>!row[k])){$('ppLogStatus').textContent='Enter date, time, time basis, position, source and an observation or action before saving.';return}logs.push(row);const ok=save('pw-passage-log-v1',logs);$('ppLogTable').innerHTML=logTable();$('ppLogStatus').textContent=ok?'Entry saved in this browser.':'Entry added for this session. Storage unavailable; download a backup now.';$('ppLogForm').reset()};
function csv(v){let s=String(v??'');if(/^[\s]*[=+@-]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"'}
window.pwPassageExportLog=()=>{download('Helmlore-navigation-log.csv',logFields.map(f=>csv(f[1])).join(',')+'\r\n'+logs.map(r=>logFields.map(f=>csv(r[f[0]])).join(',')).join('\r\n'),'text/csv;charset=utf-8');$('ppLogStatus').textContent='Log download requested. Check your browser downloads.'};
window.pwPassageQuiz=()=>{mode='quiz';nav();$('ppContent').innerHTML=`<div class="pwTidesKicker">SELF-CHECK • ORIGINAL QUESTIONS</div><h2>Check your passage-planning decisions</h2><p class="pwTidesLead">15 questions. Answer all, then check the explanations.</p><form>${d.quiz.map((q,i)=>`<fieldset class="pwTidesQuestion"><legend>${i+1}. ${esc(q[0])}</legend>${q[1].map((_,j)=>(i+j)%3).map(j=>`<label><input type="radio" name="ppQ${i}" value="${j}"> ${esc(q[1][j])}</label>`).join('')}<p id="ppFeedback${i}"></p></fieldset>`).join('')}</form><div class="cwActions"><button onclick="pwPassageLog()">← LOGBOOK</button><button onclick="pwPassageCheckQuiz()">CHECK ANSWERS</button></div><p id="ppQuizResult" role="status"></p>`;top()};
window.pwPassageCheckQuiz=()=>{const choices=d.quiz.map((q,i)=>document.querySelector(`input[name="ppQ${i}"]:checked`));if(choices.some(c=>!c)){$('ppQuizResult').textContent='Answer all questions before checking. '+choices.filter(c=>!c).length+' remaining.';return}let score=0;d.quiz.forEach((q,i)=>{const ok=Number(choices[i].value)===q[2];if(ok)score++;$('ppFeedback'+i).textContent=(ok?'Correct. ':'Review: '+q[1][q[2]]+'. ')+q[3];$('ppFeedback'+i).className='feedback '+(ok?'correct':'incorrect')});$('ppQuizResult').textContent=`${score} / ${d.quiz.length} correct. Review the explanations and repeat any lesson you need.`};
function init(){nav();$('ppSources').innerHTML=d.sources.map(s=>`<a href="${esc(s[1])}" target="_blank" rel="noopener noreferrer">${esc(s[0])} ↗</a>`).join('');$('ppDialog').addEventListener('click',e=>{if(e.target===$('ppDialog'))$('ppDialog').close()})}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
