/* Self-contained recreational tides pathway; no modification to existing course state. */
(function(){
'use strict';
const lib=window.PW_TIDES_LIBRARY;
const key='pw-tides-reviewed-v1';
let reviewed=[];let selected=0;let mode='lesson';
try{const saved=JSON.parse(localStorage.getItem(key)||'[]');if(Array.isArray(saved))reviewed=saved.filter(n=>Number.isInteger(n)&&n>=0&&n<lib.lessons.length)}catch(_){}
const $=id=>document.getElementById(id);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function top(){const el=$('tidesPage');if(el)el.scrollIntoView({block:'start',behavior:'instant'})}
function nav(){ $('pwTidesProgress').textContent=reviewed.length+' / '+lib.lessons.length+' LESSONS REVIEWED';$('pwTidesLessonNav').innerHTML=lib.lessons.map((l,i)=>`<button type="button" class="${mode==='lesson'&&selected===i?'active ':''}${reviewed.includes(i)?'completed':''}" onclick="pwTidesLesson(${i})"><small>${String(i+1).padStart(2,'0')}</small> ${esc(l.title)}</button>`).join('')}
function lesson(i){selected=i;mode='lesson';const l=lib.lessons[i];$('pwTidesContent').innerHTML=`<div class="pwTidesKicker">LESSON ${String(i+1).padStart(2,'0')} / ${lib.lessons.length} • ${esc(l.subtitle)}</div><h2>${esc(l.title)}</h2><p class="pwTidesLead">${esc(l.lead)}</p><figure class="pwTidesScene"><img src="${esc(l.image)}" alt="${esc(l.alt)}" loading="lazy"><figcaption>Original Project Watch teaching scene; fictional setting.</figcaption></figure><details class="pwTidesTechnical"><summary>VIEW PRECISE TEACHING DIAGRAM</summary><img src="${esc(l.diagram)}" alt="${esc(l.title)} schematic teaching diagram" loading="lazy"><p>Schematic training diagram. Any figures shown are fictional examples, not navigation data.</p></details><div class="pwTidesPoints">${l.points.map((p,j)=>`<article><small>0${j+1}</small><h3>${esc(p.title)}</h3><p>${esc(p.text)}</p></article>`).join('')}</div><div class="pwTidesScenario"><b>PUT IT TO WORK</b><p>${esc(l.scenario)}</p></div><p class="pwTidesTakeaway"><b>Remember:</b> ${esc(l.takeaway)}</p><div class="pwTidesActions"><button type="button" onclick="pwTidesMark()">${reviewed.includes(i)?'REVIEWED ✓':'MARK REVIEWED ✓'}</button>${i<lib.lessons.length-1?`<button type="button" class="secondary" onclick="pwTidesLesson(${i+1})">NEXT LESSON →</button>`:'<button type="button" class="secondary" onclick="pwTidesShowWorkshop()">TRY WORKSHOPS →</button>'}</div>`;nav();top()}
window.pwTidesOpen=function(){if(typeof window.showModule==='function')window.showModule('tides');if($('moduleContextNo'))$('moduleContextNo').textContent='04';if($('moduleContextTitle'))$('moduleContextTitle').textContent='Tides, Heights & Streams';if($('moduleContextDesc'))$('moduleContextDesc').textContent='Eight visual lessons • height and stream workshops • knowledge check';lesson(selected)};
window.pwTidesLesson=lesson;
window.pwTidesMark=function(){if(!reviewed.includes(selected)){reviewed.push(selected);reviewed.sort((a,b)=>a-b);try{localStorage.setItem(key,JSON.stringify(reviewed))}catch(_){}}nav();const b=$('pwTidesContent').querySelector('.pwTidesActions button');if(b)b.textContent='REVIEWED ✓'};
window.pwTidesShowWorkshop=function(){mode='workshop';nav();$('pwTidesContent').innerHTML=`<div class="pwTidesKicker">PRACTISE • FICTIONAL NUMBERS</div><h2>Two tidal workshops</h2><p class="pwTidesLead">Change one input at a time and see the effect. These simple steady-water models do not predict conditions at a real location.</p><figure class="pwTidesScene"><img src="assets/tides/chart-datum.svg" alt="Chart datum and available depth diagram"><figcaption>Depth and height must use the same chart datum.</figcaption></figure><div class="pwTidesTools"><section><h3>01 • Water under the keel</h3><p>For a charted sounding below datum: available depth = sounding + tidal height.</p><div class="pwTidesFields"><label>Charted sounding (m)<input id="tideSounding" type="number" min="0" max="30" step="0.1" value="2.0" oninput="pwTidesCalculate()"></label><label>Tidal height (m)<input id="tideHeight" type="number" min="0" max="20" step="0.1" value="1.5" oninput="pwTidesCalculate()"></label><label>Boat draught (m)<input id="tideDraught" type="number" min="0" max="20" step="0.1" value="1.2" oninput="pwTidesCalculate()"></label><label>Chosen allowance (m)<input id="tideAllowance" type="number" min="0" max="10" step="0.1" value="0.5" oninput="pwTidesCalculate()"></label></div><div class="pwTidesResult" id="tideDepthResult" aria-live="polite"></div><small>Still-water training calculation. Actual clearance can be less because of weather, motion, squat, survey or local effects.</small></section><section><h3>02 • Stream drift</h3><p>Boat north through the water; a constant eastward stream carries it sideways.</p><div class="pwTidesFields"><label>Boat speed north (kn)<input id="tideBoatSpeed" type="number" min="0" max="40" step="0.1" value="4" oninput="pwTidesCalculate()"></label><label>Eastward stream (kn)<input id="tideStream" type="number" min="0" max="10" step="0.1" value="1" oninput="pwTidesCalculate()"></label><label>Elapsed time (hours)<input id="tideHours" type="number" min="0" max="12" step="0.25" value="1" oninput="pwTidesCalculate()"></label></div><div class="pwTidesResult" id="tideDriftResult" aria-live="polite"></div><small>Steady speed and stream; this is a simplified vector sketch, not a course to steer for a real passage.</small></section></div><div class="pwTidesActions"><button type="button" onclick="pwTidesShowQuiz()">KNOWLEDGE CHECK →</button><button type="button" class="secondary" onclick="pwTidesLesson(0)">REVISIT LESSONS</button></div>`;window.pwTidesCalculate();top()};
window.pwTidesCalculate=function(){const val=id=>Number($(id)?.value);let a=['tideSounding','tideHeight','tideDraught','tideAllowance','tideBoatSpeed','tideStream','tideHours'].map(val);if(a.some(n=>!Number.isFinite(n)||n<0)){$('tideDepthResult').textContent='Enter non-negative numbers in every field.';$('tideDriftResult').textContent='Enter non-negative numbers in every field.';return}const [s,h,d,m,b,c,t]=a;const depth=s+h,clear=depth-d,margin=clear-m;$('tideDepthResult').innerHTML=`Approximate depth <b>${depth.toFixed(1)} m</b> • clearance before allowance <b>${clear.toFixed(1)} m</b><br>After chosen allowance: <b>${margin.toFixed(1)} m</b> ${margin<0?'— allowance not met in this model':'— model allowance met'}`;$('tideDriftResult').innerHTML=`In ${t.toFixed(2)} h: <b>${(b*t).toFixed(2)} NM north</b> and <b>${(c*t).toFixed(2)} NM east</b> if heading stays north.`};
window.pwTidesShowQuiz=function(){mode='quiz';nav();$('pwTidesContent').innerHTML=`<div class="pwTidesKicker">SELF-CHECK • ORIGINAL QUESTIONS</div><h2>Check your tidal thinking</h2><p class="pwTidesLead">Twelve questions with explanations. No official qualification or exam result is claimed.</p><form id="pwTidesQuiz">${lib.quiz.map((q,i)=>`<fieldset class="pwTidesQuestion"><legend>${i+1}. ${esc(q.question)}</legend>${q.options.map((_,j)=>(j+i+1)%q.options.length).map(j=>`<label><input type="radio" name="q${i}" value="${j}"> ${esc(q.options[j])}</label>`).join('')}<p class="feedback" id="tideFeedback${i}"></p></fieldset>`).join('')}</form><div class="pwTidesActions"><button type="button" onclick="pwTidesCheckQuiz()">CHECK ANSWERS</button><button type="button" class="secondary" onclick="pwTidesShowWorkshop()">BACK TO WORKSHOPS</button></div><div id="pwTidesQuizResult" aria-live="polite"></div>`;top()};
window.pwTidesCheckQuiz=function(){let score=0;lib.quiz.forEach((q,i)=>{const chosen=document.querySelector(`input[name="q${i}"]:checked`);const ok=chosen&&Number(chosen.value)===q.answer;if(ok)score++;const box=$('tideFeedback'+i);box.textContent=(ok?'Correct. ':'Review: '+q.options[q.answer]+'. ')+q.explanation;box.className='feedback '+(ok?'correct':'incorrect')});$('pwTidesQuizResult').innerHTML=`<b>${score} / ${lib.quiz.length} correct</b><p>Review the explanations and revisit any lesson you need. This is independent practice.</p>`};
function init(){const hero=document.querySelector('.pwTidesHero img');if(hero){hero.src='assets/tides/scenes/passage-window-1.93.1.webp';hero.alt='Recreational cruiser approaching a sheltered harbour in late afternoon';}const sourceNote=document.querySelector('.pwTidesSources p');if(sourceNote)sourceNote.innerHTML='Teaching checked against UKHO, Met Office and RNLI guidance. The eight lesson scenes are original AI-generated Project Watch illustrations; precise schematic SVG diagrams are separate files in <code>assets/tides/</code>. All settings and data are fictional.';const links=$('pwTidesSourceLinks');if(links)links.innerHTML=lib.sources.map(s=>`<a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">${esc(s.label)} ↗</a>`).join('');nav()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
