const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),crypto=require('node:crypto').webcrypto;
const P=require('../js/navigation/chart-pack-core.js');
function store(){const maps=new Map();return {maps,open:async n=>{if(!maps.has(n))maps.set(n,new Map());const m=maps.get(n);return {match:async u=>m.get(typeof u==='string'?u:u.url)?.clone(),put:async(u,r)=>m.set(u,r.clone()),delete:async u=>m.delete(u),addAll:async urls=>{for(const r of urls)m.set(r.url,new Response('viewer'));}};},keys:async()=>[...maps.keys()],delete:async n=>maps.delete(n)};}
const digest=b=>require('node:crypto').createHash('sha256').update(b).digest('hex');
function manifest(){const b=Buffer.from('{"chart":true}');return {schema:'helmlore-chart-pack-v1',id:'test-v1',release:'test',bytes:b.length,files:[{path:'data/navigation/tile.json',bytes:b.length,sha256:digest(b)}]};}
async function previous(s){await (await s.open(P.META)).put(P.KEY,new Response(JSON.stringify({name:'old-chart',id:'old'})));await (await s.open('old-chart')).put('https://helmlore.com/data/navigation/tile.json',new Response('old'));}
test('Complete download verifies bytes and SHA256 before replacing active pointer',async()=>{const s=store();await previous(s);let progress;const m=manifest();const {record}=await P.install(m,{storage:s,base:'https://helmlore.com/',cryptoProvider:crypto,fetcher:async()=>new Response('{"chart":true}'),onProgress:p=>progress=p});assert.equal((await P.active(s)).name,record.name);assert.equal(progress.done,1);assert.equal(await (await (await s.open(record.name)).match('https://helmlore.com/data/navigation/tile.json')).text(),'{"chart":true}');assert(s.maps.has('old-chart'));});
test('Corrupt data rolls back; previously saved chart survives',async()=>{const s=store();await previous(s);await assert.rejects(P.install(manifest(),{storage:s,base:'https://helmlore.com/',cryptoProvider:crypto,fetcher:async()=>new Response('{"chart":fals}')}),/verification/);assert.equal((await P.active(s)).id,'old');assert.equal(s.maps.size,2);});
test('Cancellation never installs an incomplete pack',async()=>{const s=store();await previous(s);const c=new AbortController();c.abort();await assert.rejects(P.install(manifest(),{storage:s,base:'https://helmlore.com/',cryptoProvider:crypto,signal:c.signal,fetcher:async()=>{throw Error('must not fetch');}}),{name:'AbortError'});assert.equal((await P.active(s)).id,'old');assert.equal(s.maps.size,2);});
test('Storage failure leaves previous active pointer untouched',async()=>{const s=store();await previous(s);const open=s.open;s.open=async n=>{const c=await open(n);if(n.startsWith('helmlore-chart-pack-'))c.put=async()=>{throw Error('QuotaExceeded');};return c;};await assert.rejects(P.install(manifest(),{storage:s,base:'https://helmlore.com/',cryptoProvider:crypto,fetcher:async()=>new Response('{"chart":true}')}),/Quota/);assert.equal((await P.active(s)).id,'old');});
test('Rejects duplicate paths, traversal and wrong byte totals',()=>{for(const path of ['data/navigation/../bad.json','https://evil.test/data/navigation/a','data/navigation/a.json?x']){const m=manifest();m.files[0].path=path;assert.throws(()=>P.validate(m));}const m=manifest();m.files.push(m.files[0]);assert.throws(()=>P.validate(m));});
test('Real package inventory matches all bytes, hashes and 7456 chart tiles',()=>{const m=JSON.parse(fs.readFileSync('data/navigation/offline-chart-manifest.json'));P.validate(m);let tiles=0;for(const f of m.files){const b=fs.readFileSync(f.path);assert.equal(b.length,f.bytes,f.path);assert.equal(digest(b),f.sha256,f.path);if(/historical-tiles-2011-v1\/\d/.test(f.path))tiles++;}assert.equal(tiles,7456);for(const p of ['data/navigation/master-chart/published-release.json','data/navigation/master-chart/20261008-reviewed-v2/depiction-register.json','data/navigation/master-chart/20261008-reviewed-v2/tile-patches.json','data/navigation/master-chart/20261008-reviewed-v2/online-seamarks.json','data/marinas/uk-marinas.json'])assert(m.files.some(f=>f.path===p));});
test('Worker serves pinned chart offline, normalises version query and bypasses updates without intercepting accounts/APIs',async()=>{const handlers={},s=store();await previous(s);let network=0;vm.runInNewContext(fs.readFileSync('navigation-sw.js','utf8'),{URL,Request,Response,self:{location:{href:'https://helmlore.com/navigation-sw.js'},addEventListener:(n,f)=>handlers[n]=f},caches:s,fetch:async()=>{network++;throw Error('offline');}});let pending;function request(url){pending=null;handlers.fetch({request:new Request(url),respondWith:p=>pending=p});return pending;}assert.equal(await (await request('https://helmlore.com/data/navigation/tile.json?v=18')).text(),'old');assert.equal(network,0);assert.equal((await request('https://helmlore.com/data/navigation/missing.json')).status,503);for(const u of ['https://helmlore.com/login.html','https://tile.openstreetmap.org/1/1/1.png','https://helmlore.com/data/navigation/tile.json?chart-download=test'])assert.equal(request(u),null);});

test('Offline snapshot symbol renderer is loaded before the chart and cached with the viewer',()=>{const h=fs.readFileSync('navigation.html','utf8');assert(h.indexOf('snapshot-mark-symbols.js')<h.indexOf('chart-lab-20261007.js'));assert(fs.readFileSync('navigation-sw.js','utf8').includes('snapshot-mark-symbols.js'));});
test('Saved mark symbol renderer handles the actual snapshot records',async()=>{const b=JSON.parse(fs.readFileSync('data/navigation/master-chart/20261008-reviewed-v2/online-seamarks.json'));const d=b.gzip?JSON.parse(require('node:zlib').gunzipSync(Buffer.from(b.gzip,'base64'))):b;const ctx={window:{}};vm.runInNewContext(fs.readFileSync('js/navigation/snapshot-mark-symbols.js','utf8'),ctx);assert.equal(d.features.length,20177);for(const f of d.features){const symbol=ctx.window.HelmloreMarkSymbol(f);assert(symbol.startsWith('<svg'));assert(!symbol.includes('undefined'));}});

test('Local Leaflet integrity attributes match the installed renderer and stylesheet',()=>{const h=fs.readFileSync('navigation.html','utf8');for(const [,p,hash] of h.matchAll(/(?:src|href)="(js\/vendor\/leaflet\/[^"?]+)" integrity="sha256-([^"\s]+)"/g)){assert.equal(require('node:crypto').createHash('sha256').update(fs.readFileSync(p)).digest('base64'),hash,p);}});
