const test=require('node:test'),assert=require('node:assert/strict'),C=require('../js/navigation/logbook-core.js'),N=require('../js/navigation/core.js');
const clock=Date.UTC(2026,9,3,12,2),fix=(time,lat=54,lon=-3)=>({lat,lon,time,accuracy:5});
const snapshot=(time,more={})=>({mode:'gps',fix:fix(time),speed:7,course:90,route:[{lat:54,lon:-3},{lat:54,lon:-2.9},{lat:54.1,lon:-2.9}],target:1,...more});
test('Logs use clock boundaries and retain actual fix time without inventing missed fixes',()=>{const t=C.begin(snapshot(clock),'Passage',30,clock);assert.equal(t.nextAt,Date.UTC(2026,9,3,12,30));const due=t.nextAt;C.tick(t,snapshot(due-1000),due+1000);const e=t.entries.at(-1);assert.equal(e.scheduledAt,due);assert.equal(e.fixAt,due-1000);assert.equal(e.gap,false);C.tick(t,snapshot(due+3600000),due+3600000);const missed=t.entries.find(e=>e.scheduledAt===due+1800000);assert.equal(missed.gap,true);assert.equal(missed.lat,null);assert.equal(missed.sog,null);});
test('Remaining distance follows the active route, marina remains explicitly direct',()=>{const s=snapshot(clock);assert.ok(C.remaining(s)>N.distance(s.fix,s.route[1])/1852);assert.equal(C.remaining({...s,marina:s.route[1]}),N.distance(s.fix,s.route[1])/1852);assert.equal(C.remaining({...s,target:9}),null);});
test('GPS gaps split the track and distance does not bridge unavailable positions',()=>{const t=C.begin(snapshot(clock),'Passage',5,clock);C.tick(t,snapshot(clock+10000,{fix:fix(clock+10000,54.001,-3)}),clock+10000);assert.ok(t.distanceNM>0);const before=t.distanceNM;C.tick(t,snapshot(clock+20000,{fix:null}),clock+20000);C.tick(t,snapshot(clock+30000,{fix:fix(clock+30000,55,-3)}),clock+30000);assert.equal(t.distanceNM,before);assert.equal(t.distanceIncomplete,true);assert.notEqual(t.track[0].segment,t.track.at(-1).segment);});
test('Source changes end a trip without mixing simulated and real fixes',()=>{const t=C.begin(snapshot(clock),'GPS trip',30,clock);C.tick(t,snapshot(clock+1000,{mode:'demo'}),clock+1000);assert.equal(t.active,false);assert.equal(t.track.length,1);assert.equal(t.entries.at(-1).gap,true);assert.equal(t.entries.at(-1).lat,null);assert.throws(()=>C.begin(snapshot(clock,{mode:'explore'}),'No source',30,clock));assert.throws(()=>C.begin(snapshot(clock,{fix:fix(clock-20000)}),'Stale',30,clock));});
test('CSV preserves UTC timestamps, notes and missing values; stop is idempotent',()=>{const t=C.begin(snapshot(clock),'Trip',30,clock);t.entries.push(C.entry(t,snapshot(clock),clock,'manual','Wind, "fresh"\nnotes'));C.stop(t,snapshot(clock),clock+1000);const count=t.entries.length;C.stop(t,snapshot(clock),clock+2000);assert.equal(t.entries.length,count);const csv=C.csv(t);assert.ok(csv.includes('2026-10-03T12:02:00.000Z'));assert.ok(csv.includes('"Wind, ""fresh""\nnotes"'));});

test('Stationary GPS jitter does not accumulate fictional travelled distance',()=>{const t=C.begin(snapshot(clock),'Stationary',30,clock);for(let i=1;i<=50;i++)C.tick(t,snapshot(clock+i*1000,{fix:fix(clock+i*1000,54+(i%2?0.00001:0),-3)}),clock+i*1000);assert.equal(t.distanceNM,0);assert.ok(t.track.length<=3);});
