const assert=require('node:assert/strict'),N=require('../js/navigation/core.js');
const origin={lat:0,lon:0},east=N.destination(origin,90,1852);
assert(Math.abs(N.distance(origin,east)-1852)<0.001);
assert(Math.abs(N.bearing(origin,east)-90)<0.001);
assert(Math.abs(N.knots(1852/3600)-1)<1e-9);
assert(Math.abs(N.distance({lat:0,lon:179.99},{lat:0,lon:-179.99})-2223.9016)<0.1);
assert.equal(N.valid({lat:91,lon:0}),false);
assert.equal(N.coordinate(54.9999999,true),'55° 00.000′ N');
assert.deepEqual(N.motion({accuracy:5,time:10000,speed:null,heading:null},null),{speed:null,course:null,estimated:false});
assert.equal(N.motion({accuracy:5,time:10000,speed:0,heading:120},null).course,null);
assert.equal(N.motion({accuracy:500,time:10000,speed:3,heading:120},null).speed,null);
const previous={...origin,time:1000,accuracy:3};
const fix={...N.destination(origin,90,20),time:11000,accuracy:3,speed:null,heading:null};
const moving=N.motion(fix,previous);assert.equal(moving.estimated,true);assert(Math.abs(moving.speed-N.knots(2))<1e-6);assert.equal(moving.course,90);
assert.equal(N.motion({...fix,time:40000},previous).speed,null);
assert.equal(N.motion({...fix,lat:0,lon:0},previous).speed,null);
const route=N.gpx([{lat:1,lon:2,name:'<boat & "crew">'}],'route','Test & route');assert(route.includes('&lt;boat &amp; &quot;crew&quot;&gt;'));assert(!route.includes('<boat'));
const track=N.gpx([{lat:1,lon:2,time:1000,segment:1},{lat:1,lon:3,time:2000,segment:1},{lat:2,lon:4,time:3000,segment:2}],'track','Test');assert.equal((track.match(/<trkseg>/g)||[]).length,2);assert.equal((track.match(/<trkpt /g)||[]).length,3);
console.log('PASS: nautical miles, true bearings, dateline, coordinates, missing/poor GPS, motion estimation, escaped GPX and separate recording segments.');
