const {test}=require('node:test'),assert=require('node:assert/strict'),C=require('../js/navigation/weather-core.js');
const now=Date.UTC(2026,9,3,21,45),hour=Math.floor(now/3600000)*3600,b={south:54,north:56,west:-6,east:-3};
const rows=()=>Array.from({length:25},(_,i)=>({latitude:54+i/100,longitude:-4,hourly:{time:Array.from({length:73},(_,j)=>hour+j*3600),wind_speed_10m:Array(73).fill(12),ocean_current_velocity:Array(73).fill(null)}}));
test('Area grid remains inside the selected box; huge and date-line boxes are rejected',()=>{const ps=C.grid(b);assert.equal(ps.length,25);assert(ps.every(p=>p.lat>b.south&&p.lat<b.north&&p.lon>b.west&&p.lon<b.east));assert.throws(()=>C.grid({...b,east:180}));assert.throws(()=>C.grid({...b,west:179,east:-179}));});
test('Package starts at current model hour and covers the full next 72 hours, not three calendar days',()=>{const p=C.pack(b,rows(),rows(),'Irish Sea',now);assert.equal(p.end-p.start,72*3600);assert.equal(p.times.length,73);assert(C.valid(JSON.parse(JSON.stringify(p))));});
test('Absent marine feed preserves downloadable wind, missing values never become zero',()=>{const p=C.pack(b,rows(),null,'Wind only',now);assert.equal(p.marine.length,0);assert.equal(C.value(p.weather[0],'ocean_current_velocity',hour),null);assert.equal(C.value(p.weather[0],'wind_speed_10m',hour+100),null);assert(C.valid(p));});
test('Partial future coverage uses the actual model horizon, malformed and expired responses are rejected',()=>{const r=rows();r[3].hourly.time=r[3].hourly.time.slice(0,49);const p=C.pack(b,r,[],'Limited',now);assert.equal(p.end-p.start,48*3600);assert.throws(()=>C.pack(b,r.slice(1),[],'Broken',now));assert.throws(()=>C.pack(b,r,[],'Past',now+10*86400000));p.times.push(p.times[0]);assert(!C.valid(p));});
test('Old, past and expired model data is visibly distinguished from a current download',()=>{const p=C.pack(b,rows(),rows(),'Test',now);assert.equal(C.state(p,p.start,now),'FORECAST');assert.equal(C.state(p,p.start,now+3600000),'PAST FORECAST');assert.equal(C.state(p,p.end,now+13*3600000),'OLDER DOWNLOAD');assert.equal(C.state(p,p.end,(p.end+1)*1000),'EXPIRED');});


test('Sea-only sampling excludes UK land and rejects inland-only boxes; small sea packages survive storage',()=>{C.setLand(require('../data/weather/land-mask.json'));assert.equal(C.isSea({lat:53.48,lon:-2.24}),false);assert.equal(C.isSea({lat:54.5,lon:-4}),true);const points=C.seaGrid({south:53,north:56,west:-8,east:-1});assert.equal(points.length,25);assert(points.every(C.isSea));assert.throws(()=>C.seaGrid({south:53.4,north:53.6,west:-2.4,east:-2.1}),/No sea/);assert(C.valid(C.pack(b,rows().slice(0,1),[],'Small',now,points.slice(0,1))));});
