const {test}=require('node:test'),assert=require('node:assert/strict'),F=require('../js/navigation/weather-console.js');
function harness(saved){const els={},events={},storage=new Map(saved?[['helmlore-weather-controls-v1',JSON.stringify(saved)]]:[]),style={};let renders=0;
const el=id=>els[id]||(els[id]={hidden:['weatherSymbolKey','weatherTimeline'].includes(id),checked:['windLayer','tideLayer'].includes(id),attrs:{},listeners:{},small:{textContent:''},click(){this.onclick?.()},setAttribute(k,v){this.attrs[k]=v},querySelector(){return this.small},addEventListener(n,fn){this.listeners[n]=fn},dispatchEvent(e){this.onchange?.();this.listeners[e.type]?.()},getBoundingClientRect(){return id==='navigationConsole'?{width:1024,height:el('weatherLayerControls').hidden?158:214}:{width:900,height:220}}});
for(const id of ['windLayer','currentLayer','waveLayer','tideLayer'])el(id).onchange=()=>renders++;
const doc={getElementById:el,body:{dataset:{dock:'bottom'},style:{setProperty:(k,v)=>style[k]=v}}},win={localStorage:{getItem:k=>storage.get(k),setItem:(k,v)=>storage.set(k,v)},Event:class{constructor(type){this.type=type}},addEventListener:(n,fn)=>events[n]=fn};
el('closeWeatherTimeline').onclick=()=>el('weatherTimeline').hidden=true;const api=F.start(win,doc);return {el,doc,win,api,style,events,storage,renders:()=>renders};}
test('Layer buttons operate the same checkboxes as the menu, keeping their state in sync',()=>{const h=harness();assert.equal(h.el('windLayerButton').attrs['aria-pressed'],'true');h.el('currentLayerButton').onclick();assert(h.el('currentLayer').checked);assert.equal(h.el('currentLayerButton').small.textContent,'On');assert.equal(h.renders(),2);h.el('currentLayer').checked=false;h.el('currentLayer').dispatchEvent(new h.win.Event('change'));assert.equal(h.el('currentLayerButton').attrs['aria-pressed'],'false');});
test('Hide all clears every weather layer in one render and survives reload',()=>{const h=harness();h.el('weatherTimeline').hidden=false;h.el('weatherKeyToggle').onclick();h.el('clearWeatherLayers').onclick();assert(h.el('weatherTimeline').hidden);assert(h.el('weatherSymbolKey').hidden);for(const id of ['windLayer','currentLayer','waveLayer','tideLayer']){assert.equal(h.el(id).checked,false);assert.equal(h.el(id+'Button').small.textContent,'Off');}assert.equal(h.renders(),2);const r=harness(JSON.parse(h.storage.get('helmlore-weather-controls-v1')));assert.equal(r.el('windLayer').checked,false);assert.equal(r.el('tideLayer').checked,false);});
test('Controls and symbol key are independently hideable, with weather access retained',()=>{const h=harness();assert(h.el('weatherSymbolKey').hidden);h.el('weatherKeyToggle').onclick();assert(!h.el('weatherSymbolKey').hidden);h.el('weatherControlsToggle').onclick();assert(h.el('weatherLayerControls').hidden);assert(h.el('weatherSymbolKey').hidden);assert.equal(h.el('weatherControlsToggle').attrs['aria-expanded'],'false');assert.equal(h.style['--bar-bottom'],'158px');assert(!h.el('reopenWeatherTimeline').hidden);const r=harness(JSON.parse(h.storage.get('helmlore-weather-controls-v1')));assert(r.el('weatherLayerControls').hidden);});
test('Dock changes reserve the full combined console extent on exactly one edge',()=>{const h=harness();for(const dock of ['top','bottom','left','right']){h.doc.body.dataset.dock=dock;h.events['navigation-dock-changed']();for(const edge of ['top','bottom','left','right'])assert.equal(h.style['--bar-'+edge],edge===dock?(['left','right'].includes(dock)?'1024px':'214px'):'0px');}h.el('weatherTimeline').hidden=false;h.api.measure();assert.equal(h.style['--timeline-height'],'220px');h.el('weatherTimeline').hidden=true;h.api.measure();assert.equal(h.style['--timeline-height'],'0px');});
