from pathlib import Path
import json,math,html
R=Path(__file__).resolve().parents[1]; A=R/'assets/passage'; A.mkdir(exist_ok=True)
lessons=[
('Start with a trip you can safely make','appraisal','A passage plan is your answer to: where are we going, can we do it safely, and what will we do if things change?', [('Match the trip to the boat','Check seaworthiness, range, draught, equipment and the kind of conditions the boat can handle.'),('Match the trip to the crew','Consider experience, fatigue, seasickness and whether someone else can take over. A shorter sheltered trip may be the better choice.'),('Keep the plan proportionate','Even a short outing needs planning. A longer or exposed trip needs more detail. Planning is a continuing process, not a form to complete once.')], 'A two-hour coastal outing with a novice crew may be unsuitable if the return is exposed to worsening wind. Change the destination or postpone.', 'Choose a suitable trip before choosing a departure time.'),
('Gather the information before drawing a route','appraisal','Use current information, check its date, and write down the assumptions that could change.', [('Read the right sources','Use suitable current charts, harbour information, pilot books, notices and navigation warnings. Inspect an electronic route at a useful detailed scale.'),('Check weather and sea state','Look at wind direction and strength, gusts, waves, visibility and the trend for the return journey. Wind against tide can make conditions worse.'),('Check local constraints','Confirm access, berth availability, tidal gates, lock or bridge operation and local rules. Identify the forecast and tide time zones: UTC and BST differ by one hour.')], 'An arrival at 14:00 BST is 13:00 UTC. A gate time copied without its time basis can leave you an hour late.', 'Current information and a clear time basis underpin the plan.'),
('Plan the whole route, berth to berth','route','A route includes leaving the harbour, the open-water legs and the final approach.', [('Keep clear of hazards','Choose waypoints with a considered safety margin from shoals, rocks and other dangers. A waypoint is a reference point, not proof that the line to it is safe.'),('Inspect every leg','Check the complete corridor between waypoints, including traffic, prohibited areas and potential drift. Auto-routing suggestions need independent inspection.'),('Prepare the pilotage','Write the arrival sequence before you leave: marks, transits, channel directions, speed restrictions and a place to wait or turn around.')], 'The fictional blue route bends around East Island. The dashed direct line crosses the island: a straight line to the destination is not a navigable route.', 'Check the water between the waypoints, not just the waypoint positions.'),
('Use tides to choose an arrival window','depth','Height tells you about depth; stream tells you about movement. Both can constrain your timing.', [('Calculate available depth','Where depth and tide height use the same chart datum, available depth = charted depth + tide height. Subtract draught to find static clearance.'),('Allow for uncertainty','Account for waves, squat where relevant, survey quality, loading and tide prediction uncertainty. Choose a suitable margin for this boat and location.'),('Work backwards from a gate','Identify when depth or access is sufficient, allow for travel and waiting, and review the plan if delayed. Do not rush an unsafe approach to catch a gate.')], 'Fictional sill: 0.8 m charted depth + 2.0 m tide = 2.8 m water. With 1.6 m draught, static clearance is 1.2 m before other allowances. These are invented teaching figures.', 'A tidal gate is a constraint to respect, not a deadline to chase.'),
('Estimate leg times and a realistic ETA','timing','Use expected speed over ground for travel time. Through-water speed alone does not include the stream.', [('Calculate each leg','Time in hours = distance in nautical miles ÷ expected speed over ground in knots. Allow separately for harbour manoeuvres and waiting.'),('Make the uncertainty visible','Plan a reasonable range of arrival times. Slower progress can affect tide, fuel, daylight and the conditions at the destination.'),('Recalculate underway','Compare observed progress with the estimate. An ETA is a forecast to update, not an appointment the boat must keep.')], 'Teaching legs of 6 NM and 4 NM at 5 kn take 72 and 48 minutes. Add 30 minutes for manoeuvres and waiting: 2 h 30 min. Depart 09:00, estimate arrival 11:30, using one stated time basis.', 'Distance ÷ speed over ground gives time; delays need their own allowance.'),
('Plan endurance and keep a reserve','fuel','Know how long the boat can operate, and preserve options if the trip becomes longer.', [('Use evidence from your boat','Estimate fuel burn at the planned operating conditions from reliable measurements or appropriate manufacturer data. Include auxiliary use and other consumers.'),('Include the alternative','Allow for manoeuvring, delays, a diversion and a reserve appropriate to the circumstances. There is no single reserve percentage suitable for every voyage.'),('Verify usable fuel','Check levels, usable capacity, tank selection and fuel condition. For sailing boats also consider the possible need to motor. Check water, food, power and crew endurance.')], 'At an assumed 8 L/h, 2.5 h uses 20 L. A one-hour diversion adds 8 L and a chosen illustrative reserve adds 10 L: 38 L total. The 10 L is an example, not a universal rule.', 'Plan for the trip changing, not only for the shortest route.'),
('Choose alternatives and decision points','alternatives','Decide what would make you delay, turn back or divert while there is still room to do it.', [('Name a usable alternative','A nearby harbour is not automatically a refuge. Check its approach, depth, shelter for the forecast direction and whether entry will be possible.'),('Set triggers in advance','Examples include worsening visibility, crew illness, an equipment fault or missing a safe entry window. Define limits suitable for this boat, crew and passage.'),('Keep a way out','Identify where you can wait, return or divert before committing to a restricted approach. Review the consequences of an engine or navigation failure.')], 'If the arrival window is missed, the plan calls for a checked waiting area or a suitable alternative. Entering with insufficient clearance is not an acceptable shortcut.', 'Prepare the alternative before you need it.'),
('Brief the crew and tell someone ashore','briefing','Make the plan understandable to the people who may need to help you.', [('Explain the journey','Cover destination, timing, likely conditions, roles and when you might change the plan. Show the crew the arrival sketch and safety equipment.'),('Prepare for the skipper being unavailable','Someone should know how to stop or control the boat, call for help and give its position. Confirm the available communication equipment.'),('Leave a shore plan','Tell a responsible person the boat, people aboard, route, expected return or arrival and what to do if concerned. Update them when plans change and close the plan on arrival.')], 'If you divert, tell the shore contact when it is safe to do so. An unchanged expected-return message can cause avoidable concern.', 'A shared plan works better than a plan only the skipper understands.'),
('Keep a log that helps you navigate','logbook','The passage plan records your intentions. The navigation log records observations, decisions and what actually happened.', [('Record a useful snapshot','Include date and time basis, position and source, heading or course with reference, COG/SOG where useful, weather, depth with reference and relevant machinery or fuel observations.'),('Distinguish evidence from estimates','Label a visual fix, GPS fix, DR or EP clearly. Record changes of course, incidents, reasons for decisions and the revised ETA.'),('Keep entries timely and safe','Use an interval suited to speed, hazards and workload. Record significant events. Maintain lookout and control first; do not become absorbed in typing.')], '10:00 UTC — GPS fix cross-checked by transit; SOG 4 kn instead of planned 5 kn; crew seasick. Decision: reduce exposure, review diversion and update ETA. A position alone would not explain the decision.', 'Record enough to reconstruct your navigation and explain your decisions.'),
('Monitor, change the plan and close the passage','monitoring','Keep asking whether the original assumptions still hold, then finish with a useful record.', [('Compare plan with reality','Monitor position independently, progress, depths, weather, traffic, fuel and crew condition. A route drawn earlier does not guarantee safe water now.'),('Act on differences','If circumstances change, evaluate the remaining route and alternatives. Record the decision, brief the crew and update the shore contact when appropriate.'),('Close and learn','Record arrival, secure the boat, tell the shore contact and note defects or lessons. Keep a backup of the log and improve the next plan.')], 'A delay and worsening sea state invalidate the intended arrival. The skipper selects a checked alternative, updates the crew and shore contact, and records the reason.', 'A good plan changes when the evidence changes.')]
quiz=[
('What should determine the detail of a passage plan?',['The boat, crew, route and risks','The length of the form','Only the destination'],0,'Keep planning proportionate to the proposed trip.'),
('Does a short local outing need planning?',['Yes, proportionate to its risks','No, if land is visible','Only at night'],0,'Short trips can still involve weather, hazards and access constraints.'),
('What must you inspect after an automatic route is suggested?',['Every leg and its surrounding hazards at a suitable chart scale','Only its total distance','Only its arrival time'],0,'Automation does not establish that the proposed corridor is safe.'),
('What speed is used for estimated travel time?',['Expected speed over ground','Maximum engine speed','Speed through water without considering current'],0,'Travel time depends on progress over the ground.'),
('How long is 6 NM at 5 kn over ground?',['72 minutes','50 minutes','30 minutes'],0,'6 ÷ 5 hours equals 1.2 hours or 72 minutes.'),
('Why must a tide prediction’s time basis be checked?',['UTC and local summer time can differ','Tide times are always local','A clock setting never affects planning'],0,'Identify time zone, date and daylight-saving status.'),
('Depth 0.8 m plus tide 2.0 m, with draught 1.6 m, gives what static clearance?',['1.2 m before allowances','2.8 m clearance','0.4 m before allowances'],0,'0.8 + 2.0 − 1.6 = 1.2 m. Check matching datums and uncertainty.'),
('What makes a harbour a suitable alternative?',['Checked access and shelter for the expected conditions','Being the nearest name on the chart','Having a marina website'],0,'Depth, conditions, approach and availability matter.'),
('What do you do if a safe tidal-entry window is missed?',['Reassess waiting or diversion','Enter anyway to keep the ETA','Increase speed regardless of hazards'],0,'Do not chase a gate at the expense of safety.'),
('What should a fuel estimate include?',['Expected use, delays or diversion and a suitable reserve','Only the shortest route','A universal percentage for every boat'],0,'Use realistic boat-specific information and preserve alternatives.'),
('What is the difference between a plan and a log?',['The plan states intentions; the log records reality','They are interchangeable','The log is only for engine hours'],0,'Use the log to compare actual progress and decisions with intentions.'),
('What should accompany a logged position?',['Time and the position source','Only the destination','Only engine RPM'],0,'The source distinguishes an observation from DR or EP.'),
('How often should you log observations?',['As appropriate to hazards, speed and workload, and at significant events','Exactly once an hour on every voyage','Only on arrival'],0,'Choose an interval that supports safe monitoring.'),
('What should happen after a diversion?',['Replan, brief the crew and update the shore contact when safe','Keep the old ETA unchanged','Erase the original observations'],0,'Record the reason and communicate the change.'),
('What takes priority over entering a log on a screen?',['Lookout and safe control of the boat','Completing all text fields','Making the entry look tidy'],0,'A log supports navigation and must not distract from it.')]
data={'lessons':[dict(id=f'pp{i+1}',title=l[0],art=l[1],lead=l[2],points=l[3],example=l[4],remember=l[5]) for i,l in enumerate(lessons)],'quiz':quiz,'sources':[['RYA — recreational passage planning','https://www.rya.org.uk/water-safety/passage-planning-and-navigation/passage-planning/'],['MCA — MGN 599 Amendment 1, section 7','https://www.gov.uk/government/publications/mgn-599-m-amendment-1-m-pleasure-vessels-regulations-and-exemptions-guidance-and-best-practice-advice/mgn-599-m-amendment-1m-pleasure-vessels-regulations-and-exemptions-guidance-and-best-practice-advice'],['RNLI — boating preparation and crew briefing','https://rnli.org/water-safety/choose-your-activity/yacht-sailing-and-motorboating/enjoy-the-sea-trouble-free'],['IMO — voyage planning framework A.893(21)','https://wwwcdn.imo.org/localresources/en/KnowledgeCentre/IndexofIMOResolutions/AssemblyDocuments/A.893(21).pdf']]}
(R/'libraries/project-watch/passage-1.97.0.js').write_text('/* Original recreational teaching and question bank. Reviewed 29 September 2026. */\nwindow.PW_PASSAGE='+json.dumps(data,ensure_ascii=False,indent=2)+';\n')
# Original editorial teaching plates with ample labelled whitespace and precise worked figures.
def plate(name,title,subtitle,body):
 s=f'<svg xmlns="http://www.w3.org/2000/svg" width="1440" height="860" viewBox="0 0 1440 860"><rect width="1440" height="860" fill="#f4f1e7"/><g font-family="Arial,Helvetica,sans-serif" fill="#173d4b"><text x="70" y="58" font-size="15" letter-spacing="3">HELMLORE • PASSAGE PLANNING</text><text x="70" y="115" font-size="36" font-weight="700">{title}</text><text x="70" y="155" font-size="21" fill="#56717a">{subtitle}</text>{body}<path d="M70 788H1370" stroke="#b4c3bd"/><text x="70" y="824" font-size="16">ORIGINAL TEACHING VISUAL • FICTIONAL EXAMPLES • NOT FOR NAVIGATION</text></g></svg>'
 (A/(name+'.svg')).write_text(s)
def tx(x,y,t,size=24,col='#173d4b'):return f'<text x="{x}" y="{y}" font-size="{size}" fill="{col}">{html.escape(t)}</text>'
def card(x,y,w,h,title,rows,color='#e5eeea'):
 return f'<rect x="{x}" y="{y}" width="{w}" height="{h}" rx="18" fill="{color}" stroke="#9fb8b5"/>'+tx(x+28,y+46,title,26)+''.join(tx(x+28,y+92+i*38,t,21) for i,t in enumerate(rows))
plate('appraisal','Make the trip fit the boat and crew','Four questions to resolve before committing to a departure.',card(70,220,620,225,'THE BOAT',['Seaworthy • suitable equipment','Draught • fuel • range • power'])+card(750,220,620,225,'THE PEOPLE',['Experience • rest • confidence','Clothing • health • shared roles'])+card(70,485,620,225,'THE CONDITIONS',['Wind • waves • visibility • trend','Tide • daylight • safe access'])+card(750,485,620,225,'THE OPTIONS',['Suitable destination and alternative','Delay • shorten • return • divert']))
plate('depth','Depth is more than a tide time','A fictional harbour sill, using a single chart datum.',f'<rect x="80" y="215" width="780" height="390" rx="15" fill="#dceff0"/><path d="M80 605H860V710H80Z" fill="#d5c598"/><path d="M80 493.57H860" stroke="#947653" stroke-dasharray="9 9" stroke-width="3"/>'+tx(105,482,'Chart datum',21)+f'<path d="M170 215V493.57M158 215H182M158 493.57H182M170 493.57V605M158 605H182" stroke="#237e96" stroke-width="4"/>'+tx(205,310,'2.0 m tide above datum')+tx(205,568,'0.8 m charted depth')+'<path d="M455 215 L740 215 L700 310 L500 310 Z" fill="#173d4b"/><path d="M610 310V437.86" stroke="#173d4b" stroke-width="18"/><path d="M585 437.86H635" stroke="#173d4b" stroke-width="10"/>'+tx(635,400,'1.6 m draught',21)+tx(475,540,'1.2 m static clearance',23,'#18795c')+card(910,230,460,445,'THE CALCULATION',['0.8 + 2.0 = 2.8 m water','2.8 − 1.6 = 1.2 m clearance','','Before waves, squat and','other uncertainty allowances.','','Check matching datums.']) )
plate('timing','Turn distance into a realistic ETA','Teaching example: constant 5 kn speed over ground; one stated time basis.',card(70,220,395,225,'LEG 1 • 6 NM',['6 ÷ 5 = 1.2 hours','72 minutes'])+card(520,220,395,225,'LEG 2 • 4 NM',['4 ÷ 5 = 0.8 hours','48 minutes'])+card(970,220,400,225,'OTHER TIME',['Manoeuvres and waiting','30 minutes'])+f'<rect x="70" y="500" width="1300" height="185" rx="18" fill="#173d4b"/>'+tx(105,553,'09:00 departure  +  2 h 30 min  =  11:30 estimated arrival',30,'#fff')+tx(105,610,'Recheck tide, daylight and weather if progress is slower.',24,'#d5eeea')+tx(105,652,'An ETA is an estimate to update.',21,'#d5eeea'))
plate('fuel','Preserve your options with endurance','Illustrative fuel calculation; use evidence from your own boat.',card(70,230,400,350,'EXPECTED TRIP',['2.5 hours × 8 L/hour','20 L','','Includes assumed operating','time for this example.'])+card(520,230,400,350,'DIVERSION',['1 hour × 8 L/hour','8 L','','Allow for a checked','alternative destination.'])+card(970,230,400,350,'CHOSEN RESERVE',['Illustrative allowance','10 L','','Not a universal rule;','choose for the circumstances.'])+tx(90,675,'20 + 8 + 10 = 38 litres needed in this example',34,'#167558'))
plate('alternatives','Decide before the options narrow','Example triggers: choose suitable limits for the boat, crew and location.',card(70,220,620,225,'BEFORE DEPARTURE',['Forecast or boat not suitable?','Delay or select a different trip.'])+card(750,220,620,225,'WHILE STILL IN OPEN WATER',['Crew illness or worsening conditions?','Review return or checked refuge.'])+card(70,485,620,225,'BEFORE A RESTRICTED APPROACH',['Gate missed or clearance uncertain?','Use a checked waiting place or divert.'])+card(750,485,620,225,'AFTER A CHANGE',['Recalculate • brief • record','Update the shore contact when safe.']))
plate('briefing','Make the plan a shared plan','The crew and a responsible person ashore need different useful information.',card(70,220,620,450,'ON BOARD',['Where we are going and likely conditions','Crew roles and who can take over','Lifejackets and safety equipment','How to call for help and give position','What would make us change the plan'])+card(750,220,620,450,'ASHORE',['Boat identity and people aboard','Route and expected arrival or return','Contact details and alternative plans','What to do if concerned','Update changes; confirm safe arrival']))
rows=[('09:00','Departure','Boat and crew checks complete'),('10:00','Position / progress','GPS cross-check; SOG lower than planned'),('10:10','Decision','Crew unwell; choose checked alternative'),('10:15','Communication','Crew briefed; shore contact updated'),('11:05','Arrival','Secured; close plan; record defect')]
b='<rect x="70" y="220" width="1300" height="490" rx="15" fill="#fff" stroke="#a3b9b9"/>'+tx(100,263,'TIME UTC',18)+tx(290,263,'ENTRY TYPE',18)+tx(610,263,'OBSERVATION / ACTION',18)
for i,(a,c,e) in enumerate(rows):
 y=315+i*78;b+=f'<path d="M90 {y-30}H1350" stroke="#d4dfdb"/>'+tx(100,y,a,24)+tx(290,y,c,23)+tx(610,y,e,21)
plate('logbook','Record reality, not just your intentions','An original example navigation log. Never let logging interrupt lookout.',b)
plate('monitoring','Compare the plan with what you observe','Use changes as reasons to reassess, not reasons to force the original plan.',card(70,220,620,450,'PLANNED',['Expected progress and arrival window','Suitable forecast and crew condition','Fuel for route, diversion and reserve','Checked approach and alternative'])+card(750,220,620,450,'OBSERVED → ACTION',['Slower speed → revised ETA and gate','Worsening weather → review exposure','Crew illness → review workload and route','Unsafe entry → wait safely or divert']))
# Route plate: reuse our original chart; exact graticule remains untouched.
s=(R/'assets/chartwork/overview.svg').read_text();sc=1210/math.radians(20/60);merc=lambda lat:math.log(math.tan(math.pi/4+math.radians(lat)/2))
def xy(a,b):return 75+sc*math.radians((20-b)/60),145+sc*(merc(50+10/60)-merc(50+a/60))
pts=[(4,10),(6.1,7.8),(6.1,1.1),(4,1.0)]; ov='<g font-family="Arial">'
coords=[xy(*p) for p in pts]
ov+='<polyline points="'+' '.join(f'{x:.2f},{y:.2f}' for x,y in coords)+'" fill="none" stroke="#116e97" stroke-width="7"/>'
for i,(x,y) in enumerate(coords):ov+=f'<circle cx="{x}" cy="{y}" r="10" fill="#fff" stroke="#116e97" stroke-width="4"/>'+tx(x+(-110 if i==3 else 14),y-16,['START','WP1','WP2','FINISH'][i],22,'#116e97')
x,y=coords[0];u,v=coords[-1];ov+=f'<line x1="{x}" y1="{y}" x2="{u}" y2="{v}" stroke="#b45560" stroke-width="4" stroke-dasharray="12 9"/>'+tx(765,757,'Direct line crosses land',22,'#b45560')+'</g>'
s=s.replace('</svg>',ov+'</svg>');(A/'route.svg').write_text(s)
