from pathlib import Path
import json,html,math
R=Path(__file__).resolve().parents[1];A=R/'assets/diesel';A.mkdir(exist_ok=True)
lessons=[
('Meet your engine','overview','A small marine diesel needs clean fuel, air, lubrication, cooling and enough electrical power to start.',[
('Start with its identity','Find the engine model, serial number and gearbox model. Obtain the correct manuals: engines that look similar can have different pumps, filters and service procedures.'),('Locate the owner’s checks','Use your manual to find the dipstick, oil filler, fuel filters, coolant check point, raw-water strainer and pump, belt, battery isolation and stop control.'),('Learn the boundaries','The lessons explain a typical four-stroke inboard diesel. Mechanical injection is our fuel-path example; common-rail engines have different controls and high-pressure precautions.')], 'A four-cylinder Volvo Penta and a four-cylinder Beta share basic principles. Their component locations, fluids and service instructions are not interchangeable.','Know what each component does before trying to service it.'),
('How a four-stroke diesel works','four-stroke','Air goes in, gets hot under compression, fuel burns, and exhaust goes out. Four piston strokes make one complete cycle.',[
('Intake and compression','The intake valve opens as the piston moves down and draws in air. Both valves then close; the rising piston compresses and heats that air.'),('Power and exhaust','Fuel is injected near the end of compression and ignites in the hot air. Expanding gas pushes the piston down. The exhaust valve opens for the upward exhaust stroke.'),('Starting is different from running','The starter turns the engine initially. A diesel uses compression ignition, not a petrol-style spark plug. Glow plugs or other starting aids are model-dependent; follow their instructions.')], 'The cycle takes two crankshaft revolutions. Four cylinders repeat it at different times to produce more even power.','Air + compression + correctly delivered fuel = combustion.'),
('Before starting: a calm check','checks','Check with the engine stopped and cool, then keep hands and clothing clear when it runs.',[
('Fluids and supply','Check engine oil, coolant and gearbox oil using the specified methods. Confirm usable fuel, the required fuel valve position, and an open cooling seacock for normal starting afloat.'),('Look, smell and inspect','Look for fresh fuel, oil or coolant leaks; check the bilge, hoses, clamps and belt condition. Inspect the raw-water strainer safely. Close its seacock before opening where flooding is possible, reseal and reopen before running.'),('Prepare the boat and crew','Ventilate, secure the boat, confirm neutral, ensure the propeller area is clear and keep people away from rotating parts. Follow the manual’s start procedure. Check cooling discharge and instruments after starting; a dry exhaust or continuing alarm needs prompt action.')], 'A loose strainer lid can draw air even with the seacock open. After reassembly, check for a good seal, leaks and restored cooling flow.','Oil, coolant, fuel, seawater supply and a clear engine space.'),
('Follow the fuel from tank to cylinder','fuel','There is a low-pressure supply side and a high-pressure injection side. They do different jobs.',[
('Supply and clean','In our mechanical-injection example, fuel passes from tank and shutoff valve through a primary filter/water separator, lift pump and engine-mounted fine filter.'),('Meter and inject','The injection pump delivers timed high-pressure fuel through rigid lines to injectors in the cylinder head. Modern common-rail systems use a rail and electronically controlled injectors.'),('Return and protect','Surplus fuel returns to the tank in this example. Actual routing varies. Never search for a pressure leak with your hand, loosen high-pressure lines to bleed, or dismantle injectors as a beginner. Injection injuries require urgent medical attention.')], 'If the engine loses power after rough water, disturbed tank contamination may restrict the filters. That is a possibility to investigate, not a diagnosis.','Clean the fuel before it reaches the expensive injection equipment.'),
('Filters, water and air in the fuel','filters','A separator removes water and particles; a fine filter protects the injection system. Air in the supply can stop the engine.',[
('Inspect the separator','Water collects low in a suitable separator. Follow its maker’s method for inspection and draining into a container with the engine stopped. Some units have a metal bowl or sensor rather than a clear bowl.'),('Change the right element','Use the specified element and filtration rating. Contain spills, keep connections clean, check old seals have been removed, fit the correct new seals and follow the tightening instructions. Do not pour unfiltered fuel into a clean outlet.'),('Prime only as instructed','Filter changes or an empty tank may introduce air. Some engines self-prime; others use a hand pump and specified low-pressure bleed points. Follow the exact manual. Recheck for leakage and dependable running before departure.')], 'An engine starts briefly after a filter change, then stops. First consider incomplete priming or an air leak at the new seal; do not start undoing injector pipes.','Water and air do not belong in the fuel supply.'),
('Diesel bug: recognise and prevent it','diesel-bug','Microbes can grow where water and diesel meet. Their debris can block filters, but dark sludge alone does not prove diesel bug.',[
('Recognise the clues','Recurring blocked filters, slime and water contamination justify investigation. Dirt, corrosion products, aged fuel and wax can also cause restrictions. A fuel sample or specialist testing helps distinguish the cause.'),('Remove the conditions','Buy fuel from a reliable source, inspect filler seals and vents, keep water out, check the separator and manage fuel age. Tank inspection and removal of accumulated water may require a competent specialist.'),('Treat the whole problem','A suitable approved biocide may be part of a confirmed treatment plan, with correct compatibility and dosage. Killing microbes does not remove sludge or dead biomass; tank cleaning, fuel treatment and filter replacement may still be needed.')], 'A new filter blocks again soon after treatment. Debris may still be reaching it. Repeatedly adding more chemical is not a substitute for investigating and cleaning the contaminated system.','Prevent water ingress; investigate repeated contamination.'),
('Cooling: two separate water circuits','cooling','On a heat-exchanger-cooled engine, engine coolant and seawater exchange heat while staying separate.',[
('Closed coolant circuit','A circulation pump moves the specified coolant through the engine. A thermostat controls temperature and flow to the heat exchanger; a bypass may circulate coolant during warm-up. Check level only by the manual’s safe cool-engine method.'),('Open raw-water circuit','Seawater enters through the hull seacock and strainer, passes through the raw-water pump and heat exchanger, then commonly joins the wet exhaust. Gearbox coolers and anti-siphon arrangements may also be fitted; their order is installation-specific.'),('Watch for lost cooling','A shut seacock, blocked strainer, air leak, damaged impeller or fouled exchanger can reduce cooling. No normal discharge, steam or a rising temperature needs prompt attention. Never remove a hot pressurised coolant cap. Running ashore requires an approved raw-water supply; do not run this cooling system dry.')], 'The exhaust suddenly sounds hollow and dry. Treat that as a possible raw-water supply failure; do not wait for the temperature alarm before responding.','Coolant cools the engine; seawater carries the heat away.'),
('Raw-water pump and impeller','impeller','A flexible rubber impeller moves raw water. Its position and drive depend on the engine: belt-driven and gear-driven arrangements both exist.',[
('Understand the part','Flexible vanes change shape in the pump housing to move water. It is not the engine’s coolant circulation pump. A photograph of a belt-driven Yanmar pump is one real example, not the layout of every four-cylinder engine.'),('Recognise damage','Cracked, set, worn or missing vanes can reduce flow. Dry running can damage an impeller rapidly. A failed shaft seal can leak; pump replacement or seal work may need an engineer.'),('Check the complete circuit','Stop the engine, prevent accidental starting and close the cooling seacock before opening a pump that could admit water. Use the manual for service. Recover missing vane pieces from downstream components; a new impeller does not clear an obstructed heat exchanger.')], 'The old impeller has one vane missing. Replacing it is only part of the job: the missing piece may have travelled into a cooler or heat exchanger.','A missing vane is also a possible blockage downstream.'),
('Oil, lubrication and the gearbox','lubrication','Oil carries load between moving surfaces, reduces wear and helps manage heat. The engine and gearbox have separate requirements.',[
('Read the level correctly','Use the manual’s dipstick procedure, boat attitude and waiting time. Keep within the specified marks; too little and too much oil can both cause problems. Gearbox level methods may differ, including whether its dipstick is screwed in.'),('Use the correct products','Oil grade, specification, quantity and filter depend on engine and gearbox. A gearbox may require a different fluid entirely. Service at the stated hours or calendar interval, whichever is due first.'),('Understand an oil-and-filter service','The visual sequence is: identify the correct oil and filter, stop and make safe, contain and remove old oil, replace the filter and seal as specified, refill to the correct level, then perform the manual’s leak/level checks. Warm oil may drain more easily but can burn; never work beside moving machinery.'),('Recognise warning signs','Unexpectedly rising oil level, milky oil, fuel smell or metal debris requires investigation. A low-oil-pressure warning while running is urgent; adding oil does not automatically cure low pressure. Do not keep running to see if it clears.')], 'The oil level has risen above maximum without topping up. That may indicate contamination. Stop treating the dipstick as reassurance and have the cause checked.','Oil level and oil pressure are different things.'),
('Starting battery, alternator and belts','electrics','The battery supplies cranking power. Once running, the alternator normally recharges it through the boat’s charging system.',[
('No crank or slow crank','Check the approved starting sequence, neutral interlock where fitted, correct battery bank and isolator position. A discharged battery, loose or corroded connection, cable fault or starter fault are possible causes. Do not bridge terminals. Observe the manual’s cranking limits and pauses. Repeated cranking of a wet-exhaust engine can accumulate seawater and cause hydraulic lock; use its model-specific procedure, not a universal seacock rule.'),('Inspect with the engine stopped','Look for cracked, glazed or frayed belts and loose connections. Belt tension and routing are model-specific; keep fingers, clothing and tools away when running. A belt may drive cooling equipment as well as the alternator.'),('Respond to charging faults','A continuing charge warning may indicate belt, alternator or wiring trouble. A mechanically injected engine may keep running, but an electronic engine can depend on electrical power. Do not disconnect the battery or operate its isolator while the engine runs unless the manufacturer explicitly permits it.')], 'The charge light stays on and the belt is damaged. Before assuming you can continue on battery power, find out what else that belt drives.','Cranking, charging and cooling may be connected by one fault.'),
('Air, exhaust and interpreting smoke','exhaust','An engine needs a clear air supply and a sound exhaust system. Colour is a clue, not a reliable diagnosis on its own.',[
('Air and carbon monoxide','Check ventilation and the specified air cleaner with the engine stopped. Exhaust leaks can expose people to carbon monoxide, including from diesels. Maintain alarms and exhaust components; keep outlets clear and do not run in poorly ventilated enclosed spaces.'),('Read the whole picture','Persistent black smoke can relate to excess load or insufficient air; blue smoke can indicate oil burning; white smoke can be unburned fuel or other faults. Steam may indicate inadequate raw-water cooling. Compare temperature, load, duration and cooling flow.'),('Know when to stop investigating','A significant exhaust leak, serious overheating, abnormal knocking or fuel leakage needs immediate action to protect people and the boat. Maintain control, stop the engine when safe and appropriate, and seek assistance if needed.')], 'A white plume with rising temperature and reduced exhaust water is different from brief cold-start smoke. The accompanying observations change the urgency.','Smoke colour gives a starting point, not a verdict.'),
('Service planning, spares and winter care','service','Use the engine and gearbox manuals to build a service schedule. There is no universal marine-diesel interval.',[
('Plan by hours and time','Record model, serial number, hours, date, parts and work done. Include first-service requirements, oil and filters, fuel filters, belts, impeller, coolant, hoses, heat exchanger and anodes where fitted. Obtain specialist help for adjustments and high-pressure work.'),('Carry useful, correct spares','Suitable fuel filters, an impeller and its cover seal, approved belts, fluids and the tools you can safely use may be valuable. Knowing the part numbers and having the manuals is as important as the box of spares.'),('Prepare for storage','Follow the manufacturer’s preservation procedure for expected frost and lay-up duration. Closed-loop antifreeze does not automatically protect the raw-water circuit. Do not dry-run the impeller; manage batteries and fuel, and collect fluids for proper disposal. Recommission before use.')], 'An engine runs few hours this year. Calendar-based service can still be due. Its raw-water cooling circuit also needs its own winter plan.','A service record turns “probably done” into something you can check.')]
quiz=[
('What causes ignition in a normal diesel cycle?',['Heat from compressing air, with fuel injected at the right time','A petrol-style spark plug firing continuously','The alternator directly heating the fuel'],0,'Diesel combustion uses compression ignition. Starting aids depend on the engine.'),
('How many crankshaft turns make one four-stroke cycle?',['One','Two','Four'],1,'Intake, compression, power and exhaust take two crankshaft revolutions.'),
('What is the best first step in learning the service points?',['Use a picture of any green engine','Assume every four-cylinder engine is the same','Find the model and correct operator’s manual'],2,'Component locations and procedures vary between models.'),
('Where does separated water normally collect in a suitable fuel separator?',['At the bottom of its collection space','Inside the alternator','At the top of the air filter'],0,'Water is denser than diesel. Follow the separator maker’s inspection and draining method.'),
('A filter change introduces air. What should you do?',['Loosen injector pipes while cranking','Follow the specified low-pressure priming or self-priming procedure','Keep cranking without limit'],1,'Do not open high-pressure injection lines as a beginner.'),
('What does dark sludge in a fuel filter prove?',['The fuel has no water','That the injectors need tightening','It needs investigation; diesel bug is only one possible cause'],2,'Dirt, aged fuel, wax and microbial contamination can cause restrictions.'),
('Why can filters block after biocide treatment?',['Dead biomass and other debris can remain in the fuel system','Biocide permanently replaces filters','The coolant has become colder'],0,'Treatment may need cleaning and debris removal as well as compatible approved biocide.'),
('In a normal heat exchanger, what happens to coolant and seawater?',['They mix to cool the engine','They exchange heat without normally mixing','They both become lubricating oil'],1,'The two circuits are normally separate.'),
('The raw-water exhaust discharge disappears. What is the sensible response?',['Wait until the oil light appears','Increase rpm to force the blockage through','Maintain boat safety and respond promptly to possible cooling failure'],2,'Do not wait for overheating to become severe.'),
('When is a pressurised coolant cap safe to open?',['Only when cooled and according to the manual','Whenever the engine is overheating','With a cloth while it is still very hot'],0,'Hot pressurised coolant can cause severe burns.'),
('An impeller has a missing vane. What else needs attention?',['Only the battery terminals','Locating the missing piece in downstream cooling components','The compass deviation card'],1,'Debris can obstruct a cooler or heat exchanger.'),
('Is the raw-water pump always driven by the alternator belt?',['Yes, on every diesel','Yes, on every four-cylinder engine','No; pump location and drive vary by engine'],2,'Belt-driven and gear-driven arrangements exist.'),
('Low oil pressure is indicated while running. What should you do?',['Treat it as urgent, maintain safety and stop to investigate','Add extra oil above maximum and carry on','Assume that normal oil level makes it harmless'],0,'Normal level does not prove adequate pressure.'),
('Can engine oil automatically be used in the gearbox?',['Yes, all marine gearboxes use it','No; use the gearbox’s specified fluid and checking method','Only if the engine has four cylinders'],1,'Some gearboxes need different fluid and procedures.'),
('What is a safe basic check for slow cranking?',['Bridge starter terminals with a screwdriver','Disconnect battery cables while cranking','Check approved start settings, battery condition and connections safely'],2,'A weak battery or poor connection is possible, but not the only cause.'),
('When should belt condition be checked by hand?',['With the engine stopped and accidental starting prevented','With the engine idling slowly','While someone operates the starter'],0,'Rotating belts and pulleys can trap fingers and clothing.'),
('What does white smoke always mean?',['A failed head gasket','No single diagnosis; consider start conditions, cooling flow and other signs','A healthy raw-water pump'],1,'Steam and smoke can have different causes. Use the whole set of observations.'),
('How should service intervals be chosen?',['By engine paint colour','By using one interval for every brand','From the correct manual, considering running hours and calendar time'],2,'First-service requirements and normal intervals also differ.'),
('Does engine coolant antifreeze automatically protect the raw-water side in winter?',['No; the raw-water circuit needs the specified separate preservation procedure','Yes, the circuits are always mixed','Only when the alternator belt is new'],0,'Normal heat-exchanger circuits remain separate.'),
('A high-pressure fuel leak is suspected. What should a beginner do?',['Feel for the leak with a finger','Keep clear, make the boat safe, stop as appropriate and get qualified help','Undo the pipe to release pressure while running'],1,'Pressurised fuel can penetrate skin. Do not open the high-pressure side.')]
faults=[
('The starter clicks and turns very slowly.','electrics',['Keep trying repeatedly','Make the boat safe; check start settings and the starting battery/connection condition safely','Loosen an injector pipe'],1,'Slow cranking points first towards starting power or connections, but a starter or mechanical fault is also possible. Avoid repeated cranking and follow the engine’s limits.'),
('The starter turns normally, but the engine will not fire after a fuel-filter change.','fuel',['Check the specified priming procedure and possible air leaks on the low-pressure side','Pour fuel directly into the air intake','Crank continuously until it catches'],0,'Air after a filter change is plausible. Use only the model’s approved priming method. Repeated cranking on a wet-exhaust engine risks seawater accumulation and hydraulic lock; follow its specific instructions.'),
('Normal exhaust water disappears and the temperature starts to rise.','cooling',['Open the hot coolant cap','Increase speed to clear it','Protect boat control, stop when safe and investigate the cooling supply'],2,'A raw-water problem can damage the engine and exhaust quickly. Cool before inspection; check seacock, strainer, leaks, pump and downstream restrictions using the manual.'),
('Filters repeatedly clog and there is water and dark slime in the separator.','diesel-bug',['Investigate contamination, sample the fuel and arrange appropriate cleaning/treatment','Add unlimited biocide and carry on','Remove the filters permanently'],0,'These clues justify investigation, not certainty. Remove water and debris and use compatible approved treatment only as specified.'),
('The engine is running and the low-oil-pressure warning remains on.','lubrication',['Ignore it if the dipstick looked fine','Protect people and boat control; stop and investigate promptly','Fill above maximum to force more pressure'],1,'Low oil pressure is urgent. Level, pressure and sensor operation are distinct. Do not assume a faulty alarm without verifying the cause.'),
('The old impeller has lost a vane. A new one is fitted.','impeller',['The job is definitely finished','The missing vane has dissolved','Find and remove missing debris from the downstream circuit and verify cooling'],2,'Rubber pieces can lodge in coolers or the heat exchanger. Replacing only the rotor may leave a blockage.'),
('The charge warning stays on and a belt looks damaged.','electrics',['Check what the belt drives and assess cooling as well as charging, with the engine safely stopped','Disconnect the battery while running','Touch the belt while idling to check its tension'],0,'The belt may also drive a coolant pump. Layout is model-specific, and moving belts are dangerous.'),
('You smell diesel and see a fresh fuel leak while underway.','fuel',['Keep running to use up the leaking fuel','Make the boat safe, stop as appropriate, avoid ignition sources and seek help','Find a high-pressure leak with your hand'],1,'Protect people and navigation first. Fuel leakage is a fire hazard; never use hands to check pressure leaks.')]
sources=[['Beta Marine operator manuals (current engine-specific instructions)','https://betamarine.co.uk/literature-downloads-seagoing/'],['Volvo Penta: find the manual for your engine','https://www.volvopenta.com/support/'],['Yanmar YM-series example operator manual','https://www.yanmar.com/media/global/com/product/marinepleasure/sailBoatPropulsion/operationmanual/0AYMM-EN0023_English.pdf'],['RYA Diesel Engine course syllabus','https://www.rya.org.uk/course-finder/diesel-engine-course/'],['Parker Racor: contamination and microbial growth','https://www.racornews.com/single-post/faq-spotlight-dark-wet-stuff-on-your-used-filter']]
photos=[{'file':'volvo-d2-75.webp','title':'Real four-cylinder Volvo Penta D2-75 during dismantling','credit':'Goelette Cardabela','license':'CC BY-SA 4.0','licenseUrl':'https://creativecommons.org/licenses/by-sa/4.0/','source':'https://commons.wikimedia.org/wiki/File:Images_Volvo_D2-75-001.jpg','note':'Photograph sheet resized and recompressed; content unchanged. Parts are removed: this is not a ready-to-run installation or a servicing instruction.'}]
for f,t,src in [('yanmar-engine','Real Yanmar 2GM20 front view','Yanmar_2GM20.JPG'),('raw-water-pump','A real belt-driven raw-water pump','Water_Pump.JPG'),('injectors','Real injectors and rigid fuel lines at the cylinder head','Yanmar_Injectors.JPG'),('oil-filter','Real engine oil filter and dipstick','Oil_filter.JPG')]:
 photos.append({'file':f+'.webp','title':t,'credit':'PHGCOM','license':'CC BY-SA 3.0','licenseUrl':'https://creativecommons.org/licenses/by-sa/3.0/','source':'https://commons.wikimedia.org/wiki/File:'+src,'note':'Photograph resized and recompressed; content unchanged. Yanmar 2GM20 is a two-cylinder reference; its component layout is not a four-cylinder model’s service guide.'})
photos.append({'file':'four-cylinder-real.webp','title':'Real four-cylinder marine diesel installation','credit':'Cjp24','license':'CC BY-SA 4.0','licenseUrl':'https://creativecommons.org/licenses/by-sa/4.0/','source':'https://commons.wikimedia.org/wiki/File:Marine_diesel_engine_with_hydraulic_machinery.jpg','note':'Resized and recompressed; content unchanged. Rental-boat installation with a hydrostatic transmission; brand and exact model are not confirmed. Numbered teaching overlays are supplied under CC BY-SA 4.0.'})
hotspots=[{'x':67,'y':60,'title':'Oil filler','text':'The blue filler cap is on the rocker cover. Use the specified oil; filling here does not measure the oil level.'},{'x':66.4,'y':51.5,'title':'Coolant pressure cap','text':'The pressure cap is on the cooling assembly. Only inspect or open as directed with the engine safely cooled.'},{'x':79,'y':47,'title':'Alternator','text':'The alternator is driven by a belt and generates electrical power while running. Inspect its belt only with the engine stopped.'},{'x':70,'y':76,'title':'Rigid injection lines','text':'These lines carry high-pressure fuel towards the injectors in the cylinder head. Keep clear of pressure leaks; do not loosen them as a beginner.'},{'x':44,'y':36,'title':'Remote fuel filter / separator','text':'This unit is mounted away from the engine. Locate the filters and shutoff valve on your own installation using its documentation.'}]
d={'hotspots':hotspots,'lessons':[dict(id=f'de{i+1}',title=t,art=a,lead=l,points=p,example=e,remember=r) for i,(t,a,l,p,e,r) in enumerate(lessons)],'quiz':quiz,'faults':faults,'sources':sources,'photos':photos,'checklist':['Correct engine and gearbox manuals available','Engine and gearbox fluid levels checked by their own methods','Coolant checked safely with engine cool','Enough usable fuel and intended fuel supply available','No fresh fuel, oil, coolant or seawater leaks','Cooling seacock and strainer checked for normal operation afloat','Belt and hoses inspected with engine stopped','Battery/start settings checked; boat secure and control in neutral','Crew, clothing and tools clear of moving parts','After starting: normal cooling discharge and instruments checked']}
(R/'libraries/project-watch/diesel-1.98.0.js').write_text('/* Original recreational diesel teaching and question bank. Reviewed 29 September 2026. */\nwindow.PW_DIESEL='+json.dumps(d,ensure_ascii=False,indent=2)+';\n')
# Exact, original vector teaching: principles, not claimed model layouts.
def text(x,y,s,size=24,color='#173a44',weight=400,anchor='start'):
 return f'<text x="{x}" y="{y}" font-size="{size}" fill="{color}" font-weight="{weight}" text-anchor="{anchor}">{html.escape(s)}</text>'
def rect(x,y,w,h,fill='#fff',stroke='#c4cec7',rx=16):return f'<rect x="{x}" y="{y}" width="{w}" height="{h}" rx="{rx}" fill="{fill}" stroke="{stroke}" stroke-width="2"/>'
def line(x,y,u,v,color='#287b99',width=6):return f'<path d="M{x} {y}L{u} {v}" fill="none" stroke="{color}" stroke-width="{width}" marker-end="url(#arrow)"/>'
def label(x,y,t,sub=''):
 return text(x,y,t,25,weight=700)+text(x,y+34,sub,20,'#526c70')
def plate(name,title,subtitle,body,foot='Original principle diagram • actual layout and servicing depend on the model'):
 s=f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 900" role="img" aria-labelledby="title desc"><title id="title">{html.escape(title)}</title><desc id="desc">{html.escape(subtitle)}</desc><defs><linearGradient id="metal"><stop stop-color="#6c8588"/><stop offset=".4" stop-color="#e2e9e6"/><stop offset=".65" stop-color="#b7c7c7"/><stop offset="1" stop-color="#516c73"/></linearGradient><linearGradient id="brass"><stop stop-color="#73521d"/><stop offset=".42" stop-color="#e5c478"/><stop offset="1" stop-color="#8c6931"/></linearGradient><linearGradient id="oil"><stop stop-color="#edd698"/><stop offset="1" stop-color="#b78135"/></linearGradient><marker id="arrow" markerWidth="10" markerHeight="10" refX="7" refY="4" orient="auto"><path d="M0 0L8 4L0 8Z" fill="context-stroke"/></marker></defs><rect width="1440" height="900" fill="#f5f2e9"/><g font-family="Arial,Helvetica,sans-serif">{text(60,52,'PROJECT WATCH / DIESEL ENGINE BASICS',17,'#5c7778',700)}{text(60,109,title,38,weight=700)}{text(60,152,subtitle,23,'#526c70')}{body}{text(60,858,foot,19,'#526c70')}</g></svg>'''
 (A/(name+'.svg')).write_text(s)
# Overview: systems, not invented realistic engine geometry.
b=''
for i,(title,sub,detail,c) in enumerate([('FUEL','Clean diesel, delivered correctly','Tank → filters → injection','#bd852e'),('AIR','Air in; exhaust out','Ventilation and sound exhaust','#597e67'),('COOLING','Heat out of the engine','Coolant + seawater circuits','#287b99'),('LUBRICATION','Protect moving parts','Specified oil, level and pressure','#a4773a'),('STARTING','Turn the engine to start','Battery, cables and starter','#526b9b'),('DRIVE','Power to the propeller','Gearbox and shaft / saildrive','#6b7178')]):
 x=60+(i%3)*450;y=218+(i//3)*280
 b+=rect(x,y,420,235)+f'<circle cx="{x+52}" cy="{y+53}" r="25" fill="{c}"/>'+text(x+52,y+61,str(i+1),22,'#fff',700,'middle')+text(x+95,y+62,title,27,weight=700)+text(x+28,y+128,sub,22)+text(x+28,y+178,detail,20,'#526c70')
plate('overview','Six systems. One reliable engine.','Learn the jobs first, then locate the actual parts in your manual.',b)
# Four strokes: intake valve open/closed; injector near TDC; arrows correct.
b=''
for i,(title,caption,py,up,intake,exhaust) in enumerate([('1  INTAKE','Air drawn into cylinder',528,False,True,False),('2  COMPRESSION','Air squeezed and heated',355,True,False,False),('3  POWER','Burning gas pushes down',465,False,False,False),('4  EXHAUST','Burned gas expelled',355,True,False,True)]):
 x=48+i*348;b+=rect(x,208,326,572)+text(x+24,252,title,25,weight=700)
 b+=f'<path d="M{x+57} 321V653H{x+273}V321" fill="#e1e8e3" stroke="#687f83" stroke-width="14"/><rect x="{x+69}" y="326" width="192" height="326" fill="#fff"/><rect x="{x+69}" y="326" width="192" height="{py-326}" fill="{["#d8eaf2","#f2d9aa","#f5c08a","#d4d7d8"][i]}"/>'
 b+=f'<rect x="{x+64}" y="{py}" width="202" height="58" rx="5" fill="url(#metal)" stroke="#566a6e" stroke-width="3"/><path d="M{x+70} {py+12}H{x+260}M{x+70} {py+23}H{x+260}" stroke="#566a6e" stroke-width="4"/><path d="M{x+165} {py+58}V675" stroke="url(#metal)" stroke-width="22"/>'
 # head and valves; intake on left, exhaust right
 b+=f'<path d="M{x+55} 319H{x+275}" stroke="#647b7e" stroke-width="16"/>'
 for dx,opened in [(102,intake),(225,exhaust)]:
  vy=343 if opened else 315;b+=f'<path d="M{x+dx} 283V{vy}" stroke="#526c70" stroke-width="8"/><path d="M{x+dx-18} {vy}H{x+dx+18}" stroke="#526c70" stroke-width="8"/>'
 b+=f'<path d="M{x+165} 282V334" stroke="#b28c48" stroke-width="12"/>'
 if i==0:b+=line(x+8,350,x+91,374)
 if i==3:b+=line(x+229,370,x+310,308,'#727c80')
 if i==2:
  for dx in [-24,-12,0,12,24]:b+=f'<path d="M{x+165} 338l{dx} 46" stroke="#cf792f" stroke-width="3"/>'
 b+=line(x+291,530 if up else 400,x+291,405 if up else 530,'#bd852e',5)+text(x+18,725,caption,21)
plate('four-stroke','A diesel’s four strokes','A simplified cylinder cutaway: intake air, compression, power, exhaust.',b,'Four strokes = two crankshaft revolutions • valve timing simplified • injector shown in the cylinder head')
# Fuel schematic detailed symbols on two tiers.
b='';names=[('TANK','Shutoff at supply'),('SEPARATOR','Primary filter + water'),('LIFT PUMP','Low-pressure supply'),('FINE FILTER','Engine-mounted filter'),('INJECTION PUMP','Timed high pressure'),('INJECTORS','Into cylinder head')]
for i,(title,sub) in enumerate(names):
 x=65+(i%3)*465;y=215+(i//3)*292
 b+=rect(x,y,385,224)+label(x+20,y+42,title,sub)
 if i in [0]:b+=rect(x+110,y+109,166,80,'url(#metal)','#647b7e',6)+f'<path d="M{x+121} {y+162}H{x+264}" stroke="#bd852e" stroke-width="25"/>'
 elif i in [1,3]:
  b+=rect(x+140,y+96,110,101,'url(#metal)','#647b7e',6)
  for dx in range(149,245,10):b+=f'<path d="M{x+dx} {y+104}V{y+178}" stroke="#b6975b" stroke-width="3"/>'
  if i==1:b+=rect(x+143,y+179,104,27,'#bddde5','#647b7e',5)
 elif i==2:b+=f'<circle cx="{x+193}" cy="{y+149}" r="52" fill="url(#metal)" stroke="#647b7e" stroke-width="3"/><path d="M{x+157} {y+149}H{x+227}" stroke="#526c70" stroke-width="6"/>'
 elif i==4:b+=rect(x+122,y+110,145,78,'url(#metal)','#647b7e',7)
 else:
  for dx in range(105,285,48):b+=f'<rect x="{x+dx}" y="{y+105}" width="18" height="68" rx="4" fill="url(#metal)"/><path d="M{x+dx+9} {y+173}v17" stroke="#b48533" stroke-width="5"/>'
for y in [327,619]:
 for x in [450,915]:b+=line(x,y,x+60,y,'#b55246' if y==619 and x==915 else '#bd852e')
b+=f'<path d="M1380 327H1401V469H35V619H60" fill="none" stroke="#bd852e" stroke-width="5" marker-end="url(#arrow)"/>'
b+=f'<path d="M1180 731V783H18V418H65M713 731V783" fill="none" stroke="#597e67" stroke-width="5" stroke-dasharray="10 7" marker-end="url(#arrow)"/>'+text(680,816,'Surplus fuel returns to tank in this example',21,'#597e67')
plate('fuel','Follow the fuel. Protect the injection side.','Mechanical example: gold supply, red injection, dashed green return. Actual routing varies.',b)
# Filters large cutaway pair
b=''
b+=rect(60,213,624,568)+rect(734,213,646,568)
b+=label(92,258,'PRIMARY FILTER / WATER SEPARATOR','Conceptual cutaway — not a particular product')
b+=rect(215,319,290,86,'url(#metal)','#647b7e',14)+rect(246,405,228,229,'#f3dc9f','#617e82',9)
for dx in range(269,460,16):b+=f'<path d="M{dx} 420V563" stroke="#b8995a" stroke-width="7"/>'
b+=rect(246,575,228,88,'#d5e7eb','#617e82',9)+f'<path d="M251 607H469" stroke="#75adc2" stroke-width="35"/>'+text(360,646,'WATER',21,'#285774',700,'middle')+text(360,552,'ELEMENT',22,'#735826',700,'middle')+f'<path d="M360 664v38" stroke="#6e7f82" stroke-width="15"/>'+text(115,747,'Inspect / drain by the separator instructions',22)
b+=label(766,258,'ENGINE FINE FILTER','Protects precision injection equipment')+rect(925,322,200,74,'url(#metal)','#647b7e',10)+rect(941,396,170,267,'#ddd4b9','#617e82',13)
for dx in range(955,1100,12):b+=f'<path d="M{dx} 411V634" stroke="#b8995a" stroke-width="5"/>'
b+=text(1025,700,'Specified element + correct seals',22,'#173a44',400,'middle')+text(767,747,'Prime only by the engine’s approved method',22)
plate('filters','Two filters. Two important jobs.','Keep dirt, water and air away from the fuel injection equipment.',b)
# bug tank section liquid interface no fake microbes magnification
b=rect(80,230,800,506)+rect(120,298,720,338,'#e8d3a4','#637d81',12)+rect(120,618,720,65,'#a0c6d4','#637d81',0)
b+=text(155,376,'DIESEL FUEL',30,'#805f2b',700)+text(155,664,'ACCUMULATED WATER',26,'#285774',700)
for i in range(30):
 x=150+i*22;y=604+(i%3)*7;b+=f'<ellipse cx="{x}" cy="{y}" rx="8" ry="5" fill="#5c6247"/>'
b+=text(940,330,'THE FUEL / WATER',27,weight=700)+text(940,367,'INTERFACE',27,weight=700)+text(940,420,'A place microbes can grow',23)+text(940,492,'Remove water and debris',24)+text(940,539,'Investigate recurring blockage',23)+text(940,586,'Treatment must match the cause',22)+line(920,630,846,623,'#597e67',4)
plate('diesel-bug','Water changes the picture.','Conceptual tank section: microbial contamination can develop at the interface.',b,'Sludge alone is not a diagnosis • approved treatment does not remove all dead biomass or dirt')
# Cooling topology: separate closed and rawwater loops.
b=rect(60,211,1320,249,'#f6e7d4','#ddc29c')+rect(60,499,1320,271,'#dcecf0','#a3c4ce')
b+=text(88,254,'CLOSED COOLANT CIRCUIT',24,'#9a6630',700)+text(88,540,'OPEN RAW-WATER CIRCUIT',24,'#287b99',700)
for i,(t,sub) in enumerate([('CIRCULATION PUMP','Moves coolant'),('ENGINE','Heat picked up'),('THERMOSTAT','Controls flow'),('HEAT EXCHANGER','Heat transferred')]):
 x=90+i*320;b+=rect(x,284,275,87,'#fff','#cfb894',9)+text(x+137,318,t,21,'#76501f',700,'middle')+text(x+137,348,sub,20,'#526c70',400,'middle')
 if i<3:b+=line(x+279,327,x+315,327,'#b88240',4)
b+=f'<path d="M1187 375V416H226V375" fill="none" stroke="#b88240" stroke-width="5" marker-end="url(#arrow)"/>'+text(690,408,'Cooled coolant returns',20,'#76501f',400,'middle')
for i,(t,sub) in enumerate([('SEACOCK','Hull inlet'),('STRAINER','Catches debris'),('RAW-WATER PUMP','Flexible impeller'),('HEAT EXCHANGER','Receives heat'),('WET EXHAUST','Water leaves boat')]):
 x=86+i*261;b+=rect(x,582,229,106,'#fff','#a3c4ce',9)+text(x+114,620,t,20,'#285774',700,'middle')+text(x+114,655,sub,19,'#526c70',400,'middle')
 if i<4:b+=line(x+231,634,x+257,634,'#287b99',3)
b+=text(895,487,'Same exchanger: heat transfer only',19,'#76501f')
b+=text(90,737,'Warm-up bypass, extra coolers and anti-siphon arrangements are not drawn.',22,'#526c70')
plate('cooling','Two circuits. Heat transfer, not mixing.','Typical heat-exchanger cooling with a wet exhaust. Follow the actual installation diagram.',b)
# Impeller comparison: uninstalled rotors, no wrong port/rotation claims.
b=''
for i,(title,sub) in enumerate([('COMPLETE ROTOR','All vanes present — condition still needs inspection'),('DAMAGED ROTOR','Missing vane — recover debris downstream')]):
 x=60+i*685;b+=rect(x,219,650,527)+text(x+30,264,title,25,weight=700)
 cx=x+320;cy=469
 b+=f'<ellipse cx="{cx}" cy="{cy+118}" rx="173" ry="22" fill="#263c4322"/>'
 for n in range(10):
  if i==1 and n==2:continue
  angle=2*math.pi*n/10;co=math.cos(angle);si=math.sin(angle);a=(cx+co*67,cy+si*67);z=(cx+co*157,cy+si*157)
  b+=f'<path d="M{a[0]} {a[1]}Q{cx+co*125-si*12} {cy+si*125+co*12} {z[0]} {z[1]}" stroke="#2c383c" stroke-width="26" stroke-linecap="round"/>'
 b+=f'<circle cx="{cx}" cy="{cy}" r="78" fill="#2c383c"/><circle cx="{cx}" cy="{cy}" r="36" fill="url(#brass)" stroke="#514734" stroke-width="5"/><circle cx="{cx}" cy="{cy}" r="19" fill="#f5f2e9"/><path d="M{cx+13} {cy-6}h14v12h-14" fill="#f5f2e9"/>'
 b+=text(x+325,691,sub,21,'#526c70',400,'middle')
plate('impeller','A small part with a big cooling job.','Flexible-impeller recognition: uninstalled rotors, not a pump assembly or replacement instruction.',b,'Pump location, drive, rotor size, vane count, direction and cover seal are model-specific')
# Oil simple flow plus dipstick bands
b=rect(70,223,665,565)+rect(779,223,591,565)
b+=label(105,270,'CHECK LEVEL BY THE MANUAL','Engine stopped; specified wait and boat attitude')
b+=f'<path d="M375 335V688" stroke="url(#metal)" stroke-width="36"/><path d="M347 492H404M347 613H404" stroke="#173a44" stroke-width="5"/>'+text(438,500,'MAX',24,weight=700)+text(438,620,'MIN',24,weight=700)+f'<path d="M358 532V613" stroke="#b88240" stroke-width="25"/>'+text(105,745,'Within the marks — never deliberately overfill',23)
b+=label(812,270,'LUBRICATION PATH','Simplified principle; arrangements vary')
for i,t in enumerate(['SUMP / PICKUP','OIL PUMP','OIL FILTER','BEARINGS / MOVING PARTS']):
 y=322+i*99;b+=rect(834,y,480,68,'#fff','#c5b598',9)+text(1074,y+43,t,23,'#805f2b',700,'middle')
 if i<3:b+=line(1074,y+70,1074,y+92,'#b88240',3)
b+=text(814,755,'Oil drains back to the sump',23)
plate('lubrication','Level is not the same as pressure.','Engine oil and gearbox fluid have their own specifications and checking procedures.',b)
# electrics battery, starter, alternator belt relationships
b=rect(65,223,1310,555)
for x,t,sub in [(115,'START BATTERY','Cranking power'),(600,'STARTER','Turns the engine'),(1080,'ALTERNATOR','Charges while running')]:
 b+=text(x+110,282,t,23,weight=700)+text(x+110,317,sub,20,'#526c70')
 if x==115:
  b+=rect(x+70,374,225,175,'#355e65','#183d47',15)+rect(x+96,356,35,20,'url(#metal)','#637d81',3)+rect(x+240,356,35,20,'url(#metal)','#637d81',3)+text(x+112,475,'+',42,'#fff',700)+text(x+252,475,'−',42,'#fff',700)
 else:
  b+=f'<circle cx="{x+125}" cy="453" r="85" fill="url(#metal)" stroke="#536d76" stroke-width="6"/><circle cx="{x+125}" cy="453" r="31" fill="#536d76"/>'
  if x==1080:
   for k in range(12):
    ang=k*math.pi/6;b+=f'<path d="M{x+125+math.cos(ang)*45} {453+math.sin(ang)*45}L{x+125+math.cos(ang)*69} {453+math.sin(ang)*69}" stroke="#536d76" stroke-width="8"/>'
b+=line(410,453,622,453,'#a76847',6)+text(518,415,'START',22,'#a76847',700,'middle')+f'<path d="M1205 549V618H294V555" stroke="#597e67" stroke-width="6" fill="none" marker-end="url(#arrow)"/>'+text(700,665,'CHARGING CIRCUIT • regulator and boat wiring not shown',21,'#597e67',700,'middle')+text(135,730,'Never touch moving belts or disconnect the battery while running.',25)
plate('electrics','Starting uses power. Running can restore it.','Electrical principle diagram, not an installation wiring diagram.',b)
# checks, service, exhaust panels use themed precise cards
for name,title,subtitle,items in [
('checks','A simple before-start routine','Afloat, with the engine stopped and cool. Follow your boat’s manual.',[('FLUIDS','Oil • coolant • gearbox fluid','Correct method, within specified levels'),('SUPPLIES','Fuel • starting battery • cooling inlet','Available, correctly set and inspected'),('CONDITION','Leaks • hoses • belt • strainer','Inspect safely; resolve new problems'),('AFTER START','Cooling discharge • instruments','Keep clear; confirm normal operation')]),
('exhaust','Interpret smoke with the whole picture','These are possibilities to investigate, not diagnoses.',[('BLACK','Excess load / insufficient air possible','Consider load, air supply and performance'),('BLUE','Oil burning possible','Check consumption and seek investigation'),('WHITE','Unburned fuel / other fault possible','Cold-start behaviour changes the picture'),('STEAM + HEAT','Reduced raw-water cooling possible','Check discharge and respond promptly')]),
('service','Build a schedule for your engine','Use model-specific hours, calendar intervals and first-service requirements.',[('IDENTIFY','Model • serial number • gearbox','Correct manuals and approved fluids'),('PLAN','Oil • filters • belt • cooling parts','Record hours and calendar due dates'),('PREPARE','Correct spares • seals • safe tools','Know your limits and seek skilled help'),('RECORD','Date • hours • parts • observations','Include preservation and recommissioning')])]:
 b=''
 for i,(t,l1,l2) in enumerate(items):
  x=65+(i%2)*680;y=219+(i//2)*286;b+=rect(x,y,630,246)+text(x+30,y+53,t,28,weight=700)+text(x+30,y+120,l1,24)+text(x+30,y+177,l2,22,'#526c70')
 plate(name,title,subtitle,b)
print('12 lessons, 20 questions, 8 fault scenarios, 12 original plates, 6 licensed references')
