/* Internet AIS display; source timestamps are never treated as own-boat fixes. */
(()=>{'use strict';const $=id=>document.getElementById(id);let map,layer,timer,abort,epoch=0,enabled=false,targets=[];const url=window.HelmloreAISConfig?.relayUrl||'';const configured=/^https:\/\//.test(url);const staleMs=300000,expireMs=900000;
function age(v){const t=v.reportedAt??v.receivedAt;return Date.now()-t;}const value=(n,u)=>Number.isFinite(n)?n.toFixed(1)+' '+u:'Unavailable';
function draw(){layer.clearLayers();const now=Date.now();targets=targets.filter(v=>now-v.receivedAt<=expireMs&&age(v)<=expireMs);for(const v of targets){const old=age(v)>staleMs,direction=Number.isFinite(v.heading)?v.heading:v.course;const div=document.createElement('div');div.className='ais-symbol';div.style.opacity=old?'.4':'1';div.style.transform='rotate('+(Number.isFinite(direction)?direction:0)+'deg)';div.textContent=Number.isFinite(direction)?'▲':'●';const icon=L.divIcon({className:'ais-target',html:div,iconSize:[24,24],iconAnchor:[12,12]});const marker=L.marker([v.lat,v.lon],{icon,zIndexOffset:700});const popup=document.createElement('div');const title=document.createElement('strong');title.textContent=v.name||'AIS vessel';popup.append(title);for(const line of ['MMSI '+v.mmsi,'Speed '+value(v.speed,'kn'),'Course '+value(v.course,'° T'),'Heading '+value(v.heading,'° T'),Math.max(0,Math.floor(age(v)/1000))+' seconds since '+(v.reportedAt?'reported position':'relay reception'),old?'OLD POSITION · do not treat as current':'Internet AIS · delays and missing vessels possible']){const p=document.createElement('div');p.textContent=line;popup.append(p);}marker.bindPopup(popup).addTo(layer);if(!old&&Number.isFinite(v.speed)&&v.speed>0&&Number.isFinite(v.course)){const end=window.HelmloreNav.destination({lat:v.lat,lon:v.lon},v.course,v.speed*1852*3/60);L.polyline([[v.lat,v.lon],[end.lat,end.lon]],{color:'#146d5a',weight:1,dashArray:'4 4',interactive:false}).addTo(layer);}}
$('aisCount').textContent=targets.length+' targets in the loaded area';const list=$('aisTargets');list.replaceChildren();targets.slice(0,20).forEach(v=>{const b=document.createElement('button');b.textContent=(v.name||v.mmsi)+' · '+value(v.speed,'kn')+(age(v)>staleMs?' · OLD':'');b.onclick=()=>map.panTo([v.lat,v.lon]);list.append(b);});}
function stop(){enabled=false;epoch++;clearTimeout(timer);abort?.abort();targets=[];layer.clearLayers();$('aisEnabled').checked=false;$('aisCount').textContent='AIS hidden';$('aisTargets').replaceChildren();}
async function poll(){if(!enabled)return;const token=epoch;abort?.abort();abort=new AbortController();const timeout=setTimeout(()=>abort.abort(),15000);try{const b=map.getBounds(),params=new URLSearchParams({bbox:[b.getSouth(),b.getWest(),b.getNorth(),b.getEast()].map(x=>x.toFixed(4)).join(',')});if(b.getNorth()-b.getSouth()>8||b.getEast()-b.getWest()>12){targets=[];draw();$('aisStatus').textContent='Zoom in to load AIS for a smaller area.';return;}const r=await fetch(url.replace(/\/$/,'')+'/v1/targets?'+params,{signal:abort.signal,cache:'no-store'});if(!r.ok)throw Error();const data=await r.json();if(token!==epoch||!enabled)return;if(!Array.isArray(data.targets)||!Number.isFinite(data.asOf)||Math.abs(Date.now()-data.asOf)>60000)throw Error();targets=data.targets.filter(v=>/^\d{9}$/.test(String(v.mmsi))&&Number.isFinite(v.lat)&&Math.abs(v.lat)<=90&&Number.isFinite(v.lon)&&Math.abs(v.lon)<=180&&Number.isFinite(v.receivedAt)&&v.receivedAt<=Date.now()+60000).map(v=>({...v,name:String(v.name||'').slice(0,80),reportedAt:Number.isFinite(v.reportedAt)&&v.reportedAt<=Date.now()+60000?v.reportedAt:null}));draw();const c=data.coverage,outside=c&&(b.getSouth()<c.south||b.getNorth()>c.north||b.getWest()<c.west||b.getEast()>c.east);$('aisStatus').textContent=(data.connected?'Relay connected':'Upstream disconnected · last known positions only')+(outside?' · part of this view is outside relay coverage':'')+' · refreshed '+new Date(data.asOf).toLocaleTimeString('en-GB')+(targets.length?'':' · no reports received here; this does not mean no vessels');}catch(e){if(token!==epoch||!enabled)return;targets=[];draw();$('aisStatus').textContent='AIS connection unavailable · targets cleared. Retrying.';}finally{clearTimeout(timeout);if(token===epoch&&enabled)timer=setTimeout(poll,10000);}}
window.addEventListener('navigation-map-ready',e=>{map=e.detail.map;layer=L.layerGroup().addTo(map);$('aisEnabled').disabled=!configured;$('aisRefresh').disabled=!configured;$('aisStatus').textContent=configured?'Ready · enable AIS to send the visible map area to the relay.':'Live AIS is not connected yet. The AISStream key and relay hosting still need to be set up.';$('aisEnabled').onchange=e=>{if(e.target.checked){enabled=true;epoch++;poll();}else{stop();$('aisStatus').textContent='AIS off';}};$('aisRefresh').onclick=()=>{if(enabled){clearTimeout(timer);epoch++;poll();}};setInterval(()=>{if(enabled)draw();},10000);window.addEventListener('pagehide',stop);});
})();
