/* Helmlore Navigation Lab 0.1: online map and foreground GPS prototype. */
(function(){
 'use strict';
 const N=window.HelmloreNav,$=id=>document.getElementById(id),HOME={lat:54.5531,lon:-3.5904},KEY='helmlore-navigation-lab-v1';
 const state={mode:'explore',fix:null,previous:null,motion:{speed:null,course:null},watch:null,epoch:0,demo:null,recording:false,adding:false,follow:false,target:0,planId:null,marinaTarget:null,segment:Date.now(),routes:{demo:[],gps:[]},tracks:{demo:[],gps:[]}};
 let map,boat,accuracyCircle,routeLine,targetLine,waypointLayer,trackLayer,seamarks,base;
 const source=()=>state.mode==='gps'||(state.mode==='explore'&&state.planId)?'gps':'demo',route=()=>state.routes[source()],track=()=>state.tracks[source()];
 const stale=()=>!state.fix||Date.now()-state.fix.time>15000;
 const metresToNM=m=>(m/1852).toFixed(2);
 const degrees=n=>String(Math.round(n)%360).padStart(3,'0')+'° T';
 function readSaved(){try{const s=JSON.parse(localStorage.getItem(KEY)||'{}');state.planId=typeof s.planId==='string'?s.planId:null;for(const k of ['demo','gps']){state.routes[k]=(Array.isArray(s.routes?.[k])?s.routes[k]:[]).filter(N.valid).slice(0,100).map(p=>({lat:p.lat,lon:p.lon,name:String(p.name||'Waypoint').slice(0,80),locked:!!p.locked}));state.tracks[k]=(Array.isArray(s.tracks?.[k])?s.tracks[k]:[]).filter(p=>N.valid(p)&&Number.isFinite(p.time)&&Number.isFinite(p.segment)).slice(-6000).map(p=>({lat:p.lat,lon:p.lon,time:p.time,segment:p.segment}));}}catch{ $('storageStatus').textContent='Saved data could not be read. You can still use the map and export your work.';}}
 function save(){try{localStorage.setItem(KEY,JSON.stringify({routes:state.routes,tracks:state.tracks,planId:state.planId}));}catch{$('storageStatus').textContent='Browser storage is unavailable or full. Export your route or track before leaving.';}}
 function status(text){$('positionStatus').textContent=text;}
 function popup(point,index){const node=document.createElement('div'),strong=document.createElement('strong'),small=document.createElement('div');strong.textContent=point.name;small.textContent=N.coordinate(point.lat,true)+' / '+N.coordinate(point.lon,false);node.append(strong,small);return node;}
 function resetSource(mode){state.epoch++;if(state.watch!==null){navigator.geolocation?.clearWatch(state.watch);state.watch=null;}if(state.demo){clearInterval(state.demo);state.demo=null;}state.mode=mode;state.recording=false;state.fix=null;state.previous=null;state.motion={speed:null,course:null};state.target=state.planId&&mode!=='demo'&&state.routes.gps.length>1?1:0;if(boat){map.removeLayer(boat);boat=null;}accuracyCircle?.setRadius(0);$('modeBadge').textContent=mode==='gps'?'LIVE GPS':mode==='demo'?'SIMULATED':'EXPLORE';$('modeBadge').className='badge '+mode;$('demoButton').textContent=mode==='demo'?'Stop demo':'Run demo';$('gpsButton').textContent=mode==='gps'?'Stop GPS':'Use my GPS';$('routeSource').textContent=source()==='gps'?'GPS ROUTE':'DEMO ROUTE';drawRoute();drawTrack();render();}
 function vesselIcon(course,old){return L.divIcon({className:'vessel-icon',iconSize:[36,36],iconAnchor:[18,18],html:`<svg viewBox="0 0 36 36" aria-hidden="true" style="transform:rotate(${Number.isFinite(course)?course:0}deg)"><path d="M18 2 L30 29 L18 25 L6 29 Z" fill="${old?'#6b7b83':state.mode==='demo'?'#ba761a':'#007fa8'}" stroke="white" stroke-width="2.5"/><circle cx="18" cy="20" r="3" fill="white"/></svg>`});}
 function updateFix(fix){if(!N.valid(fix)||!Number.isFinite(fix.time)||fix.time>Date.now()+5000)return;if(state.fix&&fix.time<=state.fix.time)return;state.previous=state.fix;state.fix=fix;state.motion=N.motion(fix,state.previous);const point=[fix.lat,fix.lon];if(!boat)boat=L.marker(point,{icon:vesselIcon(state.motion.course,stale()),zIndexOffset:1000}).addTo(map);else boat.setLatLng(point).setIcon(vesselIcon(state.motion.course,stale()));accuracyCircle.setLatLng(point).setRadius(state.mode==='gps'?Math.min(fix.accuracy,100000):0);if(state.follow)map.panTo(point,{animate:false});
  if(state.recording&&!stale()&&fix.accuracy<=100){const t=track(),last=t[t.length-1];if(!last||last.segment!==state.segment||N.distance(last,fix)>=3){t.push({lat:fix.lat,lon:fix.lon,time:fix.time,segment:state.segment});if(t.length>=6000){state.recording=false;$('storageStatus').textContent='Track limit reached (6,000 positions). Export the track, then clear it to record again.';}save();drawTrack();}}
  render();
 }
 function startDemo(){resetSource('demo');let p={lat:54.557,lon:-3.628},course=250;function tick(){p=N.destination(p,course,7*1852/3600);course=N.bearing(p,N.destination(p,course+0.4,10));updateFix({...p,time:Date.now(),accuracy:0,speed:7*1852/3600,heading:course});status('SIMULATED voyage near Whitehaven · not your GPS position');}tick();map.setView([p.lat,p.lon],13);state.demo=setInterval(tick,1000);}
 function startGPS(){if(!navigator.geolocation){status('Location is not supported by this browser. You can use the demo.');return;}if(!window.isSecureContext){status('GPS requires a secure HTTPS page. Open https://helmlore.com/navigation.html.');return;}resetSource('gps');const epoch=state.epoch;status('Waiting for location permission and a GPS fix…');let first=true;
  state.watch=navigator.geolocation.watchPosition(p=>{if(state.mode!=='gps'||epoch!==state.epoch)return;const c=p.coords;if(!Number.isFinite(c.accuracy)||c.accuracy<0)return;updateFix({lat:c.latitude,lon:c.longitude,accuracy:c.accuracy,speed:c.speed,heading:c.heading,time:p.timestamp});if(first&&state.fix){map.setView([state.fix.lat,state.fix.lon],14);first=false;}if(state.fix)status(c.accuracy>100?'Low location accuracy · speed and course unavailable':'GPS active · location from your device');},e=>{if(epoch!==state.epoch)return;state.fix=null;state.previous=null;state.recording=false;state.motion={speed:null,course:null};if(boat)boat.setIcon(vesselIcon(null,true));accuracyCircle.setRadius(0);status(e.code===1?'Location permission denied. Allow location for Helmlore in Safari, then try again.':e.code===2?'Location unavailable. Check Location Services or use the demo.':'Waiting for location · no fresh GPS fix yet');render();},{enableHighAccuracy:true,maximumAge:0,timeout:15000});
 }
 function drawRoute(){if(!map)return;waypointLayer.clearLayers();routeLine.setLatLngs(route().map(p=>[p.lat,p.lon]));route().forEach((p,i)=>{const m=L.marker([p.lat,p.lon],{draggable:!p.locked,icon:L.divIcon({className:'waypoint-icon',html:String(i+1),iconSize:[25,25],iconAnchor:[12.5,12.5]})}).addTo(waypointLayer).bindPopup(popup(p,i));m.on('dragend',()=>{const c=m.getLatLng();p.lat=c.lat;p.lon=((c.lng+540)%360)-180;save();drawRoute();render();});});
  const list=$('waypoints');list.replaceChildren();route().forEach((p,i)=>{const li=document.createElement('li'),line=document.createElement('div'),number=document.createElement('span'),input=document.createElement('input'),coords=document.createElement('small'),actions=document.createElement('div'),select=document.createElement('button'),remove=document.createElement('button');line.className='waypoint-name';number.textContent=i+1;input.value=p.name;input.maxLength=60;input.setAttribute('aria-label','Waypoint '+(i+1)+' name');input.addEventListener('change',()=>{p.name=input.value.trim()||'Waypoint '+(i+1);save();drawRoute();render();});line.append(number,input);coords.textContent=N.coordinate(p.lat,true)+' · '+N.coordinate(p.lon,false);actions.className='waypoint-actions';select.textContent=i===state.target?'Next target':'Set next';select.setAttribute('aria-pressed',String(i===state.target));select.addEventListener('click',()=>{state.marinaTarget=null;window.dispatchEvent(new Event('navigation-marina-cleared'));state.target=i;drawRoute();render();});remove.textContent='Remove';remove.setAttribute('aria-label','Remove waypoint '+(i+1));remove.addEventListener('click',()=>{route().splice(i,1);if(i<state.target)state.target--;state.target=Math.max(0,Math.min(state.target,route().length-1));save();drawRoute();render();});actions.append(select,remove);li.append(line,coords,actions);list.append(li);});
 }
 function drawTrack(){if(!map)return;trackLayer.clearLayers();const groups=[];for(const p of track()){let g=groups[groups.length-1];if(!g||g[0].segment!==p.segment){g=[];groups.push(g);}g.push(p);}groups.forEach(g=>{if(g.length>1)L.polyline(g.map(p=>[p.lat,p.lon]),{color:'#9859c8',weight:3}).addTo(trackLayer);});}
 function render(){const fresh=state.fix&&!stale()&&state.fix.accuracy<=100,m=state.motion,p=state.fix,w=state.marinaTarget||route()[state.target];$('destinationLabel').textContent=state.marinaTarget?'MARINA DESTINATION':'NEXT WAYPOINT';$('timeTargetLabel').textContent=state.marinaTarget?'TIME TO MARINA':'TIME TO WAYPOINT';if(state.recording&&(!fresh||p.accuracy>100)){state.recording=false;$('storageStatus').textContent='Recording stopped because the position became old or inaccurate. Start a new recording after the fix recovers.';}$('sog').textContent=fresh&&m.speed!==null?m.speed.toFixed(1):'—';$('cog').textContent=fresh&&m.course!==null?degrees(m.course):'—';$('speedSource').textContent=state.mode==='demo'?'knots · simulated':fresh?(m.estimated?'knots · estimated from fixes':m.speed===null?'knots · device speed unavailable':'knots · device speed'):'knots · no fresh position';$('latitude').textContent=p?N.coordinate(p.lat,true):'—';$('longitude').textContent=p?N.coordinate(p.lon,false):'—';$('accuracy').textContent=p?(state.mode==='demo'?'Simulated position':`${fresh?'Accuracy':stale()?'OLD FIX':'LOW ACCURACY'} ±${Math.round(p.accuracy)} m · ${Math.max(0,Math.floor((Date.now()-p.time)/1000))}s ago`):'No position fix';
  if(w&&fresh){const d=N.distance(p,w);$('distance').textContent=metresToNM(d)+' NM';$('bearing').textContent=degrees(N.bearing(p,w))+' · '+w.name;const minutes=m.speed!==null&&m.speed>=0.5?d/1852/m.speed*60:null;$('eta').textContent=minutes===null?'—':minutes<60?Math.max(1,Math.round(minutes))+' min':Math.floor(minutes/60)+'h '+Math.round(minutes%60)+'m';$('arrival').textContent=minutes===null?'Need a reliable speed to estimate':(state.mode==='demo'?'Simulated arrival ':'Arrival ')+new Date(Date.now()+minutes*60000).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});targetLine.setLatLngs([[p.lat,p.lon],[w.lat,w.lon]]);}else{$('distance').textContent='—';$('bearing').textContent=w?w.name:'Choose a waypoint';$('eta').textContent='—';$('arrival').textContent='Based on current speed';targetLine?.setLatLngs([]);}
  let total=0;route().forEach((p,i)=>{if(i)total+=N.distance(route()[i-1],p);});$('routeTotal').textContent=metresToNM(total)+' NM';let travelled=0;track().forEach((p,i)=>{if(i&&p.segment===track()[i-1].segment)travelled+=N.distance(track()[i-1],p);});$('trackDistance').textContent=metresToNM(travelled)+' NM';$('trackCount').textContent=track().length+' positions';$('recordButton').disabled=!state.recording&&(!fresh||p.accuracy>100||track().length>=6000);$('recordButton').textContent=state.recording?'Stop recording':'Start recording';$('recordButton').className='record-button'+(state.recording?' recording':'');$('recordBadge').textContent=state.recording?'RECORDING':'STOPPED';$('exportRoute').disabled=!route().length;$('clearRoute').disabled=!route().length;$('exportTrack').disabled=!track().length;$('clearTrack').disabled=!track().length||state.recording;$('centreButton').disabled=!p;
  if(boat)boat.setIcon(vesselIcon(m.course,!fresh));if(state.mode==='gps'&&p&&stale())status('GPS fix is old · waiting for a fresh position');
  window.dispatchEvent(new CustomEvent('navigation-position-update',{detail:{mode:state.mode,fix:fresh?{...p}:null,speed:fresh?m.speed:null,course:fresh?m.course:null,route:route().map(p=>({...p})),target:state.target,marina:state.marinaTarget?{...state.marinaTarget}:null}}));
 }
 function download(data,name){const url=URL.createObjectURL(new Blob([data],{type:'application/gpx+xml'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
 function toggleAdding(){state.adding=!state.adding;$('addWaypoint').setAttribute('aria-pressed',String(state.adding));$('addWaypoint').textContent=state.adding?'Finish adding':'＋ Add waypoint';$('map').classList.toggle('adding',state.adding);$('routeHint').textContent=state.adding?'Tap the map to add waypoints. Tap Finish adding when done.':'Tap Add waypoint, then tap the map.';}
 if(!window.L||!N){$('mapFallback').textContent='The map library could not load. Check your internet connection, then reload this page.';status('Map unavailable');document.querySelectorAll('button').forEach(b=>b.disabled=true);return;}
 readSaved();
 try{const raw=JSON.parse(localStorage.getItem(window.HelmlorePlanning.ACTIVE)||'null');if(raw&&raw.id!==state.planId){const plan=window.HelmlorePlanning.confirmed(raw);state.routes.gps=plan.points;state.planId=plan.id;state.target=1;state.marinaTarget=null;localStorage.removeItem('helmlore-marina-destination');save();$('routeHint').textContent=plan.name+' · confirmed manual plan, unchecked for safe water. GPS is off.';}if(state.planId){state.target=1;$('routeSource').textContent='CONFIRMED GPS ROUTE';}}catch{$('routeHint').textContent='Confirmed plan could not be loaded. Open Planning to review it.';}
 $('mapFallback').remove();map=L.map('map',{worldCopyJump:true}).setView([HOME.lat,HOME.lon],13);
 base=L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'}).addTo(map);
 seamarks=L.tileLayer('https://tiles.openseamap.org/seamark/{z}/{x}/{y}.png',{maxNativeZoom:18,maxZoom:19,attribution:'Sea marks © <a href="https://www.openseamap.org/">OpenSeaMap</a> contributors'}).addTo(map);
 L.control.scale({metric:true,imperial:false}).addTo(map);accuracyCircle=L.circle([HOME.lat,HOME.lon],{radius:0,color:'#187b9f',weight:1,fillOpacity:.07}).addTo(map);waypointLayer=L.layerGroup().addTo(map);trackLayer=L.layerGroup().addTo(map);routeLine=L.polyline([],{color:'#d18318',weight:3,dashArray:'8 6'}).addTo(map);targetLine=L.polyline([],{color:'#0786a7',weight:2,dashArray:'3 8'}).addTo(map);
 let baseError=false,seaError=false;base.on('tileload',()=>{if(!baseError)$('mapStatus').textContent=seaError?'Base map loaded · some sea marks could not load':'Online map · sea-mark coverage varies by area';});base.on('tileerror',()=>{baseError=true;$('mapStatus').textContent='Some map tiles failed to load. Check the connection; blank areas are missing data.';});seamarks.on('tileerror',()=>{seaError=true;if(!baseError)$('mapStatus').textContent='Base map available · some sea marks could not load';});
 map.on('click',e=>{if(!state.adding)return;if(route().length>=100){$('routeHint').textContent='Route limit is 100 waypoints. Remove a point before adding another.';return;}const p={lat:e.latlng.lat,lon:((e.latlng.lng+540)%360)-180,name:'Waypoint '+(route().length+1)};if(!N.valid(p))return;route().push(p);save();drawRoute();render();});map.on('dragstart',()=>{state.follow=false;$('followButton').setAttribute('aria-pressed','false');});
 $('demoButton').onclick=()=>{if(state.mode==='demo'){resetSource('explore');status('Demo stopped · GPS is off');}else startDemo();};$('gpsButton').onclick=()=>{if(state.mode==='gps'){resetSource('explore');status('GPS stopped · explore or run the demo');}else startGPS();};$('centreButton').onclick=()=>{if(state.fix)map.setView([state.fix.lat,state.fix.lon],map.getZoom());};$('followButton').onclick=()=>{state.follow=!state.follow;$('followButton').setAttribute('aria-pressed',String(state.follow));if(state.follow&&state.fix)map.panTo([state.fix.lat,state.fix.lon]);};$('seamarksToggle').onchange=e=>{if(e.target.checked)seamarks.addTo(map);else map.removeLayer(seamarks);};$('addWaypoint').onclick=toggleAdding;
 $('exampleRoute').onclick=()=>{if(state.routes.demo.length&&!confirm('Replace the saved demo route with the example?'))return;state.routes.demo=[{lat:54.557,lon:-3.628,name:'Demo start'},{lat:54.551,lon:-3.652,name:'Demo waypoint 2'},{lat:54.56,lon:-3.674,name:'Demo waypoint 3'}];save();startDemo();state.target=1;drawRoute();render();map.fitBounds(L.latLngBounds([...route().map(p=>[p.lat,p.lon]),[HOME.lat,HOME.lon]]),{padding:[35,35]});$('routeHint').textContent='Example only · these positions have not been checked for safe navigation.';};
 $('clearRoute').onclick=()=>{if(!confirm('Clear this '+source()+' route?'))return;state.routes[source()]=[];state.target=0;save();drawRoute();render();};$('exportRoute').onclick=()=>download(N.gpx(route(),'route','Helmlore '+source()+' route'),'helmlore-'+source()+'-route.gpx');
 $('recordButton').onclick=()=>{if(state.recording)state.recording=false;else if(!stale()&&state.fix.accuracy<=100){state.segment=Date.now();state.recording=true;const p=state.fix;track().push({lat:p.lat,lon:p.lon,time:p.time,segment:state.segment});save();drawTrack();}render();};$('clearTrack').onclick=()=>{if(state.recording||!confirm('Clear the saved '+source()+' track?'))return;state.tracks[source()]=[];save();drawTrack();render();};$('exportTrack').onclick=()=>download(N.gpx(track(),'track','Helmlore '+source()+' track'),'helmlore-'+source()+'-track.gpx');
 window.addEventListener('online',()=>{$('mapStatus').textContent='Connection restored · reloading visible map tiles';baseError=seaError=false;base.redraw();if(map.hasLayer(seamarks))seamarks.redraw();});window.addEventListener('offline',()=>{$('mapStatus').textContent='Offline · map tiles may be missing. Choose a saved basemap through Offline maps.';});window.addEventListener('pagehide',()=>{state.recording=false;if(state.watch!==null)navigator.geolocation?.clearWatch(state.watch);if(state.demo)clearInterval(state.demo);state.watch=null;state.demo=null;});window.addEventListener('pageshow',e=>{if(e.persisted){resetSource('explore');status('Recording stopped when you left the page. Choose GPS or demo to restart.');}});window.addEventListener('resize',()=>map.invalidateSize());document.addEventListener('visibilitychange',()=>{if(!document.hidden){render();map.invalidateSize();}});
 map.zoomControl?.remove();L.control.zoom({position:'bottomleft'}).addTo(map);
 window.HelmloreChart={
 setMarinaDestination(m){if(!m){state.marinaTarget=null;render();return;}if(!N.valid(m))return;state.marinaTarget={lat:m.lat,lon:m.lon,name:String(m.name||'Marina').slice(0,80)};if(state.adding)toggleAdding();render();},
 getPosition(){const fresh=state.fix&&!stale()&&state.fix.accuracy<=100;return {mode:state.mode,fix:fresh?{...state.fix}:null,speed:fresh?state.motion.speed:null};},
 startGPS(){if(state.mode!=='gps')startGPS();}
 };
 window.dispatchEvent(new CustomEvent("navigation-map-ready",{detail:{map,baseLayer:base,seamarksLayer:seamarks}}));
 if(state.planId&&route().length>1)map.fitBounds(route().map(p=>[p.lat,p.lon]),{padding:[180,180],maxZoom:14});
 drawRoute();drawTrack();render();setInterval(render,1000);
})();
