/* Explicit full-chart download. No external map tiles are bulk downloaded. */
(()=>{'use strict';const $=id=>document.getElementById(id),P=window.HelmloreChartPack;let current=null,available=null,controller=null,ready=false;const size=b=>(b/1048576).toFixed(1)+' MB';
function note(s){$('chartPackStatus').textContent=s;}
async function saved(){current=await P.active();$('chartPackInstalled').textContent=current?'Saved: '+current.release+' · '+size(current.bytes)+' · '+new Date(current.installedAt).toLocaleDateString():'No chart downloaded on this device.';$('removeChartPack').disabled=!current;if(current){window.dispatchEvent(new CustomEvent('navigation-saved-chart',{detail:current}));}}
async function check(){if(!navigator.onLine){note('Connect to check for chart updates. Your saved chart remains available.');return;}try{const r=await fetch('data/navigation/offline-chart-manifest.json?chart-download=manifest',{cache:'no-store'});if(!r.ok)throw Error('Manifest unavailable');available=P.validate(await r.json());$('downloadChartPack').disabled=!ready; $('downloadChartPack').textContent=current?.id===available.id?'Download again':current?'Download chart update':'Download UK & Ireland';note((current?.id===available.id?'Latest published package is saved. ':'Available: '+available.release+'. ')+size(available.bytes)+' · '+available.files.length.toLocaleString()+' files. Coastline and depths: 2011; sea marks: '+available.sourceDates.seamarks+'.');}catch(e){note('Update check failed: '+e.message);}}
$('checkChartPack').onclick=check;
$('downloadChartPack').onclick=async()=>{if(!available||controller)return;controller=new AbortController();$('downloadChartPack').disabled=true;$('checkChartPack').disabled=true;$('removeChartPack').disabled=true;$('cancelChartPack').hidden=false;const bar=$('chartPackProgress');bar.hidden=false;bar.value=0;try{await navigator.storage?.persist?.();const estimate=await navigator.storage?.estimate?.();if(estimate?.quota&&estimate.quota-estimate.usage<available.bytes*1.15)throw Error('Not enough browser storage for this chart.');await P.install(available,{base:new URL('./',location.href).href,signal:controller.signal,onProgress:p=>{bar.value=p.bytes/p.totalBytes*100;note('Downloading '+size(p.bytes)+' / '+size(p.totalBytes)+' · '+p.done.toLocaleString()+' / '+p.total.toLocaleString()+' files. Keep this page open.');}});await saved();note('Chart verified and saved. Reload to use the complete saved package.');$('reloadChartPack').hidden=false;}catch(e){note(e.name==='AbortError'?'Download cancelled. The previously saved chart is unchanged.':'Chart was not installed: '+e.message+'. The previously saved chart is unchanged.');}finally{controller=null;$('cancelChartPack').hidden=true;bar.hidden=true;$('checkChartPack').disabled=false;$('downloadChartPack').disabled=!available;$('removeChartPack').disabled=!current;}};
$('cancelChartPack').onclick=()=>controller?.abort();$('reloadChartPack').onclick=()=>location.reload();
$('removeChartPack').onclick=async()=>{if(!current||!confirm('Remove the saved chart from this device? Routes, waypoints and trips will stay saved.'))return;const meta=await caches.open(P.META);await meta.delete(P.KEY);await caches.delete(current.name);current=null;await saved();note('Saved chart removed. Reload to use online charts.');$('reloadChartPack').hidden=false;};
window.addEventListener('beforeunload',e=>{if(controller){e.preventDefault();e.returnValue='';}});
window.addEventListener('navigation-offline-ready',async()=>{ready=true;await saved();await check();});
})();
