/* Personal comfort comparison, not a vessel capability or passage safety model. */
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.HelmloreComfort=api;})(typeof window==='object'?window:globalThis,()=>{'use strict';
const finite=Number.isFinite;
function limits(profile){const height=Number(profile?.waveLimit),period=Number(profile?.periodLimit);return {height:finite(height)&&height>0?height:null,period:finite(period)&&period>0?period:null};}
function classify(height,period,profile){const l=limits(profile);if(!l.height)return {level:'setup',reasons:['Set your wave-height comfort limit']};if(!finite(height)||height<0)return {level:'unknown',reasons:['Wave height unavailable']};const near=height>=l.height*.8,meaningful=height>=Math.min(1,l.height*.5),short=l.period&&meaningful&&finite(period)&&period>0&&period<l.period,reasons=[];if(height>l.height)reasons.push('Height above your limit');else if(near)reasons.push('Height near your limit');if(short)reasons.push('Short period in appreciable waves');if(height>l.height||(near&&short))return {level:'above',reasons};if(l.period&&meaningful&&(!finite(period)||period<=0))return {level:near?'near':'unknown',reasons:[...reasons,'Wave period unavailable']};if(near||short)return {level:'near',reasons};return {level:'within',reasons:[]};}
function value(m,key,t){const i=m?.hourly?.time?.indexOf(t);const v=i>=0?m.hourly[key]?.[i]:null;return finite(v)?v:null;}
function summarize(pack,profile,now=Date.now(),allowed=()=>true){const l=limits(profile),start=Math.floor(now/3600000)*3600,end=Math.min(start+72*3600,pack?.end??start),times=(pack?.times||[]).filter(t=>t>=start&&t<end),rank={unknown:0,within:1,near:2,above:3},hours=[],windows=[];let missing=0,total=0,maxHeight=null,minPeriod=null,maxWind=null;
if(!l.height)return {level:'setup',start,end,hours,windows,limits:l};
if(!pack||pack.end<=start||!times.length)return {level:'unknown',start,end,hours,windows,limits:l,missing:1,total:1,coverage:0};
const indexes=(pack.points||[]).map((p,i)=>allowed(p)?i:-1).filter(i=>i>=0);
for(const t of times){let worst={level:'unknown',reasons:['Marine data unavailable']},location=null,known=0;for(const i of indexes){const m=pack.marine?.[i],h=value(m,'wave_height',t),p=value(m,'wave_period',t),result=classify(h,p,profile);total++;if(result.level==='unknown'||(l.period&&h>=Math.min(1,l.height*.5)&&(!finite(p)||p<=0)))missing++;if(result.level!=='unknown')known++;if(finite(h))maxHeight=maxHeight===null?h:Math.max(maxHeight,h);if(finite(p)&&p>0&&finite(h)&&h>=Math.min(1,l.height*.5))minPeriod=minPeriod===null?p:Math.min(minPeriod,p);const w=value(pack.weather?.[i],'wind_speed_10m',t);if(pack.seaOnly&&finite(w))maxWind=maxWind===null?w:Math.max(maxWind,w);if(rank[result.level]>rank[worst.level]){worst=result;location=pack.points[i];}}
const row={time:t,end:Math.min(t+3600,end),...worst,location,known};hours.push(row);if(['near','above'].includes(row.level)){const last=windows.at(-1);if(last&&last.level===row.level&&last.end===t){last.end=row.end;row.reasons.forEach(r=>{if(!last.reasons.includes(r))last.reasons.push(r);});}else windows.push({start:t,end:row.end,level:row.level,reasons:[...row.reasons],location});}}
if(!indexes.length){missing=times.length;total=times.length;}
const worst=hours.reduce((level,h)=>rank[h.level]>rank[level]?h.level:level,'unknown'),coverage=Math.max(0,(end-start)/3600),gaps=hours.length<coverage,level=worst==='within'&&(missing>0||gaps||!indexes.length)?'unknown':worst;
return {level,start,end,hours,windows,limits:l,missing,total,coverage,maxHeight,minPeriod,maxWind,partial:coverage<72||gaps||missing>0,downloadedAt:pack.downloadedAt};}
return {limits,classify,summarize};});