/* Ocean-model current trails. Animation speed is illustrative, not a travel scale. */
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.HelmloreCurrentFlow=api;})(typeof window==='object'?window:globalThis,()=>{'use strict';
function vector(speed,direction){if(!Number.isFinite(speed)||speed<0||!Number.isFinite(direction))return null;const a=direction*Math.PI/180;return {x:Math.sin(a)*speed,y:-Math.cos(a)*speed};}
function field(points,x,y,radius){const near=points.map(p=>({...p,d:Math.hypot(p.x-x,p.y-y)})).filter(p=>p.d<=radius).sort((a,b)=>a.d-b.d).slice(0,4);if(!near.length)return null;let weight=0,vx=0,vy=0;for(const p of near){const w=1/Math.max(20,p.d)**2;weight+=w;vx+=p.v.x*w;vy+=p.v.y*w;}return {x:vx/weight,y:vy/weight};}
function create(map,C){const canvas=document.createElement('canvas');canvas.className='current-flow-canvas';canvas.setAttribute('aria-hidden','true');map.getPanes().overlayPane.append(canvas);const ctx=canvas.getContext('2d'),reduced=window.matchMedia?.('(prefers-reduced-motion: reduce)'),state={enabled:false,particles:[],frame:null,last:0,width:0,height:0,mask:new Map(),bounds:null};
function stop(){if(state.frame!==null)cancelAnimationFrame(state.frame);state.frame=null;state.last=0;}
function sea(x,y){const key=Math.round(x/6)+','+Math.round(y/6);if(state.mask.has(key))return state.mask.get(key);const p=map.containerPointToLatLng([x,y]),b=state.bounds,result=(!b||(p.lat>=b.south&&p.lat<=b.north&&p.lng>=b.west&&p.lng<=b.east))&&C.isSea({lat:p.lat,lon:p.lng});state.mask.set(key,result);return result;}
function paint(time){state.frame=null;if(!ctx||!state.enabled||document.hidden)return;const dt=state.last?Math.min(.06,(time-state.last)/1000):0;state.last=time;ctx.clearRect(0,0,state.width,state.height);const night=document.body.dataset.theme==='night';ctx.lineWidth=1.6;ctx.lineCap='round';for(const p of state.particles){if(!reduced?.matches)p.distance=(p.distance+dt*p.speed)%p.length;const x=p.x+p.vx*p.distance,y=p.y+p.vy*p.distance,tail=15;if(!sea(x,y)||!sea(x-p.vx*tail,y-p.vy*tail))continue;ctx.strokeStyle=night?'rgba(98,191,235,.7)':'rgba(17,109,169,.8)';ctx.beginPath();ctx.moveTo(x-p.vx*tail,y-p.vy*tail);ctx.lineTo(x,y);ctx.stroke();ctx.fillStyle=night?'#b8e7ff':'#0c609b';ctx.beginPath();ctx.arc(x,y,2.1,0,Math.PI*2);ctx.fill();}if(!reduced?.matches)state.frame=requestAnimationFrame(paint);}
function update(pack,t,enabled){stop();state.enabled=!!enabled;canvas.hidden=!enabled;const size=map.getSize(),ratio=Math.min(window.devicePixelRatio||1,2);state.width=size.x;state.height=size.y;canvas.width=Math.round(size.x*ratio);canvas.height=Math.round(size.y*ratio);canvas.style.width=size.x+'px';canvas.style.height=size.y+'px';const top=map.containerPointToLayerPoint([0,0]);canvas.style.transform='translate('+top.x+'px,'+top.y+'px)';ctx?.setTransform(ratio,0,0,ratio,0,0);state.particles=[];state.mask.clear();state.bounds=pack?.bounds;if(!enabled||!pack||!ctx)return;const points=[];for(const m of pack.marine||[]){const p={lat:m?.latitude,lon:m?.longitude};if(!C.isSea(p)||p.lat<pack.bounds.south||p.lat>pack.bounds.north||p.lon<pack.bounds.west||p.lon>pack.bounds.east)continue;const v=vector(C.value(m,'ocean_current_velocity',t),C.value(m,'ocean_current_direction',t));if(!v)continue;const q=map.latLngToContainerPoint([p.lat,p.lon]);if(!points.some(n=>Math.hypot(n.x-q.x,n.y-q.y)<3))points.push({x:q.x,y:q.y,v});}
const diagonal=Math.hypot(size.x,size.y),radius=Math.min(240,Math.max(90,diagonal/Math.sqrt(Math.max(1,points.length))*.8));for(let y=16;y<size.y;y+=34)for(let x=16;x<size.x;x+=34){const geo=map.containerPointToLatLng([x,y]);if(geo.lat<pack.bounds.south||geo.lat>pack.bounds.north||geo.lng<pack.bounds.west||geo.lng>pack.bounds.east||!C.isSea({lat:geo.lat,lon:geo.lng}))continue;const v=field(points,x,y,radius);if(!v)continue;const magnitude=Math.hypot(v.x,v.y);if(magnitude<.03)continue;const length=22+Math.min(42,magnitude*18);state.particles.push({x:x-v.x/magnitude*length/2,y:y-v.y/magnitude*length/2,vx:v.x/magnitude,vy:v.y/magnitude,distance:((x*13+y*7)%100)/100*length,length,speed:9+Math.min(28,magnitude*12)});}
state.frame=requestAnimationFrame(paint);}
document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();else if(state.enabled)state.frame=requestAnimationFrame(paint);});reduced?.addEventListener?.('change',()=>{stop();if(state.enabled)state.frame=requestAnimationFrame(paint);});return {update};}
return {vector,field,create};});