/* Device-local trip recording. Missing fixes remain explicit gaps. */
(function(root,factory){const N=typeof module==='object'&&module.exports?require('./core.js'):root.HelmloreNav;const api=factory(N);if(typeof module==='object'&&module.exports)module.exports=api;else root.HelmloreLogbook=api;})(typeof globalThis!=='undefined'?globalThis:this,function(N){
'use strict';const KEY='helmlore-trip-logbook-v1',intervals=[5,15,30,60],fresh=(f,now)=>N.valid(f)&&Number.isFinite(f.time)&&Number.isFinite(f.accuracy)&&f.accuracy>=0&&f.accuracy<=100&&now-f.time>=-5000&&now-f.time<=15000;
const value=v=>Number.isFinite(v)?v:null;
function remaining(s){if(!N.valid(s.fix))return null;if(s.marina&&N.valid(s.marina))return N.distance(s.fix,s.marina)/1852;const r=s.route||[],i=s.target;if(!Number.isInteger(i)||!N.valid(r[i]))return null;let m=N.distance(s.fix,r[i]);for(let j=i+1;j<r.length;j++)if(N.valid(r[j]))m+=N.distance(r[j-1],r[j]);return m/1852;}
function entry(trip,s,at,kind,note=''){const ok=s.mode===trip.source&&fresh(s.fix,at)&&Math.abs(s.fix.time-at)<=15000,left=ok?remaining(s):null,speed=ok?value(s.speed):null;return{scheduledAt:at,fixAt:ok?s.fix.time:null,lat:ok?s.fix.lat:null,lon:ok?s.fix.lon:null,accuracy:ok?s.fix.accuracy:null,sog:speed,cog:ok?value(s.course):null,travelled:trip.distanceNM,remaining:left,remainingKind:s.marina?'Direct to marina':'Via remaining waypoints',next:s.marina?.name||s.route?.[s.target]?.name||'',etaMinutes:left!==null&&speed>=0.5?left/speed*60:null,kind,note:String(note).slice(0,500),gap:!ok};}
function begin(s,name,minutes,now){if(!intervals.includes(minutes))throw Error('Choose a supported interval.');if(!['gps','demo'].includes(s.mode)||!fresh(s.fix,now))throw Error('Choose GPS or demo and wait for an accurate position.');const step=minutes*60000,t={id:String(now),name:String(name||'Passage').trim().slice(0,80),source:s.mode,interval:minutes,startedAt:now,endedAt:null,reason:'',distanceNM:0,distanceIncomplete:false,route:(s.route||[]).filter(N.valid).map(p=>({lat:p.lat,lon:p.lon,name:p.name})),vessel:s.vessel||null,track:[],entries:[],nextAt:(Math.floor(now/step)+1)*step,lastFix:null,active:true};tick(t,s,now);t.entries.push(entry(t,s,now,'start'));return t;}
function tick(t,s,now){if(!t.active)return false;if(s.mode!==t.source){stop(t,s,now,'Position source changed');return true;}const f=s.fix;if(!fresh(f,now)&&t.lastFix){t.distanceIncomplete=true;t.lastFix=null;}if(fresh(f,now)&&(!t.lastFix||f.time>t.lastFix.time)){const previous=t.lastFix;const connected=previous&&f.time-previous.time<=60000,d=connected?N.distance(previous,f):0,noise=Math.max(3,f.accuracy,previous?.accuracy||0),moved=d>noise;
if(connected&&moved)t.distanceNM+=d/1852;else if(previous&&!connected)t.distanceIncomplete=true;
if(!previous||!connected||moved||f.time-previous.time>=30000){t.lastFix={lat:f.lat,lon:f.lon,time:f.time,accuracy:f.accuracy};const last=t.track[t.track.length-1];t.track.push({lat:f.lat,lon:f.lon,time:f.time,segment:connected?(last?.segment||t.startedAt):f.time,speed:value(s.speed)});}}

let changed=false;const step=t.interval*60000;while(t.nextAt<=now&&t.entries.length<2000){t.entries.push(entry(t,s,t.nextAt,'scheduled'));t.nextAt+=step;changed=true;}if(t.track.length>=8000||t.entries.length>=2000)stop(t,s,now,'Recording limit reached; export this trip and start another');return changed;}
function stop(t,s,now,reason='Stopped by user'){if(!t.active)return;t.entries.push(entry(t,s,now,'stop'));t.endedAt=now;t.reason=reason;t.active=false;}
function csv(t){const quote=v=>'"'+String(v??'').replace(/"/g,'""')+'"';const iso=v=>v==null?'':new Date(v).toISOString();const rows=[['Scheduled time UTC','GPS fix time UTC','Latitude','Longitude','Accuracy m','SOG kn','COG true deg','Distance travelled NM','Distance remaining NM','Remaining basis','Next waypoint','ETA minutes','Entry type','GPS gap','Note']];for(const e of t.entries)rows.push([iso(e.scheduledAt),iso(e.fixAt),e.lat,e.lon,e.accuracy,e.sog,e.cog,e.travelled,e.remaining,e.remainingKind,e.next,e.etaMinutes,e.kind,e.gap?'YES':'NO',e.note]);return rows.map(row=>row.map(quote).join(',')).join('\r\n');}
return{KEY,intervals,fresh,remaining,entry,begin,tick,stop,csv};
});
