/* Named trip history, separate from legacy tracks and from account storage. */
(()=>{'use strict';const C=window.HelmloreLogbook,N=window.HelmloreNav,$=id=>document.getElementById(id);let trips=[],active=null,selected=null,map,layer,snapshot={mode:'explore',fix:null},lastSave=0,error='';
function status(text){$('tripStatus').textContent=text;}
function save(){try{localStorage.setItem(C.KEY,JSON.stringify(trips));lastSave=Date.now();return true;}catch{error='Could not save to this browser. Export the trip before leaving.';status(error);if(active){C.stop(active,snapshot,Date.now(),'Browser storage failed');active=null;}return false;}}
try{const raw=JSON.parse(localStorage.getItem(C.KEY)||'[]');if(!Array.isArray(raw)||raw.length>50)throw Error();trips=raw.filter(t=>t&&typeof t.id==='string'&&Array.isArray(t.track)&&Array.isArray(t.entries)&&['gps','demo'].includes(t.source)).map(t=>({...t,track:t.track.filter(p=>N.valid(p)&&Number.isFinite(p.time)).slice(0,8000),entries:t.entries.filter(e=>Number.isFinite(e.scheduledAt)).slice(0,2001)}));for(const t of trips)if(t.active){t.active=false;t.endedAt=t.track.at(-1)?.time||t.startedAt;t.reason='Previous session interrupted; recording was not resumed';t.distanceIncomplete=true;}selected=trips.at(-1)?.id;save();}catch{error='Saved logbook could not be read. Existing storage has been left untouched.';status(error);}
const current=()=>trips.find(t=>t.id===selected);
const time=x=>new Date(x).toLocaleString('en-GB',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit',second:'2-digit',timeZoneName:'short'});
const number=(n,u)=>Number.isFinite(n)?n.toFixed(2)+' '+u:'—';
function download(data,name,type){const url=URL.createObjectURL(new Blob([data],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
function draw(){if(!layer)return;layer.clearLayers();const t=current();if(!t)return;let groups=[];for(const p of t.track){let g=groups.at(-1);if(!g||g[0].segment!==p.segment)groups.push(g=[]);g.push(p);}for(const g of groups)if(g.length>1)L.polyline(g.map(p=>[p.lat,p.lon]),{color:t.source==='demo'?'#e3a135':'#ad78d6',weight:4}).addTo(layer);}
function history(){const root=$('tripHistory');root.replaceChildren();for(const t of [...trips].reverse()){const b=document.createElement('button');b.className='trip-card';b.setAttribute('aria-pressed',String(t.id===selected));b.textContent=t.name+' · '+(t.source==='demo'?'SIMULATED':'GPS')+'\n'+time(t.startedAt)+' · '+number(t.distanceNM,'NM')+(t.active?' · RECORDING':'');b.onclick=()=>{selected=t.id;details();history();draw();};root.append(b);}}
function details(){const t=current();$('tripDetail').hidden=!t;if(!t)return;$('tripTitle').textContent=t.name+' · '+(t.source==='demo'?'SIMULATED':'GPS');$('tripSummary').textContent=number(t.distanceNM,'NM')+' · '+Math.round(((t.endedAt||Date.now())-t.startedAt)/60000)+' minutes · '+t.entries.length+' entries'+(t.distanceIncomplete?' · distance incomplete across GPS gaps':'')+(t.reason?' · '+t.reason:'');const tbody=$('tripEntries');tbody.replaceChildren();for(const e of [...t.entries].reverse()){const tr=document.createElement('tr');const coord=N.valid(e)?N.coordinate(e.lat,true)+' / '+N.coordinate(e.lon,false):'GPS unavailable';for(const text of [time(e.scheduledAt)+(e.kind==='scheduled'?'':' · '+e.kind),e.fixAt?time(e.fixAt):'No fix',coord,number(e.sog,'kn'),Number.isFinite(e.cog)?Math.round(e.cog)+'° T':'—',number(e.travelled,'NM'),number(e.remaining,'NM')+(e.remaining!==null?' · '+e.remainingKind:''),e.next||'—',Number.isFinite(e.etaMinutes)?Math.round(e.etaMinutes)+' min':'—',e.note||'']){const td=document.createElement('td');td.textContent=text;tr.append(td);}tbody.append(tr);}}
function controls(){const fresh=C.fresh(snapshot.fix,Date.now());$('tripRecord').disabled=!active&&(!fresh||!['gps','demo'].includes(snapshot.mode)||trips.length>=50||!!error);$('tripRecord').textContent=active?'Stop & save trip':'Start recording trip';$('tripRecord').setAttribute('aria-pressed',String(!!active));$('tripName').disabled=$('tripInterval').disabled=!!active;$('tripManual').disabled=!active;$('tripRecordingBadge').hidden=!active;$('tripRecordingBadge').textContent=active?(active.source==='demo'?'● DEMO RECORDING':'● TRIP RECORDING'):'';if(!error)status(active?'Recording '+active.name+' · '+(fresh?'position available':'GPS gap · waiting for an accurate fix')+' · next log '+time(active.nextAt):fresh?'Ready to record '+(snapshot.mode==='demo'?'a simulated trip.':'your trip.'):'Use GPS or Run demo in Controls, then start a trip.');}
function end(reason){if(!active)return;C.tick(active,snapshot,Date.now());C.stop(active,snapshot,Date.now(),reason);selected=active.id;active=null;save();controls();history();details();draw();}
$('tripRecord').onclick=()=>{if(active){end('Stopped by user');return;}try{const vessel=JSON.parse(localStorage.getItem(window.HelmlorePlanning.PROFILE)||'null');const trip=C.begin({...snapshot,vessel},$('tripName').value,Number($('tripInterval').value),Date.now());trips.push(trip);active=trip;selected=trip.id;save();controls();history();details();draw();}catch(e){status(e.message);}};
$('tripManual').onclick=()=>{if(!active)return;C.tick(active,snapshot,Date.now());active.entries.push(C.entry(active,snapshot,Date.now(),'manual',$('tripNote').value));$('tripNote').value='';save();details();history();};
$('tripCSV').onclick=()=>{const t=current();if(t)download(C.csv(t),'helmlore-trip-'+t.id+'.csv','text/csv;charset=utf-8');};$('tripGPX').onclick=()=>{const t=current();if(t)download(N.gpx(t.track,'track',t.name+(t.source==='demo'?' (simulated)':'')),'helmlore-trip-'+t.id+'.gpx','application/gpx+xml');};$('tripJSON').onclick=()=>{const t=current();if(t)download(JSON.stringify(t,null,2),'helmlore-trip-'+t.id+'.json','application/json');};$('tripShow').onclick=()=>{const t=current();if(t?.track.length){draw();map.fitBounds(t.track.map(p=>[p.lat,p.lon]),{padding:[100,100],maxZoom:15});}};
window.addEventListener('navigation-position-update',e=>{snapshot=e.detail;if(active){const changed=C.tick(active,snapshot,Date.now());if(!active.active){active=null;save();history();details();}else if(changed||Date.now()-lastSave>=10000){save();history();details();draw();}}controls();});
window.addEventListener('navigation-panel-open',e=>{if(e.detail.name==='logbook'){history();details();controls();draw();}});window.addEventListener('navigation-map-ready',e=>{map=e.detail.map;layer=L.layerGroup().addTo(map);history();details();controls();});window.addEventListener('pagehide',()=>end('Left navigation page'));document.addEventListener('visibilitychange',()=>{if(document.hidden)end('Navigation moved to background');});
})();
