/* Offline basemaps from self-hosted, permitted Protomaps extracts. No tile scraping. */
(()=>{'use strict';const $=id=>document.getElementById(id);let map,base,seamarks,db,layer,active,viewEpoch=0,busy=false,abort,outline;
const SELECTED='helmlore-selected-offline-map-v1',DATE='2026-10-03';
const packs=window.HelmloreMapPacks;
function message(s){$('mapDownloadStatus').textContent=s;}
function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open('helmlore-offline-maps-v1',1);r.onupgradeneeded=()=>r.result.createObjectStore('packs',{keyPath:'id'});r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);r.onblocked=()=>reject(Error('Close other Helmlore tabs and retry.'));});}
function read(id){return new Promise((resolve,reject)=>{const t=db.transaction('packs','readonly'),r=t.objectStore('packs').get(id);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
function write(record){return new Promise((resolve,reject)=>{const t=db.transaction('packs','readwrite');t.objectStore('packs').put(record);t.oncomplete=resolve;t.onerror=()=>reject(t.error);t.onabort=()=>reject(t.error||Error('Storage update failed'));});}
function remove(id){return new Promise((resolve,reject)=>{const t=db.transaction('packs','readwrite');t.objectStore('packs').delete(id);t.oncomplete=resolve;t.onerror=()=>reject(t.error);});}
const reader=r=>new pmtiles.PMTiles(new pmtiles.FileSource(new File([r.blob],r.id+'.pmtiles')));
function controls(local){for(const id of ['seamarksToggle','seaVisible'])if($(id))$(id).disabled=local;}
function coverage(){const el=$('localMapStatus');el.hidden=!active;if(!active)return;const b=active.bounds,c=map.getCenter(),v=map.getBounds(),within=c.lat>=b[1]&&c.lat<=b[3]&&c.lng>=b[0]&&c.lng<=b[2],full=v.getSouth()>=b[1]&&v.getNorth()<=b[3]&&v.getWest()>=b[0]&&v.getEast()<=b[2];el.textContent='LOCAL BASEMAP · '+active.name+' · '+(!within?'Outside saved area':!full?'Some visible areas are outside this pack':'Saved area available')+' · no chart depths';el.dataset.missing=String(!within||!full);}
function online(){viewEpoch++;if(layer){map.removeLayer(layer);layer=null;}active=null;controls(false);base.addTo(map);if(seamarks&&(!$('seamarksToggle')||$('seamarksToggle').checked))seamarks.addTo(map);try{localStorage.removeItem(SELECTED);}catch{}coverage();message('Online map selected. Internet is required for its tiles and sea marks.');cards();}
async function use(p,fit=false){const token=++viewEpoch;try{const r=await read(p.id);if(!r?.blob)throw Error('Download this map first.');const pm=reader(r),h=await pm.getHeader();if(token!==viewEpoch)return;if(h.tileType!==1)throw Error('This is not a supported vector basemap.');const next=protomapsL.leafletLayer({url:pm,flavor:document.body.dataset.theme==='night'?'dark':'light',lang:'en',maxDataZoom:p.maxZoom,levelDiff:0,maxZoom:19,noWrap:true,bounds:[[p.bounds[1],p.bounds[0]],[p.bounds[3],p.bounds[2]]],attribution:'<a href="https://protomaps.com/">Protomaps</a> · © <a href="https://www.openstreetmap.org/copyright">OpenStreetMap contributors</a> · data '+DATE});
if(layer)map.removeLayer(layer);map.removeLayer(base);if(seamarks)map.removeLayer(seamarks);layer=next;active=p;controls(true);next.addTo(map);try{localStorage.setItem(SELECTED,p.id);}catch{}if(fit)map.fitBounds([[p.bounds[1],p.bounds[0]],[p.bounds[3],p.bounds[2]]],{padding:[80,150],maxZoom:13});message(p.name+' is displayed from this device. Coastline and places only; no depth, hazard or offline sea-mark layer.');coverage();cards();}catch(e){message('Saved map could not open: '+e.message+'. Your other maps are retained.');}}
async function download(p){if(busy||!db)return;if(!navigator.onLine){message('Connect to download a map. Existing saved maps are still available.');return;}busy=true;abort=new AbortController();$('cancelMapDownload').hidden=false;cards();message('Downloading '+p.name+'…');try{const response=await fetch(p.url,{signal:abort.signal});if(!response.ok)throw Error('Download service returned '+response.status);const chunks=[],stream=response.body?.getReader();let bytes=0;if(stream){while(true){const part=await stream.read();if(part.done)break;bytes+=part.value.byteLength;if(bytes>p.bytes)throw Error('Unexpected download size');chunks.push(part.value);message('Downloading '+p.name+' · '+Math.round(bytes/p.bytes*100)+'% · '+(bytes/1048576).toFixed(1)+' / '+(p.bytes/1048576).toFixed(1)+' MB');}}else{const b=await response.arrayBuffer();bytes=b.byteLength;chunks.push(b);}if(bytes!==p.bytes)throw Error('Incomplete map download');const blob=new Blob(chunks,{type:'application/octet-stream'}),digest=await crypto.subtle.digest('SHA-256',await blob.arrayBuffer()),hex=Array.from(new Uint8Array(digest),n=>n.toString(16).padStart(2,'0')).join('');if(hex!==p.sha256)throw Error('Map integrity check failed');const r={id:p.id,blob,bytes,downloadedAt:Date.now(),version:DATE};await reader(r).getHeader();await write(r);message(p.name+' saved on this device.');await use(p,true);}catch(e){message(e.name==='AbortError'?'Download cancelled. Existing saved maps are retained.':'Map download failed: '+e.message+'. Existing saved maps are retained.');}finally{busy=false;abort=null;$('cancelMapDownload').hidden=true;cards();}}
async function cards(){const el=$('offlineMapPacks');if(!db)return;const records=await Promise.all(packs.map(p=>read(p.id)));el.replaceChildren();packs.forEach((p,i)=>{const r=records[i],card=document.createElement('section'),h=document.createElement('h3'),info=document.createElement('p'),status=document.createElement('p'),buttons=document.createElement('div');card.className='offline-map-card';h.textContent=p.name;info.className='helper';info.textContent=p.description+' · '+(p.bytes/1048576).toFixed(1)+' MB';status.className='helper';status.textContent=r?'Saved '+new Date(r.downloadedAt).toLocaleDateString('en-GB')+(active?.id===p.id?' · IN USE':'')+(r.version!==DATE?' · older data':''):'Not downloaded';buttons.className='button-row';const get=document.createElement('button');get.textContent=r?'Download again':'Download map';get.disabled=busy;get.onclick=()=>download(p);buttons.append(get);if(r){const show=document.createElement('button'),del=document.createElement('button');show.textContent='Use saved map';show.disabled=busy;show.onclick=()=>use(p,true);del.textContent='Remove';del.disabled=busy;del.setAttribute('aria-label','Remove saved map '+p.name);del.onclick=async()=>{try{await remove(p.id);if(active?.id===p.id)online();message(p.name+' removed from this device.');cards();}catch{message('Could not remove the saved map.');}};buttons.append(show,del);}const preview=document.createElement('button');preview.textContent='Show coverage';preview.disabled=busy;preview.onclick=()=>{outline.clearLayers();L.rectangle([[p.bounds[1],p.bounds[0]],[p.bounds[3],p.bounds[2]]],{color:'#efa737',fillOpacity:.04,interactive:false}).addTo(outline);map.fitBounds([[p.bounds[1],p.bounds[0]],[p.bounds[3],p.bounds[2]]],{padding:[80,140]});};buttons.append(preview);card.append(h,info,status,buttons);el.append(card);});}
window.addEventListener('navigation-map-ready',async e=>{map=e.detail.map;base=e.detail.baseLayer;seamarks=e.detail.seamarksLayer;if(!base)return;outline=L.layerGroup().addTo(map);const status=document.createElement('div');status.id='localMapStatus';status.className='local-map-status';status.hidden=true;status.setAttribute('role','status');document.body.append(status);map.on('moveend',coverage);$('onlineMapButton').onclick=online;$('cancelMapDownload').onclick=()=>abort?.abort();
try{db=await openDB();await cards();let id;try{id=localStorage.getItem(SELECTED);}catch{}const p=packs.find(p=>p.id===id);if(p&&await read(p.id))await use(p);else if(!navigator.onLine){const rows=await Promise.all(packs.map(p=>read(p.id)));const i=rows.findIndex(Boolean);if(i>=0)await use(packs[i]);else message('No maps saved. Connect and download an area before going offline.');}else message('Choose an area to download while online. Saved maps work in both Navigation and Planning.');
if(navigator.storage?.estimate){const estimate=await navigator.storage.estimate();$('offlineMapStorage').textContent='Browser storage: '+((estimate.usage||0)/1048576).toFixed(0)+' MB used of '+((estimate.quota||0)/1048576).toFixed(0)+' MB. Browser or iPad storage cleanup can remove downloads; check saved status before departure.';}
}catch(e){message('Offline map storage unavailable: '+e.message+'. Online maps still work.');}
new MutationObserver(()=>{if(active&&layer){const p=active;use(p);}}).observe(document.body,{attributes:true,attributeFilter:['data-theme']});window.addEventListener('offline',async()=>{coverage();if(active)return;try{const c=map.getCenter(),choices=[...packs].sort((a,b)=>b.maxZoom-a.maxZoom);for(const p of choices){const b=p.bounds;if(c.lat>=b[1]&&c.lat<=b[3]&&c.lng>=b[0]&&c.lng<=b[2]&&await read(p.id)){await use(p);return;}}message('Offline. No downloaded pack covers the map centre; select a saved area through Offline maps.');}catch{message('Offline map storage could not be read.');}});window.addEventListener('online',coverage);});
})();
