/* Search the versioned marina library locally; GPS is never sent to a lookup service. */
(()=>{'use strict';const $=id=>document.getElementById(id),N=window.HelmloreNav,M=window.HelmloreMarinas,KEY='helmlore-marina-destination';let map,records=[],loaded=false,loading=false,selected=null,marker=null,limit=50;
const position=()=>window.HelmloreChart?.getPosition()||{mode:'explore',fix:null,speed:null};
function distanceText(m,p){if(!p.fix)return '';return (N.distance(p.fix,m)/1852).toFixed(2)+' NM direct'+(p.mode==='demo'?' · DEMO':'');}
function updateDistance(){if(!selected)return;const p=position();if(!p.fix){$('marinaDistance').textContent=p.mode==='gps'?'Waiting for a fresh GPS fix with accuracy within 100 m.':'Enable GPS to show distance and bearing from your position.';return;}const distance=N.distance(p.fix,selected),bearing=String(Math.round(N.bearing(p.fix,selected))%360).padStart(3,'0')+'° T';const minutes=Number.isFinite(p.speed)&&p.speed>=.5?distance/1852/p.speed*60:null;const eta=minutes===null?'Time unavailable without reliable speed':Math.round(minutes)+' min at current speed';$('marinaDistance').textContent=(p.mode==='demo'?'DEMO POSITION · ':'GPS · ')+(distance/1852).toFixed(2)+' NM direct · '+bearing+' · '+eta;}
function select(m){selected=m;window.HelmloreChart.setMarinaDestination(m);try{localStorage.setItem(KEY,m.id);}catch{}$('marinaDestination').hidden=false;$('marinaDestinationName').textContent=m.name;$('marinaDestinationCoords').textContent=N.coordinate(m.lat,true)+' · '+N.coordinate(m.lon,false)+' · '+(m.coordinateBasis==='osm-node'?'Mapped point':'Mapped area centre');marker?.remove();const node=document.createElement('div'),title=document.createElement('strong'),text=document.createElement('p');title.textContent=m.name;text.textContent='Marina location · not a verified entrance';node.append(title,text);marker=L.marker([m.lat,m.lon],{icon:L.divIcon({className:'marina-icon',html:'⚓',iconSize:[28,28],iconAnchor:[14,14]}),zIndexOffset:900}).addTo(map).bindPopup(node);map.setView([m.lat,m.lon],14);updateDistance();}
function results(){const matches=M.search(records,$('marinaSearch').value),p=position();matches.sort((a,b)=>p.fix?N.distance(p.fix,a)-N.distance(p.fix,b):a.name.localeCompare(b.name,'en'));$('marinaResultsCount').textContent=matches.length+' matching locations · showing '+Math.min(limit,matches.length)+(p.fix?(p.mode==='demo'?' · nearest to DEMO position':' · nearest to GPS position'):' · alphabetical');const list=$('marinaResults');list.replaceChildren();matches.slice(0,limit).forEach(m=>{const b=document.createElement('button'),name=document.createElement('strong'),detail=document.createElement('small');b.className='marina-result';name.textContent=m.name;detail.textContent=[m.locality,m.postcode,distanceText(m,p),m.access==='private'?'Private access — check with operator':'',m.named?null:'Name missing from source'].filter(Boolean).join(' · ')||N.coordinate(m.lat,true)+' · '+N.coordinate(m.lon,false);b.append(name,detail);b.onclick=()=>select(m);list.append(b);});$('marinaMore').hidden=matches.length<=limit;}
async function load(){if(loaded||loading)return;loading=true;$('marinaLibraryStatus').textContent='Loading the UK marina library…';try{const r=await fetch('data/marinas/uk-marinas.json?v=2026-10-03');if(!r.ok)throw Error();const data=await r.json();if(data.schemaVersion!==1||!Array.isArray(data.marinas))throw Error();records=data.marinas.filter(M.valid);if(!records.length)throw Error();loaded=true;$('marinaLibraryStatus').textContent=records.length+' mapped UK marina locations · source '+String(data.sourceTimestamp||data.generatedAt).slice(0,10)+'. Coverage is not guaranteed complete.';try{const saved=localStorage.getItem(KEY),m=records.find(x=>x.id===saved);if(m)select(m);}catch{}results();}catch{$('marinaLibraryStatus').textContent='The marina library could not load. Check the connection, then close and reopen this menu to retry.';}finally{loading=false;}}
window.addEventListener('navigation-map-ready',e=>{map=e.detail.map;$('marinaSearch').oninput=()=>{limit=50;if(loaded)results();};$('marinaMore').onclick=()=>{limit+=50;results();};$('marinaGPS').onclick=()=>{window.HelmloreChart.startGPS();updateDistance();};$('clearMarina').onclick=()=>{selected=null;marker?.remove();marker=null;window.HelmloreChart.setMarinaDestination(null);$('marinaDestination').hidden=true;try{localStorage.removeItem(KEY);}catch{}};});
window.addEventListener('navigation-panel-open',e=>{if(e.detail.name==='marinas'){if(loaded)results();else load();}});
window.addEventListener('navigation-marina-cleared',()=>{selected=null;marker?.remove();marker=null;$('marinaDestination').hidden=true;try{localStorage.removeItem(KEY);}catch{}});
window.addEventListener('navigation-position-update',updateDistance);
})();

