/* Device-local review register. Source files and shared release are never mutated here. */
(()=>{'use strict';
const key='helmlore-mark-corrections-v1',edit=document.body.dataset.markReview==='true',$=id=>document.getElementById(id);
let publishedRetains=new Set(),publishedCutoff=0;
let records=[],selected=null,shown=[],map=null;
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function valid(r){return r&&['cm93-2011','user-local-marks'].includes(r.source)&&typeof r.source_external_id==='string'&&r.source_external_id.length>0&&r.source_external_id.length<200&&r.action==='retire'&&typeof r.evidence==='string'&&r.evidence.trim()&&Array.isArray(r.coordinates)&&r.coordinates.length===2&&r.coordinates.every(Number.isFinite)&&Math.abs(r.coordinates[0])<=180&&Math.abs(r.coordinates[1])<=90;}
try{const v=JSON.parse(localStorage.getItem(key)||'[]');if(Array.isArray(v))records=v.filter(valid);}catch(e){console.warn('Mark correction storage unavailable',e);}
function record(f,source){return {source,source_external_id:String(source==='cm93-2011'?(f.properties.record_id||''):(f.id||'')),name:f.properties.name||f.properties.OBJNAM||f.properties.NOBJNM||f.properties.class||'Unnamed mark',coordinates:f.geometry.coordinates,mark_type:f.properties.mark_type||f.properties.class,source_date:source==='cm93-2011'?'2011':f.properties.confirmed_on,properties:f.properties};}
function same(a,b){return a.source===b.source&&a.source_external_id===b.source_external_id;}
function save(next){try{localStorage.setItem(key,JSON.stringify(next));records=next;renderRemoved();window.dispatchEvent(new Event('mark-corrections-changed'));return true;}catch(e){if(edit)$('mark-message').textContent='Could not save changes on this device. No change was applied.';return false;}}
window.MarkReview={publishedRetains(ids,cutoff){publishedRetains=new Set(ids);publishedCutoff=Date.parse(cutoff)||0;},hidden(f,source){const a=record(f,source);return !!a.source_external_id&&records.some(b=>same(a,b)&&!(source==='cm93-2011'&&publishedRetains.has(a.source_external_id)&&(Date.parse(b.decided_at)||0)<=publishedCutoff));},select(f,source){if(!edit)return;selected=record(f,source);$('mark-selection').innerHTML='<h3>'+esc(selected.name)+'</h3><p>'+esc(selected.mark_type)+' · '+esc(source)+' · '+esc(selected.source_date||'date unknown')+'</p><p>'+selected.coordinates[1].toFixed(6)+', '+selected.coordinates[0].toFixed(6)+'</p><p>Source ID: '+esc(selected.source_external_id)+'</p><p>Light: '+esc(f.properties.light||f.properties.LITCHR||'Not specified')+'</p>';$('mark-remove').disabled=!selected.source_external_id||records.some(b=>same(selected,b));$('mark-evidence').value='';$('mark-message').textContent='';$('mark-selection').scrollIntoView({block:'nearest',behavior:'smooth'});},visible(fs,m,local){if(!edit)return;map=m;const seen=new Set();shown=[];for(const [features,source] of [[fs,'cm93-2011'],[$('review-local').checked?(local?.features||[]):[],'user-local-marks']])for(const f of features){const a=record(f,source),id=a.source+':'+a.source_external_id;if(!a.source_external_id||seen.has(id)||!m.getBounds().contains([a.coordinates[1],a.coordinates[0]])||records.some(b=>same(a,b)))continue;seen.add(id);shown.push({f,source,a});}renderList();}};
function renderList(){const q=$('mark-search').value.trim().toLowerCase(),items=shown.filter(x=>(x.a.name+' '+x.a.source_external_id).toLowerCase().includes(q));$('mark-list').replaceChildren();for(const x of items.slice(0,150)){const b=document.createElement('button');b.textContent=x.a.name+' · '+(x.source==='cm93-2011'?'2011':'Recent');b.style.cssText='display:block;width:100%;text-align:left;margin:5px 0';b.onclick=()=>{map.panTo([x.a.coordinates[1],x.a.coordinates[0]]);window.MarkReview.select(x.f,x.source);};$('mark-list').append(b);}if(!items.length)$('mark-list').textContent='No editable marks loaded in this view. Zoom in or choose another area.';else if(items.length>150)$('mark-list').append(document.createTextNode('Showing 150 of '+items.length+'; use search or zoom in.'));}
function renderRemoved(){if(!edit)return;$('removed-count').textContent='Removed marks ('+records.length+')';$('removed-list').replaceChildren();for(const r of records){const p=document.createElement('p');p.textContent=r.name+' · '+r.evidence+' ';const b=document.createElement('button');b.textContent='Restore';b.onclick=()=>{save(records.filter(x=>!same(x,r)));$('mark-message').textContent='Mark restored.';};p.append(b);$('removed-list').append(p);}}
window.addEventListener('storage',e=>{if(e.key!==key)return;try{const next=JSON.parse(e.newValue||'[]');if(!Array.isArray(next)||!next.every(valid))return;records=next;renderRemoved();window.dispatchEvent(new Event('mark-corrections-changed'));}catch{}});
if(!edit)return;
$('mark-search').oninput=renderList;
$('review-local').onchange=()=>{const c=$('localmarks');c.checked=$('review-local').checked;c.dispatchEvent(new Event('change'));window.dispatchEvent(new Event('mark-corrections-changed'));};
$('mark-remove').onclick=()=>{const evidence=$('mark-evidence').value.trim();if(!selected||!evidence){$('mark-message').textContent='Add a reason or chart reference before removing this mark.';return;}if(records.some(b=>same(selected,b)))return;if(save([...records,{...selected,action:'retire',evidence,decided_at:new Date().toISOString()}])){$('mark-remove').disabled=true;$('mark-message').textContent='Mark removed from your chart on this device. You can restore it below.';}};
$('mark-export').onclick=()=>{const blob=new Blob([JSON.stringify({schema:'helmlore-mark-corrections-v1',scope:'device-local-review',exported_at:new Date().toISOString(),corrections:records},null,2)],{type:'application/json'}),a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download='helmlore-mark-corrections-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('mark-import').onchange=async()=>{try{const file=$('mark-import').files[0];if(!file)return;if(file.size>5e6)throw Error('File is too large');const d=JSON.parse(await file.text());if(d.schema!=='helmlore-mark-corrections-v1'||!Array.isArray(d.corrections)||!d.corrections.every(valid))throw Error('Invalid corrections file');const next=[...records];for(const r of d.corrections){if(!next.some(x=>same(x,r)))next.push(r);}if(save(next))$('mark-message').textContent='Corrections loaded on this device.';}catch(e){$('mark-message').textContent=e.message;}$('mark-import').value='';};
renderRemoved();
})();
