/* Separate planning page: manual geometry, one-shot position only. */
(()=>{'use strict';const N=window.HelmloreNav,P=window.HelmlorePlanning,M=window.HelmloreMarinas,$=id=>document.getElementById(id);let points=[],vessel=null,library=[],pick=null,gpsEpoch=0;let map,lines,markers;
function loadVessel(){try{vessel=P.profile(JSON.parse(localStorage.getItem(P.PROFILE)||'null')||{});}catch{vessel=null;}}
function message(s){$('planStatus').textContent=s;}
function save(){try{localStorage.setItem(P.DRAFT,JSON.stringify({name:$('planName').value,points}));return true;}catch{message('Browser storage unavailable. Export GPX before leaving.');return false;}}
function invalidate(){ $('planReviewed').checked=false;save();draw();}
function hideTools(){$('planningTools').hidden=true;$('planningToolsToggle').setAttribute('aria-expanded','false');}
$('planningToolsToggle').onclick=()=>{const show=$('planningTools').hidden;close();$('planningTools').hidden=!show;$('planningToolsToggle').setAttribute('aria-expanded',String(show));};
function menu(which='route'){hideTools(); $('planMenu').hidden=false;$('routeEditor').hidden=which==='vessel';$('vesselEditor').hidden=which!=='vessel';$('planMenuToggle').setAttribute('aria-expanded','true');}
function close(){ $('planMenu').hidden=true;$('planMenuToggle').setAttribute('aria-expanded','false');}
function endpoint(p,end){if(end&&!points.length){message('Choose a start first.');return;}if(points.length<2){if(!points.length)points=[{...p,name:p.name||'Start',locked:false}];else if(end)points.push({...p,name:p.name||'Destination',locked:false});else points[0]={...p,name:p.name||'Start',locked:false};if(end&&points.length===1)message('Destination selected as the first point. Choose your start to complete the route.');}else points[end?points.length-1:0]={...p,name:p.name||(end?'Destination':'Start'),locked:false};invalidate();fit();if(points.length>1)message('Direct line ready. Tap it to insert and drag waypoints.');}
function fit(){if(points.length>1)map.fitBounds(points.map(p=>[p.lat,p.lon]),{paddingTopLeft:[30,175],paddingBottomRight:[$('planMenu').hidden?90:Math.min(450,map.getSize().x*0.55),55],maxZoom:15});else if(points.length)map.setView([points[0].lat,points[0].lon],13);}
function draw(){lines.clearLayers();markers.clearLayers();points.forEach((p,i)=>{if(i){const leg=i-1;L.polyline([[points[leg].lat,points[leg].lon],[p.lat,p.lon]],{color:'#efa737',weight:4,interactive:false}).addTo(lines);L.polyline([[points[leg].lat,points[leg].lon],[p.lat,p.lon]],{color:'#efa737',weight:22,opacity:0}).addTo(lines).on('click',e=>{L.DomEvent.stopPropagation(e);try{points=P.insert(points,leg,{lat:e.latlng.lat,lon:((e.latlng.lng+540)%360)-180});invalidate();message('Waypoint inserted. Drag its marker, then lock it.');}catch(error){message(error.message);}});}const marker=L.marker([p.lat,p.lon],{draggable:!p.locked,icon:L.divIcon({className:'waypoint-icon'+(p.locked?' locked-point':''),html:String(i+1),iconSize:[28,28],iconAnchor:[14,14]})}).addTo(markers);const text=document.createElement('div');text.textContent=p.name+(p.locked?' · locked':' · drag to move');marker.bindPopup(text);marker.on('dragend',()=>{try{const ll=marker.getLatLng();points=P.move(points,i,{lat:ll.lat,lon:((ll.lng+540)%360)-180});invalidate();}catch(error){message(error.message);}});});
const list=$('planWaypoints');list.replaceChildren();points.forEach((p,i)=>{const li=document.createElement('li'),name=document.createElement('input'),coords=document.createElement('small'),actions=document.createElement('div'),lock=document.createElement('button'),remove=document.createElement('button');name.value=p.name;name.maxLength=80;name.setAttribute('aria-label','Waypoint '+(i+1)+' name');name.oninput=()=>{p.name=name.value.trim()||'Waypoint '+(i+1);$('planReviewed').checked=false;save();render();};name.onchange=draw;coords.textContent=(i===0?'Start · ':i===points.length-1?'Destination · ':'')+N.coordinate(p.lat,true)+' / '+N.coordinate(p.lon,false);lock.textContent=p.locked?'Unlock':'Lock';lock.setAttribute('aria-label',(p.locked?'Unlock':'Lock')+' waypoint '+(i+1));lock.onclick=()=>{p.locked=!p.locked;invalidate();};remove.textContent='Remove';remove.setAttribute('aria-label','Remove waypoint '+(i+1));remove.onclick=()=>{points.splice(i,1);invalidate();};actions.className='waypoint-actions';actions.append(lock,remove);li.append(name,coords,actions);list.append(li);});render();}
function render(){const s=P.summary(points,vessel?.cruise);$('planDistance').textContent=s.nm.toFixed(2)+' NM';$('planTime').textContent=points.length<2?'—':P.duration(s.hours);$('planSpeed').textContent=vessel?vessel.cruise.toFixed(1)+' kn':'Set vessel';$('planCount').textContent=points.length;const legs=$('planLegs');legs.replaceChildren();s.legs.forEach((l,i)=>{const p=document.createElement('p');p.textContent=(i+1)+' → '+(i+2)+' · '+l.nm.toFixed(2)+' NM · '+String(Math.round(l.bearing)%360).padStart(3,'0')+'° T · '+P.duration(vessel?l.nm/vessel.cruise:null);legs.append(p);});$('confirmPlan').disabled=points.length<2||!vessel||!$('planReviewed').checked||s.nm<0.001;$('planExport').disabled=points.length<2;}
function search(end){const input=$(end?'endSearch':'startSearch'),results=$(end?'endResults':'startResults');results.replaceChildren();const q=input.value.trim();if(q.length<2)return;const found=M.search(library,q).slice(0,12);for(const m of found){const b=document.createElement('button');b.textContent=m.name+' · '+(m.locality||m.postcode||'UK');b.onclick=()=>{endpoint({lat:m.lat,lon:m.lon,name:m.name},end);input.value=m.name;results.replaceChildren();};results.append(b);}if(!found.length){const p=document.createElement('p');p.textContent=library.length?'No matching marinas. Choose a map point instead.':'Marina library not loaded.';results.append(p);}}
loadVessel();try{const d=JSON.parse(localStorage.getItem(P.DRAFT)||'null');if(d){points=P.points(d.points);$('planName').value=String(d.name||'').slice(0,80);if(points.length){$('startSearch').value=points[0].name;if(points.length>1)$('endSearch').value=points[points.length-1].name;message('Saved draft restored. Edit the manual route, then confirm when ready.');}}}catch{message('Previous draft could not be read. Start a new plan.');}
if(!window.L){$('mapFallback').textContent='Map could not load. Check your connection and reload.';return;}$('mapFallback').remove();map=L.map('map',{worldCopyJump:true}).setView([54.5531,-3.5904],13);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'}).addTo(map);L.tileLayer('https://tiles.openseamap.org/seamark/{z}/{x}/{y}.png',{maxNativeZoom:18,maxZoom:19,attribution:'Sea marks © OpenSeaMap'}).addTo(map);map.zoomControl.remove();L.control.zoom({position:'bottomleft'}).addTo(map);L.control.scale().addTo(map);lines=L.layerGroup().addTo(map);markers=L.layerGroup().addTo(map);
map.on('click',e=>{hideTools();if(pick===null)return;const end=pick;pick=null;endpoint({lat:e.latlng.lat,lon:((e.latlng.lng+540)%360)-180},end);menu();});
$('startOnMap').onclick=()=>{pick=false;message('Tap the map for your start.');close();};$('endOnMap').onclick=()=>{if(!points.length){message('Choose a start first.');return;}pick=true;message('Tap the map for your destination.');close();};
$('copyGPS').onclick=()=>{if(!navigator.geolocation){message('Location is unavailable. Choose a marina or map point.');return;}const token=++gpsEpoch;$('copyGPS').disabled=true;message('Requesting a single current position; tracking remains off.');navigator.geolocation.getCurrentPosition(pos=>{if(token!==gpsEpoch)return;$('copyGPS').disabled=false;if(!Number.isFinite(pos.coords.accuracy)||pos.coords.accuracy>100||Date.now()-pos.timestamp>15000){message('Position too old or inaccurate. Choose a marina or map point.');return;}endpoint({lat:pos.coords.latitude,lon:pos.coords.longitude,name:'Copied current position'},false);message('Start copied once · GPS tracking is off.');},()=>{if(token!==gpsEpoch)return;$('copyGPS').disabled=false;message('Could not copy your position. Choose a marina or map point.');},{enableHighAccuracy:true,maximumAge:0,timeout:15000});};
$('startSearch').oninput=()=>search(false);$('endSearch').oninput=()=>search(true);$('planName').oninput=()=>{$('planReviewed').checked=false;save();render();};$('planReviewed').onchange=render;$('fitPlan').onclick=()=>{hideTools();fit();};$('planVessel').onclick=()=>menu('vessel');$('planMenuToggle').onclick=()=>{if($('planMenu').hidden||$('routeEditor').hidden)menu();else close();};$('planMenuClose').onclick=close;window.addEventListener('vessel-profile-saved',()=>{loadVessel();$('planReviewed').checked=false;render();message('Vessel updated. Open Plan menu to continue.');});
$('confirmPlan').onclick=()=>{try{if(!$('planReviewed').checked)throw Error('Acknowledge the unchecked plan first.');const route=P.confirmed({name:$('planName').value,points,vessel});localStorage.setItem(P.ACTIVE,JSON.stringify(route));location.href='navigation.html?plan=confirmed';}catch(error){message('Could not confirm: '+error.message);}};
$('planExport').onclick=()=>{hideTools();const url=URL.createObjectURL(new Blob([N.gpx(points,'route',$('planName').value||'Helmlore manual plan')],{type:'application/gpx+xml'}));const a=document.createElement('a');a.href=url;a.download='helmlore-planned-route.gpx';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);};
function theme(night){document.body.dataset.theme=night?'night':'day';$('planTheme').textContent=night?'Day mode':'Night mode';try{localStorage.setItem('helmlore-chart-theme',night?'night':'day');}catch{}}try{theme(localStorage.getItem('helmlore-chart-theme')==='night');}catch{}$('planTheme').onclick=()=>theme(document.body.dataset.theme!=='night');window.addEventListener('resize',()=>map.invalidateSize());window.addEventListener('pagehide',()=>{gpsEpoch++;save();});
fetch('data/marinas/uk-marinas.json?v=2026-10-03.1').then(r=>{if(!r.ok)throw Error();return r.json();}).then(d=>{library=d.marinas.filter(M.valid);$('planLibraryStatus').textContent=library.length+' mapped UK marina locations · includes inland sites.';}).catch(()=>{$('planLibraryStatus').textContent='Marina library unavailable. You can still choose map points.';});draw();if(points.length)fit();
})();
