/* Forecast layers: explicitly loaded map area, never automatic GPS upload. */
(()=>{'use strict';const $=id=>document.getElementById(id),finite=Number.isFinite;let map,wind,currents,area,data,loadedAt,baseTime,busy=false;
const fmtTime=t=>new Date(t*1000).toLocaleString('en-GB',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit',timeZoneName:'short'});
const val=(d,k,t)=>{const h=d?.hourly;if(!h||!Array.isArray(h.time))return null;const i=h.time.findIndex(v=>v===t);const x=h[k]?.[i];return finite(x)?x:null;};
const number=(x,u)=>finite(x)?x.toFixed(1)+' '+u:'Unavailable';
function arrow(layer,d,speed,direction,kind){if(!finite(speed)||!finite(direction))return;const flow=kind==='wind'?(direction+180)%360:direction;const icon=L.divIcon({className:'forecast-arrow '+kind+'-vector',iconSize:[66,50],iconAnchor:[33,25],html:'<b style="transform:rotate('+flow+'deg)">↑</b><small>'+speed.toFixed(1)+' kn</small>'});L.marker([d.latitude,d.longitude],{icon,interactive:true}).bindTooltip(kind==='wind'?'Wind FROM '+Math.round(direction)+'° T':'Current TOWARDS '+Math.round(direction)+'° T').addTo(layer);}
function render(){wind.clearLayers();currents.clearLayers();if(!data)return;const t=baseTime+Number($('forecastHour').value)*3600;$('forecastTime').textContent=fmtTime(t);for(const d of data.weather)arrow(wind,d,val(d,'wind_speed_10m',t),val(d,'wind_direction_10m',t),'wind');for(const d of data.marine)arrow(currents,d,val(d,'ocean_current_velocity',t),val(d,'ocean_current_direction',t),'current');const w=data.weather[4],m=data.marine[4];const wd=val(w,'wind_direction_10m',t),cd=val(m,'ocean_current_direction',t);$('weatherReadout').textContent='Area centre: '+area.points[4].lat.toFixed(3)+'°, '+area.points[4].lon.toFixed(3)+'° · Wind '+number(val(w,'wind_speed_10m',t),'kn')+(finite(wd)?' from '+Math.round(wd)+'° T':'')+' · Gusts '+number(val(w,'wind_gusts_10m',t),'kn')+' · Current '+number(val(m,'ocean_current_velocity',t),'kn')+(finite(cd)?' towards '+Math.round(cd)+'° T':'')+' · Waves '+number(val(m,'wave_height',t),'m')+' · Sea level '+number(val(m,'sea_level_height_msl',t),'m MSL');
const points=[];for(let i=0;i<=24;i++){const v=val(m,'sea_level_height_msl',baseTime+i*3600);if(finite(v))points.push({i,v});}const el=$('seaLevelPlot');el.replaceChildren();if(points.length<2){el.textContent='Sea-level forecast unavailable for this area.';return;}const low=Math.min(...points.map(p=>p.v)),high=Math.max(...points.map(p=>p.v)),span=Math.max(.2,high-low);const ns='http://www.w3.org/2000/svg',svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox','0 0 280 110');svg.setAttribute('role','img');svg.setAttribute('aria-label','24 hour modelled sea level curve in metres above mean sea level');const line=document.createElementNS(ns,'polyline');line.setAttribute('points',points.map(p=>(10+p.i/24*260)+','+(80-(p.v-low)/span*60)).join(' '));line.setAttribute('fill','none');line.setAttribute('stroke','#67d6e4');line.setAttribute('stroke-width','2');svg.append(line);for(const [x,y,text] of [[10,105,'Now'],[218,105,'+24 hours'],[10,12,low.toFixed(1)+' to '+high.toFixed(1)+' m MSL']]){const tx=document.createElementNS(ns,'text');tx.setAttribute('x',x);tx.setAttribute('y',y);tx.setAttribute('fill','#a9c9d4');tx.setAttribute('font-size','11');tx.textContent=text;svg.append(tx);}el.append(svg);}
async function get(url){const abort=new AbortController(),timer=setTimeout(()=>abort.abort(),18000);try{const r=await fetch(url,{signal:abort.signal});if(!r.ok)throw Error('Service returned '+r.status);const j=await r.json();if(j.error)throw Error(j.reason);return Array.isArray(j)?j:[j];}finally{clearTimeout(timer);}}
async function load(newArea){if(busy)return;if(!newArea&&loadedAt&&Date.now()-loadedAt<60000){$('weatherStatus').textContent='Please wait a minute before refreshing.';return;}busy=true;$('loadWeather').disabled=$('refreshWeather').disabled=true;wind.clearLayers();currents.clearLayers();data=null;$('forecastHour').disabled=true;$('weatherReadout').textContent='';$('seaLevelPlot').replaceChildren();$('weatherStatus').textContent='Loading forecast models…';try{if(newArea){const b=map.getBounds(),points=[];for(let y=0;y<3;y++)for(let x=0;x<3;x++)points.push({lat:Math.max(-85,Math.min(85,b.getSouth()+(y+.5)/3*(b.getNorth()-b.getSouth()))),lon:((b.getWest()+(x+.5)/3*(b.getEast()-b.getWest())+540)%360)-180});area={points};}const params=new URLSearchParams({latitude:area.points.map(p=>p.lat.toFixed(4)).join(','),longitude:area.points.map(p=>p.lon.toFixed(4)).join(','),timezone:'GMT',timeformat:'unixtime',forecast_days:'3',wind_speed_unit:'kn'});const [weather,marine]=await Promise.all([get('https://api.open-meteo.com/v1/forecast?'+params+'&hourly=wind_speed_10m,wind_direction_10m,wind_gusts_10m'),get('https://marine-api.open-meteo.com/v1/marine?'+params+'&cell_selection=sea&hourly=ocean_current_velocity,ocean_current_direction,sea_level_height_msl,wave_height')]);if(weather.length!==9||marine.length!==9)throw Error('Incomplete area response');data={weather,marine};loadedAt=Date.now();baseTime=Math.ceil(loadedAt/3600000)*3600;$('forecastHour').value=0;$('forecastHour').disabled=false;$('weatherStatus').textContent='Retrieved '+fmtTime(loadedAt/1000)+' · hourly forecast · sea model about 8 km resolution. Pan then Load this area to change coverage.';render();}catch(e){$('weatherStatus').textContent='Forecast unavailable. Check your connection and try again. No estimated values are shown.';}finally{busy=false;$('loadWeather').disabled=false;$('refreshWeather').disabled=!area;}}
window.addEventListener('navigation-map-ready',e=>{map=e.detail.map;wind=L.layerGroup().addTo(map);currents=L.layerGroup();$('loadWeather').onclick=()=>load(true);$('refreshWeather').onclick=()=>load(false);$('forecastHour').oninput=render;for(const [id,layer] of [['windLayer',wind],['currentLayer',currents]])$(id).onchange=()=>$(id).checked?layer.addTo(map):map.removeLayer(layer);setInterval(()=>{if(loadedAt&&Date.now()-loadedAt>3600000){wind.clearLayers();currents.clearLayers();data=null;$('forecastHour').disabled=true;$('weatherReadout').textContent='';$('seaLevelPlot').replaceChildren();$('weatherStatus').textContent='Forecast display expired. Refresh to retrieve new data.';}},60000);});
})();
