/* Forecast packages: exact model times, bounded areas, no invented observations. */
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.HelmloreWeather=api;})(typeof window==='object'?window:globalThis,()=>{'use strict';
const KEY='helmlore-weather-areas-v1';
let land=null;
function setLand(data){if(!Array.isArray(data?.polygons))throw Error('Sea-area coastline check unavailable.');land=data.polygons;}
function inRing(x,y,ring){let inside=false;for(let i=0,j=ring.length-1;i<ring.length;j=i++){const a=ring[i],b=ring[j];if((a[1]>y)!==(b[1]>y)&&x<(b[0]-a[0])*(y-a[1])/(b[1]-a[1])+a[0])inside=!inside;}return inside;}
function isSea(p){if(!land||!Number.isFinite(p?.lat)||!Number.isFinite(p?.lon))return false;return !land.some(g=>p.lon>=g.b[0]&&p.lon<=g.b[2]&&p.lat>=g.b[1]&&p.lat<=g.b[3]&&inRing(p.lon,p.lat,g.r[0])&&!g.r.slice(1).some(r=>inRing(p.lon,p.lat,r)));}
function seaGrid(b){b=bounds(b);if(!land)throw Error('Coastline check is still loading. Retry shortly.');const candidates=[];for(let y=0;y<15;y++)for(let x=0;x<15;x++){const p={lat:b.south+(y+.5)/15*(b.north-b.south),lon:b.west+(x+.5)/15*(b.east-b.west)};if(isSea(p))candidates.push(p);}if(!candidates.length)throw Error('No sea samples in this box. Choose an area covering the sea.');const picked=[candidates.splice(Math.floor(candidates.length/2),1)[0]],scale=Math.cos((b.north+b.south)/2*Math.PI/180);while(candidates.length&&picked.length<25){let best=-1,index=0;candidates.forEach((p,i)=>{const distance=Math.min(...picked.map(q=>(p.lat-q.lat)**2+((p.lon-q.lon)*scale)**2));if(distance>best){best=distance;index=i;}});picked.push(candidates.splice(index,1)[0]);}return picked;}

function bounds(b){if(!b||![b.south,b.north,b.west,b.east].every(Number.isFinite)||b.south>=b.north||b.west>=b.east||b.south< -85||b.north>85||b.west< -180||b.east>180||b.north-b.south>8||b.east-b.west>12)throw Error('Choose a smaller area, up to 8° north–south and 12° east–west, without crossing the date line.');return {...b};}
function grid(b){b=bounds(b);const out=[];for(let y=0;y<5;y++)for(let x=0;x<5;x++)out.push({lat:b.south+(y+.5)/5*(b.north-b.south),lon:b.west+(x+.5)/5*(b.east-b.west)});return out;}
function value(d,k,t){const h=d?.hourly,i=h?.time?.indexOf(t);const v=i>=0?h[k]?.[i]:null;return Number.isFinite(v)?v:null;}
function series(d){return d&&Number.isFinite(d.latitude)&&Number.isFinite(d.longitude)&&Array.isArray(d.hourly?.time)&&d.hourly.time.length>=2&&d.hourly.time.length<=100&&d.hourly.time.every((t,i,a)=>Number.isFinite(t)&&(!i||t>a[i-1]));}
function pack(b,weather,marine,name,now=Date.now(),points=grid(b)){b=bounds(b);if(!Array.isArray(weather)||weather.length!==points.length||!points.length||points.length>25||!weather.every(series))throw Error('Incomplete wind forecast response. Your previous forecast is retained.');if(!Array.isArray(marine)||marine.length!==points.length||!marine.every(series))marine=[];const start=Math.max(Math.floor(now/3600000)*3600,...weather.map(d=>d.hourly.time[0]));const end=Math.min(start+72*3600,...weather.map(d=>d.hourly.time.at(-1)));const times=weather[0].hourly.time.filter(t=>t>=start&&t<=end&&weather.every(d=>d.hourly.time.includes(t)));if(times.length<2)throw Error('Forecast has no usable future coverage.');return {version:1,id:String(now),name:String(name||'Coastal forecast').trim().slice(0,80)||'Coastal forecast',bounds:b,points,seaOnly:points.every(isSea),weather,marine,times,downloadedAt:now,source:'Open-Meteo',start:times[0],end:times.at(-1)};}
function valid(p){try{bounds(p.bounds);return p.version===1&&typeof p.id==='string'&&typeof p.name==='string'&&Number.isFinite(p.downloadedAt)&&p.weather?.length>=1&&p.weather.length<=25&&p.weather.every(series)&&Array.isArray(p.marine)&&(p.marine.length===0||(p.marine.length===p.weather.length&&p.marine.every(series)))&&p.points?.length===p.weather.length&&p.points.every(v=>Number.isFinite(v.lat)&&Number.isFinite(v.lon))&&p.times?.length>=2&&p.times.length<=73&&p.times.every((t,i,a)=>Number.isFinite(t)&&(!i||t>a[i-1])&&p.weather.every(d=>d.hourly.time.includes(t)))&&p.start===p.times[0]&&p.end===p.times.at(-1);}catch{return false;}}
function state(p,t,now=Date.now()){if(now/1000>p.end)return 'EXPIRED';if(t<Math.floor(now/3600000)*3600)return 'PAST FORECAST';if(now-p.downloadedAt>12*3600000)return 'OLDER DOWNLOAD';return 'FORECAST';}
const names=['Calm','Light air','Light breeze','Gentle breeze','Moderate breeze','Fresh breeze','Strong breeze','Near gale','Gale','Strong gale','Storm','Violent storm','Hurricane force'];
function beaufort(kn){if(!Number.isFinite(kn)||kn<0)return null;const cuts=[1,4,7,11,17,22,28,34,41,48,56,64];const force=cuts.findIndex(v=>kn<v);return {force:force<0?12:force,name:names[force<0?12:force]};}
function forceColour(force){return force<=3?'#298d99':force<=5?'#e3b833':force<=7?'#eb862b':force<=9?'#ce3949':'#913865';}
function waveBand(height,limit){if(!Number.isFinite(height)||height<0)return {colour:'#607784',label:'Unavailable'};if(!Number.isFinite(limit)||limit<=0)return {colour:'#298d99',label:'Set vessel comfort limit'};return height>limit?{colour:'#ce3949',label:'Above your comfort limit'}:height>=limit*.8?{colour:'#eb862b',label:'Approaching your comfort limit'}:{colour:'#298d99',label:'Below your comfort limit'};}
return {KEY,setLand,isSea,seaGrid,bounds,grid,value,pack,valid,state,beaufort,forceColour,waveBand};});

