/* Explicit area downloads; saved model data works offline in the loaded app. */
(()=>{'use strict';const $=id=>document.getElementById(id),C=window.HelmloreWeather,finite=Number.isFinite;
let map,wind,currents,box,area,active,busy=false,selecting=false,corner=null,preview=null,playing=null,notice='',saved=[];
const fmt=t=>new Date(t*1000).toLocaleString('en-GB',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit',timeZoneName:'short'});
const number=(v,u)=>finite(v)?v.toFixed(1)+' '+u:'Unavailable',val=C.value;
function pause(){clearInterval(playing);playing=null;$('weatherPlay').textContent='▶';$('weatherPlay').setAttribute('aria-pressed','false');$('weatherPlay').setAttribute('aria-label','Play forecast');}
function timeline(show){if(show&&!active)return;$('weatherTimeline').hidden=!show;document.body.classList.toggle('weather-timeline-visible',show);$('showWeatherTimeline').textContent=show?'Hide weather timeline':'Show weather timeline';$('showWeatherTimeline').setAttribute('aria-pressed',String(show));if(!show)pause();}
function setArea(b){area=C.bounds(b);box.clearLayers();L.rectangle([[b.south,b.west],[b.north,b.east]],{color:'#68d9e3',weight:2,fillOpacity:.06,interactive:false}).addTo(box);$('downloadWeather').disabled=busy;$('areaSelectionStatus').textContent='Selected box · '+b.south.toFixed(2)+'° to '+b.north.toFixed(2)+'° latitude · '+b.west.toFixed(2)+'° to '+b.east.toFixed(2)+'° longitude';}
function selection(on){selecting=on;corner=null;if(preview){map.removeLayer(preview);preview=null;}$('selectWeatherArea').setAttribute('aria-pressed',String(on));$('selectWeatherArea').textContent=on?'Cancel area selection':'Draw area box';map.getContainer().style.cursor=on?'crosshair':'';$('areaSelectionStatus').textContent=on?'Tap the first corner on the chart.':'Area selection cancelled.';$('weatherMapPrompt').hidden=!on;$('weatherMapPrompt').textContent='Weather area: tap the first corner · Menu → Weather to cancel';}
function arrow(layer,p,speed,direction,kind){if(!finite(speed)||!finite(direction)||speed<0)return;const flow=kind==='wind'?(direction+180)%360:direction;const icon=L.divIcon({className:'forecast-arrow '+kind+'-vector',iconSize:[66,50],iconAnchor:[33,25],html:'<b style="transform:rotate('+flow+'deg)">↑</b><small>'+speed.toFixed(1)+' kn</small>'});L.marker([p.lat,p.lon],{icon,interactive:true}).bindTooltip((kind==='wind'?'Wind FROM ':'Current TOWARDS ')+Math.round(direction)+'° T · model sample').addTo(layer);}
function status(){if(!active)return;const t=active.times[Number($('forecastHour').value)||0],s=C.state(active,t);$('timelineStatus').textContent=(!navigator.onLine?'OFFLINE · ':'')+s;$('timelineStatus').dataset.stale=s==='FORECAST'?'false':'true';$('weatherStatus').textContent=notice+(notice?' ':'')+'Downloaded '+fmt(active.downloadedAt/1000)+' · valid '+fmt(active.start)+' – '+fmt(active.end)+' · '+active.times.length+' hourly steps · '+(!navigator.onLine?'Offline: using saved forecast.':'Saved on this device; refresh while online.')+(!active.marine.length?' Marine forecast unavailable; wind only.':'');}
function plot(t){const el=$('seaLevelPlot');el.replaceChildren();const m=active.marine[12],points=[];for(let i=0;i<=24;i++){const v=val(m,'sea_level_height_msl',t+i*3600);if(finite(v))points.push({i,v});}if(points.length<2){el.textContent='Sea-level forecast unavailable for the selected time.';return;}const low=Math.min(...points.map(p=>p.v)),high=Math.max(...points.map(p=>p.v)),span=Math.max(.2,high-low),ns='http://www.w3.org/2000/svg',svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox','0 0 280 110');svg.setAttribute('role','img');svg.setAttribute('aria-label','Modelled sea level for 24 hours from selected forecast time, metres above mean sea level');const line=document.createElementNS(ns,'polyline');line.setAttribute('points',points.map(p=>(10+p.i/24*260)+','+(80-(p.v-low)/span*60)).join(' '));line.setAttribute('fill','none');line.setAttribute('stroke','#67d6e4');line.setAttribute('stroke-width','2');svg.append(line);for(const [x,y,text] of [[10,105,'Selected time'],[215,105,'+24 hours'],[10,12,low.toFixed(1)+' to '+high.toFixed(1)+' m MSL']]){const tx=document.createElementNS(ns,'text');tx.setAttribute('x',x);tx.setAttribute('y',y);tx.setAttribute('fill','#a9c9d4');tx.setAttribute('font-size','11');tx.textContent=text;svg.append(tx);}el.append(svg);}
function render(){wind.clearLayers();currents.clearLayers();if(!active)return;const index=Number($('forecastHour').value)||0,t=active.times[index];$('forecastTime').textContent=fmt(t)+' · +'+Math.round((t-active.start)/3600)+'h';$('timelineArea').textContent=active.name;status();if(C.state(active,t)!=='EXPIRED'){active.points.forEach((p,i)=>{arrow(wind,{lat:active.weather[i].latitude,lon:active.weather[i].longitude},val(active.weather[i],'wind_speed_10m',t),val(active.weather[i],'wind_direction_10m',t),'wind');arrow(currents,{lat:active.marine[i]?.latitude,lon:active.marine[i]?.longitude},val(active.marine[i],'ocean_current_velocity',t),val(active.marine[i],'ocean_current_direction',t),'current');});}
const w=active.weather[12],m=active.marine[12],wd=val(w,'wind_direction_10m',t),cd=val(m,'ocean_current_direction',t),read='Centre sample · Wind '+number(val(w,'wind_speed_10m',t),'kn')+(finite(wd)?' from '+Math.round(wd)+'° T':'')+' · Gust '+number(val(w,'wind_gusts_10m',t),'kn')+' · Current '+number(val(m,'ocean_current_velocity',t),'kn')+(finite(cd)?' towards '+Math.round(cd)+'° T':'')+' · Waves '+number(val(m,'wave_height',t),'m');
$('timelineReadout').textContent=read;$('weatherReadout').textContent=read+' · Sea level '+number(val(m,'sea_level_height_msl',t),'m MSL');$('weatherPrevious').disabled=index===0;$('weatherNext').disabled=index>=active.times.length-1;plot(t);}
function history(){const el=$('savedWeatherAreas');el.replaceChildren();if(!saved.length){el.textContent='No saved forecasts yet.';return;}for(const p of saved){const row=document.createElement('div'),b=document.createElement('button'),remove=document.createElement('button');row.className='weather-saved-row';b.className='weather-saved';b.textContent=p.name+' · '+fmt(p.downloadedAt/1000)+(Date.now()/1000>p.end?' · EXPIRED':'');b.setAttribute('aria-pressed',String(active?.id===p.id));b.onclick=()=>{notice='';activate(p);map.fitBounds([[p.bounds.south,p.bounds.west],[p.bounds.north,p.bounds.east]],{padding:[70,120]});};remove.textContent='Remove';remove.setAttribute('aria-label','Remove saved forecast '+p.name);remove.onclick=()=>{const next=saved.filter(x=>x.id!==p.id);try{localStorage.setItem(C.KEY,JSON.stringify(next));saved=next;if(active?.id===p.id){active=null;wind.clearLayers();currents.clearLayers();pause();timeline(false);$('weatherReadout').textContent='';$('seaLevelPlot').replaceChildren();$('refreshWeather').disabled=true;$('weatherStatus').textContent='Saved area removed.';}history();}catch{$('weatherStatus').textContent='Could not update saved forecasts. Storage unavailable.';}};row.append(b,remove);el.append(row);}}
function activate(p){pause();active=p;selection(false);setArea(p.bounds);$('weatherAreaName').value=p.name;$('forecastHour').max=p.times.length-1;$('forecastHour').value=Math.max(0,p.times.findIndex(t=>t>=Math.floor(Date.now()/3600000)*3600));$('forecastHour').disabled=false;$('showWeatherTimeline').disabled=false;$('refreshWeather').disabled=busy;timeline(true);history();render();}
async function get(url){const abort=new AbortController(),timer=setTimeout(()=>abort.abort(),25000);try{const r=await fetch(url,{signal:abort.signal});if(!r.ok)throw Error('Service returned '+r.status);const j=await r.json();if(j.error)throw Error(j.reason);return Array.isArray(j)?j:[j];}finally{clearTimeout(timer);}}
async function download(refresh){if(busy||(!area&&!active))return;if(!navigator.onLine){notice='No connection: download unavailable. Your saved forecast is retained.';if(active)status();else $('weatherStatus').textContent=notice;return;}if(saved.length>=10&&!refresh){$('weatherStatus').textContent='Ten areas saved. Remove an area or refresh an existing download.';return;}const b=refresh?active.bounds:area,name=refresh?active.name:$('weatherAreaName').value,replaceId=refresh?active.id:null;busy=true;pause();for(const id of ['downloadWeather','refreshWeather','loadWeather','selectWeatherArea'])$(id).disabled=true;$('weatherStatus').textContent='Downloading hourly wind and marine forecasts…';const points=C.grid(b),params=new URLSearchParams({latitude:points.map(p=>p.lat.toFixed(4)).join(','),longitude:points.map(p=>p.lon.toFixed(4)).join(','),timezone:'GMT',timeformat:'unixtime',forecast_hours:'73',wind_speed_unit:'kn'});try{const responses=await Promise.allSettled([get('https://api.open-meteo.com/v1/forecast?'+params+'&hourly=wind_speed_10m,wind_direction_10m,wind_gusts_10m'),get('https://marine-api.open-meteo.com/v1/marine?'+params+'&cell_selection=sea&hourly=ocean_current_velocity,ocean_current_direction,sea_level_height_msl,wave_height')]);if(responses[0].status!=='fulfilled')throw Error('Wind forecast download failed: '+responses[0].reason.message+'. Check your connection and retry.');const p=C.pack(b,responses[0].value,responses[1].status==='fulfilled'?responses[1].value:[],name);const next=[p,...saved.filter(x=>x.id!==replaceId)].slice(0,10);try{localStorage.setItem(C.KEY,JSON.stringify(next));saved=next;notice='Forecast saved for offline use.';}catch{notice='Storage full or unavailable: this forecast is NOT saved for offline use. Remove an old area and retry.';}activate(p);}catch(e){notice=e.message+' Previous saved forecast retained.';if(active)status();else $('weatherStatus').textContent=notice;}finally{busy=false;for(const id of ['loadWeather','selectWeatherArea'])$(id).disabled=false;$('downloadWeather').disabled=!area;$('refreshWeather').disabled=!active;}}
window.addEventListener('navigation-map-ready',e=>{map=e.detail.map;wind=L.layerGroup().addTo(map);currents=L.layerGroup();box=L.layerGroup().addTo(map);const prompt=document.createElement('div');prompt.id='weatherMapPrompt';prompt.className='weather-map-prompt';prompt.hidden=true;prompt.setAttribute('role','status');document.body.append(prompt);try{const old=JSON.parse(localStorage.getItem(C.KEY)||'[]');if(Array.isArray(old))saved=old.filter(C.valid).slice(0,10);}catch{$('weatherStatus').textContent='Saved forecasts could not be read. Download again while online.';}history();if(saved.length)activate(saved[0]);
$('selectWeatherArea').onclick=()=>{selection(!selecting);if(selecting){if($('addWaypoint').getAttribute('aria-pressed')==='true')$('addWaypoint').click();$('closeMenu').click();}};
$('loadWeather').onclick=()=>{selection(false);const b=map.getBounds();try{setArea({south:b.getSouth(),north:b.getNorth(),west:b.getWest(),east:b.getEast()});}catch(e){$('areaSelectionStatus').textContent=e.message;}};
map.on('click',e=>{if(!selecting)return;L.DomEvent.stopPropagation(e);const p={lat:e.latlng.lat,lon:((e.latlng.lng+540)%360)-180};if(!corner){corner=p;preview=L.circleMarker([p.lat,p.lon],{radius:6,color:'#68d9e3'}).addTo(map);$('weatherMapPrompt').textContent='Weather area: tap the opposite corner';return;}try{const b={south:Math.min(corner.lat,p.lat),north:Math.max(corner.lat,p.lat),west:Math.min(corner.lon,p.lon),east:Math.max(corner.lon,p.lon)};selection(false);setArea(b);requestAnimationFrame(()=>{$('chartToolsToggle').click();document.querySelector('[data-open="weather"]').click();});}catch(error){selection(false);$('areaSelectionStatus').textContent=error.message;requestAnimationFrame(()=>{$('chartToolsToggle').click();document.querySelector('[data-open="weather"]').click();});}});
$('downloadWeather').onclick=()=>download(false);$('refreshWeather').onclick=()=>download(true);$('forecastHour').oninput=()=>{pause();render();};$('weatherPrevious').onclick=()=>{pause();$('forecastHour').value=Math.max(0,Number($('forecastHour').value)-1);render();};$('weatherNext').onclick=()=>{pause();$('forecastHour').value=Math.min(active.times.length-1,Number($('forecastHour').value)+1);render();};$('weatherPlay').onclick=()=>{if(playing){pause();return;}if(!active)return;if(Number($('forecastHour').value)>=active.times.length-1)$('forecastHour').value=0;$('weatherPlay').textContent='Ⅱ';$('weatherPlay').setAttribute('aria-pressed','true');$('weatherPlay').setAttribute('aria-label','Pause forecast');playing=setInterval(()=>{const i=Number($('forecastHour').value);if(i>=active.times.length-1){pause();return;}$('forecastHour').value=i+1;render();},1000);};
$('showWeatherTimeline').onclick=()=>timeline($('weatherTimeline').hidden);$('closeWeatherTimeline').onclick=()=>timeline(false);for(const [id,layer] of [['windLayer',wind],['currentLayer',currents]])$(id).onchange=()=>$(id).checked?layer.addTo(map):map.removeLayer(layer);
document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});window.addEventListener('offline',status);window.addEventListener('online',status);setInterval(()=>{if(active)render();},60000);window.addEventListener('navigation-panel-open',e=>{if(e.detail.name!=='weather'&&selecting)selection(false);});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&selecting)selection(false);});
});
})();
