/* Forecast packages: exact model times, bounded areas, no invented observations. */
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.HelmloreWeather=api;})(typeof window==='object'?window:globalThis,()=>{'use strict';
const KEY='helmlore-weather-areas-v1';
function bounds(b){if(!b||![b.south,b.north,b.west,b.east].every(Number.isFinite)||b.south>=b.north||b.west>=b.east||b.south< -85||b.north>85||b.west< -180||b.east>180||b.north-b.south>8||b.east-b.west>12)throw Error('Choose a smaller area, up to 8° north–south and 12° east–west, without crossing the date line.');return {...b};}
function grid(b){b=bounds(b);const out=[];for(let y=0;y<5;y++)for(let x=0;x<5;x++)out.push({lat:b.south+(y+.5)/5*(b.north-b.south),lon:b.west+(x+.5)/5*(b.east-b.west)});return out;}
function value(d,k,t){const h=d?.hourly,i=h?.time?.indexOf(t);const v=i>=0?h[k]?.[i]:null;return Number.isFinite(v)?v:null;}
function series(d){return d&&Number.isFinite(d.latitude)&&Number.isFinite(d.longitude)&&Array.isArray(d.hourly?.time)&&d.hourly.time.length>=2&&d.hourly.time.length<=100&&d.hourly.time.every((t,i,a)=>Number.isFinite(t)&&(!i||t>a[i-1]));}
function pack(b,weather,marine,name,now=Date.now()){b=bounds(b);if(!Array.isArray(weather)||weather.length!==25||!weather.every(series))throw Error('Incomplete wind forecast response. Your previous forecast is retained.');if(!Array.isArray(marine)||marine.length!==25||!marine.every(series))marine=[];const start=Math.max(Math.floor(now/3600000)*3600,...weather.map(d=>d.hourly.time[0]));const end=Math.min(start+72*3600,...weather.map(d=>d.hourly.time.at(-1)));const times=weather[0].hourly.time.filter(t=>t>=start&&t<=end&&weather.every(d=>d.hourly.time.includes(t)));if(times.length<2)throw Error('Forecast has no usable future coverage.');return {version:1,id:String(now),name:String(name||'Coastal forecast').trim().slice(0,80)||'Coastal forecast',bounds:b,points:grid(b),weather,marine,times,downloadedAt:now,source:'Open-Meteo',start:times[0],end:times.at(-1)};}
function valid(p){try{bounds(p.bounds);return p.version===1&&typeof p.id==='string'&&typeof p.name==='string'&&Number.isFinite(p.downloadedAt)&&p.weather?.length===25&&p.weather.every(series)&&Array.isArray(p.marine)&&(p.marine.length===0||(p.marine.length===25&&p.marine.every(series)))&&p.points?.length===25&&p.points.every(v=>Number.isFinite(v.lat)&&Number.isFinite(v.lon))&&p.times?.length>=2&&p.times.length<=73&&p.times.every((t,i,a)=>Number.isFinite(t)&&(!i||t>a[i-1])&&p.weather.every(d=>d.hourly.time.includes(t)))&&p.start===p.times[0]&&p.end===p.times.at(-1);}catch{return false;}}
function state(p,t,now=Date.now()){if(now/1000>p.end)return 'EXPIRED';if(t<Math.floor(now/3600000)*3600)return 'PAST FORECAST';if(now-p.downloadedAt>12*3600000)return 'OLDER DOWNLOAD';return 'FORECAST';}
return {KEY,bounds,grid,value,pack,valid,state};});
